import type { PathwayPack } from '../types'
import { gloss, hint } from '../packHelpers'

/**
 * Community Support Foundations content pack.
 * Same progression skeleton as Construction — people-care / support-work craft.
 * Aligned to Skills for Care / Care Certificate values: dignity, privacy, choice,
 * respect, confidentiality, and escalate-when-unsure (support / observe / report).
 */
export const communityPack: PathwayPack = {
  id: 'community',
  skillDomains: {
    vocabulary: 'Vocabulary',
    safety: 'Safety',
    tools: 'Support tools',
    systems: 'Community skills',
  },
  unitGoals: {
    3: {
      goal: 'Learn the Level-1 support words you will hear in Alberta community workplaces.',
      outcomes: [
        'See each object and hear English',
        'Connect the English word to the real support action',
      ],
    },
    4: {
      goal: 'Use English with support, then prove you can find and follow person-centred language.',
      outcomes: [
        'Match pictures to English words',
        'Find objects in a busy welcome area',
        'Follow short workplace instructions',
        'Understand dignity, privacy, and consent phrases',
      ],
    },
    5: {
      goal: 'Build the digital, safety, tool, and systems foundations community roles expect.',
      outcomes: [
        'Practice school computer tasks',
        'Pass required privacy and hygiene safety checks',
        'Name support tools and community systems',
      ],
    },
    6: {
      goal: 'Prove readiness under observation, then connect to community employment support.',
      outcomes: [
        'Rehearse competent support skill order',
        'Make respectful placement decisions',
        'Pass the final checks and open employment support',
      ],
    },
  },
  stepTitles: {
    12: {
      title: 'Support Language',
      help: 'Hear a community-support phrase. Choose what it means.',
      purpose: 'Useful English for dignity, privacy, consent, and escalation at work.',
    },
    15: {
      title: 'Support Tools & Materials',
      help: 'Learn each support tool group. Answer one check.',
      purpose: 'Safe naming before safe use with an instructor.',
    },
    16: {
      title: 'Community Systems',
      help: 'Learn each system. Answer one check.',
      purpose: 'Your task helps people stay safe, informed, and supported with dignity.',
    },
    18: {
      title: 'Placement Training',
      help: 'Make support decisions and log the day like a real team member.',
      purpose: 'Daily judgment, notes, and supervisor feedback.',
    },
  },
  vocab: [
    {
      id: 'badge',
      english: 'Name badge',
      emoji: 'NB',
      imageKey: 'com-badge',
      definition: 'An ID card that shows your name and role so people know who you are.',
      sentence: 'Wear your name badge where people can see it.',
      gloss: gloss('Credencial', 'بطاقة الاسم', 'नाम बैज', 'የስም ካርድ', 'ናይ ስም ካርድ'),
    },
    {
      id: 'clipboard',
      english: 'Clipboard',
      emoji: 'CB',
      imageKey: 'com-clipboard',
      definition: 'A board that holds papers for notes and forms. Keep private pages covered.',
      sentence: 'Write the notes on the clipboard.',
      gloss: gloss('Portapapeles', 'لوح الكتابة', 'क्लिपबोर्ड', 'ክሊፕቦርድ', 'ክሊፕቦርድ'),
    },
    {
      id: 'first-aid',
      english: 'First aid kit',
      emoji: 'FA',
      imageKey: 'com-first-aid',
      definition: 'A marked box with supplies for small injuries. Know where it is before you need it.',
      sentence: 'Get the first aid kit from the wall.',
      gloss: gloss('Botiquín', 'صندوق الإسعافات الأولية', 'प्राथमिक चिकित्सा पेटी', 'የመጀመሪያ እርዳታ ሳጥን', 'ናይ ቀዳማይ ሓገዝ ሳንዱቕ'),
    },
    {
      id: 'gloves',
      english: 'Protective gloves',
      emoji: 'GL',
      imageKey: 'com-gloves',
      definition: 'Gloves that protect your hands during cleaning or personal-care support tasks.',
      sentence: 'Put on protective gloves before cleaning.',
      gloss: gloss('Guantes protectores', 'قفازات واقية', 'सुरक्षा दस्ताने', 'መከላከያ ጓንት', 'መከላኸሊ ጓንቲ'),
    },
    {
      id: 'schedule',
      english: 'Schedule',
      emoji: 'SCH',
      imageKey: 'com-schedule',
      definition: 'A plan that shows times and tasks for the day. Check it before each visit.',
      sentence: 'Check the schedule for your next visit.',
      gloss: gloss('Horario', 'جدول المواعيد', 'समयसारिणी', 'የጊዜ ሰሌዳ', 'ናይ ግዜ ሰሌዳ'),
    },
    {
      id: 'phone',
      english: 'Work phone',
      emoji: 'PH',
      imageKey: 'com-phone',
      definition: 'A phone used for work calls, check-ins, and calling a supervisor.',
      sentence: 'Call the supervisor on the work phone.',
      gloss: gloss('Teléfono de trabajo', 'هاتف العمل', 'काम का फ़ोन', 'የሥራ ስልክ', 'ናይ ስራኽ ስልኪ'),
    },
    {
      id: 'welcome',
      english: 'Welcome desk',
      emoji: 'WD',
      imageKey: 'com-welcome',
      definition: 'The front desk where people arrive, ask for help, and begin intake.',
      sentence: 'Meet the visitor at the welcome desk.',
      gloss: gloss('Recepción', 'مكتب الاستقبال', 'स्वागत डेस्क', 'የአቀባበል ዴስክ', 'ናይ ኣቀባብላ ዴስክ'),
    },
    {
      id: 'consent',
      english: 'Consent form',
      emoji: 'CF',
      imageKey: 'com-consent',
      definition: 'A form that records permission before you enter a private space or start a support task.',
      sentence: 'Check the consent form before you enter.',
      gloss: gloss(
        'Formulario de consentimiento',
        'استمارة الموافقة',
        'सहमति फॉर्म',
        'የፈቃድ ቅጽ',
        'ናይ ፍቓድ ቅጥዒ',
      ),
    },
    {
      id: 'hygiene',
      english: 'Hygiene station',
      emoji: 'HY',
      imageKey: 'com-hygiene',
      definition: 'A place with soap, sanitizer, and supplies for clean hands and safe support.',
      sentence: 'Use the hygiene station before the task.',
      gloss: gloss(
        'Estación de higiene',
        'محطة النظافة',
        'स्वच्छता स्टेशन',
        'የንፅህና ጣቢያ',
        'ናይ ጽሬት ጣብያ',
      ),
    },
  ],
  wordActions: [
    {
      id: 'wa-badge',
      termId: 'badge',
      title: 'Name badge in action',
      body: 'Clip the badge where clients and coworkers can read your name and role. Never wear someone else’s badge.',
      actionCue: 'Badge visible. Name clear. Role clear.',
    },
    {
      id: 'wa-clipboard',
      termId: 'clipboard',
      title: 'Clipboard in action',
      body: 'Write only what is needed. Keep private pages covered from public view. Return it to a secure place.',
      actionCue: 'Clear notes. Private papers covered. Secure storage.',
    },
    {
      id: 'wa-first-aid',
      termId: 'first-aid',
      title: 'First aid kit in action',
      body: 'Know where the kit hangs. Tell a supervisor if supplies are low. Follow trained steps only.',
      actionCue: 'Know the location. Report low supplies. Stay in role.',
    },
    {
      id: 'wa-gloves',
      termId: 'gloves',
      title: 'Protective gloves in action',
      body: 'Clean hands, then put gloves on before cleaning or personal-care support. Dispose as trained.',
      actionCue: 'Hands clean. Gloves on before the task. Dispose as trained.',
    },
    {
      id: 'wa-schedule',
      termId: 'schedule',
      title: 'Schedule in action',
      body: 'Check times and locations before each visit. Arrive a few minutes early. Escalate conflicts.',
      actionCue: 'Check the schedule. Arrive ready. Confirm conflicts.',
    },
    {
      id: 'wa-phone',
      termId: 'phone',
      title: 'Work phone in action',
      body: 'Use a calm voice. Confirm who you are speaking with before you share details. Call a supervisor when unsure.',
      actionCue: 'Calm voice. Confirm identity. Escalate when unsure.',
    },
    {
      id: 'wa-welcome',
      termId: 'welcome',
      title: 'Welcome desk in action',
      body: 'Greet people kindly. Ask how you can help. Guide them to the right support without rushing.',
      actionCue: 'Greet. Listen. Guide with respect.',
    },
    {
      id: 'wa-consent',
      termId: 'consent',
      title: 'Consent form in action',
      body: 'Ask permission before you enter a private room or begin a support task. Record consent as trained.',
      actionCue: 'Ask first. Wait for yes. Record as trained.',
    },
    {
      id: 'wa-hygiene',
      termId: 'hygiene',
      title: 'Hygiene station in action',
      body: 'Use soap or sanitizer at the hygiene station before and after support tasks that need clean hands.',
      actionCue: 'Clean hands before. Clean hands after. Restock if empty.',
    },
  ],
  eyeSpyScenes: [
    {
      id: 'desk-a-badge',
      title: 'Welcome area A',
      instruction: 'Find the name badge. Tap it in the scene, then confirm the English name.',
      targetId: 'badge',
      distractors: ['Clipboard', 'Work phone', 'Schedule'],
      variantGroup: 'desk-badge',
      hotspots: [
        { id: 'badge', label: 'Name badge', answer: 'Name badge', imageKey: 'com-badge', x: 16, y: 22, w: 20, h: 24 },
        { id: 'clipboard', label: 'Clipboard', answer: 'Clipboard', imageKey: 'com-clipboard', x: 52, y: 48, w: 24, h: 28 },
        { id: 'phone', label: 'Work phone', answer: 'Work phone', imageKey: 'com-phone', x: 72, y: 20, w: 18, h: 26 },
        { id: 'schedule', label: 'Schedule', answer: 'Schedule', imageKey: 'com-schedule', x: 34, y: 55, w: 22, h: 24 },
      ],
    },
    {
      id: 'desk-b-badge',
      title: 'Welcome area B',
      instruction: 'Find the name badge. Tap it in the scene, then confirm the English name.',
      targetId: 'badge',
      distractors: ['First aid kit', 'Protective gloves', 'Welcome desk'],
      variantGroup: 'desk-badge',
      hotspots: [
        { id: 'first-aid', label: 'First aid kit', answer: 'First aid kit', imageKey: 'com-first-aid', x: 12, y: 18, w: 22, h: 26 },
        { id: 'badge', label: 'Name badge', answer: 'Name badge', imageKey: 'com-badge', x: 58, y: 40, w: 20, h: 24 },
        { id: 'gloves', label: 'Protective gloves', answer: 'Protective gloves', imageKey: 'com-gloves', x: 38, y: 58, w: 22, h: 22 },
        { id: 'welcome', label: 'Welcome desk', answer: 'Welcome desk', imageKey: 'com-welcome', x: 74, y: 14, w: 20, h: 28 },
      ],
    },
    {
      id: 'room-a-kit',
      title: 'Support room A',
      instruction: 'Find the first aid kit. Tap it in the scene, then confirm the English name.',
      targetId: 'first-aid',
      distractors: ['Clipboard', 'Name badge', 'Schedule'],
      variantGroup: 'room-kit',
      hotspots: [
        { id: 'first-aid', label: 'First aid kit', answer: 'First aid kit', imageKey: 'com-first-aid', x: 20, y: 20, w: 22, h: 28 },
        { id: 'clipboard', label: 'Clipboard', answer: 'Clipboard', imageKey: 'com-clipboard', x: 55, y: 50, w: 24, h: 26 },
        { id: 'badge', label: 'Name badge', answer: 'Name badge', imageKey: 'com-badge', x: 70, y: 18, w: 18, h: 22 },
        { id: 'schedule', label: 'Schedule', answer: 'Schedule', imageKey: 'com-schedule', x: 40, y: 55, w: 22, h: 24 },
      ],
    },
    {
      id: 'room-b-kit',
      title: 'Support room B',
      instruction: 'Find the first aid kit. Tap it in the scene, then confirm the English name.',
      targetId: 'first-aid',
      distractors: ['Protective gloves', 'Work phone', 'Welcome desk'],
      variantGroup: 'room-kit',
      hotspots: [
        { id: 'gloves', label: 'Protective gloves', answer: 'Protective gloves', imageKey: 'com-gloves', x: 14, y: 52, w: 22, h: 22 },
        { id: 'first-aid', label: 'First aid kit', answer: 'First aid kit', imageKey: 'com-first-aid', x: 48, y: 20, w: 22, h: 28 },
        { id: 'phone', label: 'Work phone', answer: 'Work phone', imageKey: 'com-phone', x: 72, y: 48, w: 18, h: 26 },
        { id: 'welcome', label: 'Welcome desk', answer: 'Welcome desk', imageKey: 'com-welcome', x: 30, y: 12, w: 22, h: 28 },
      ],
    },
    {
      id: 'hall-a-consent',
      title: 'Private hallway A',
      instruction: 'Find the consent form. Tap it in the scene, then confirm the English name.',
      targetId: 'consent',
      distractors: ['Clipboard', 'Name badge', 'Work phone'],
      variantGroup: 'hall-consent',
      hotspots: [
        { id: 'consent', label: 'Consent form', answer: 'Consent form', imageKey: 'com-consent', x: 42, y: 28, w: 24, h: 30 },
        { id: 'clipboard', label: 'Clipboard', answer: 'Clipboard', imageKey: 'com-clipboard', x: 12, y: 50, w: 22, h: 26 },
        { id: 'badge', label: 'Name badge', answer: 'Name badge', imageKey: 'com-badge', x: 70, y: 16, w: 18, h: 22 },
        { id: 'phone', label: 'Work phone', answer: 'Work phone', imageKey: 'com-phone', x: 68, y: 55, w: 18, h: 26 },
      ],
    },
    {
      id: 'hall-b-consent',
      title: 'Private hallway B',
      instruction: 'Find the consent form. Tap it in the scene, then confirm the English name.',
      targetId: 'consent',
      distractors: ['Hygiene station', 'Schedule', 'Protective gloves'],
      variantGroup: 'hall-consent',
      hotspots: [
        { id: 'hygiene', label: 'Hygiene station', answer: 'Hygiene station', imageKey: 'com-hygiene', x: 10, y: 20, w: 22, h: 28 },
        { id: 'consent', label: 'Consent form', answer: 'Consent form', imageKey: 'com-consent', x: 48, y: 42, w: 24, h: 30 },
        { id: 'schedule', label: 'Schedule', answer: 'Schedule', imageKey: 'com-schedule', x: 72, y: 14, w: 20, h: 24 },
        { id: 'gloves', label: 'Protective gloves', answer: 'Protective gloves', imageKey: 'com-gloves', x: 28, y: 58, w: 22, h: 22 },
      ],
    },
    {
      id: 'bay-a-hygiene',
      title: 'Care bay A',
      instruction: 'Find the hygiene station. Tap it in the scene, then confirm the English name.',
      targetId: 'hygiene',
      distractors: ['First aid kit', 'Protective gloves', 'Clipboard'],
      variantGroup: 'bay-hygiene',
      hotspots: [
        { id: 'hygiene', label: 'Hygiene station', answer: 'Hygiene station', imageKey: 'com-hygiene', x: 18, y: 24, w: 24, h: 32 },
        { id: 'first-aid', label: 'First aid kit', answer: 'First aid kit', imageKey: 'com-first-aid', x: 58, y: 16, w: 22, h: 26 },
        { id: 'gloves', label: 'Protective gloves', answer: 'Protective gloves', imageKey: 'com-gloves', x: 70, y: 52, w: 20, h: 22 },
        { id: 'clipboard', label: 'Clipboard', answer: 'Clipboard', imageKey: 'com-clipboard', x: 40, y: 58, w: 22, h: 24 },
      ],
    },
    {
      id: 'bay-b-hygiene',
      title: 'Care bay B',
      instruction: 'Find the hygiene station. Tap it in the scene, then confirm the English name.',
      targetId: 'hygiene',
      distractors: ['Consent form', 'Welcome desk', 'Work phone'],
      variantGroup: 'bay-hygiene',
      hotspots: [
        { id: 'consent', label: 'Consent form', answer: 'Consent form', imageKey: 'com-consent', x: 12, y: 48, w: 22, h: 28 },
        { id: 'hygiene', label: 'Hygiene station', answer: 'Hygiene station', imageKey: 'com-hygiene', x: 46, y: 22, w: 24, h: 32 },
        { id: 'welcome', label: 'Welcome desk', answer: 'Welcome desk', imageKey: 'com-welcome', x: 72, y: 12, w: 20, h: 26 },
        { id: 'phone', label: 'Work phone', answer: 'Work phone', imageKey: 'com-phone', x: 68, y: 55, w: 18, h: 26 },
      ],
    },
    {
      id: 'front-a-welcome',
      title: 'Front lobby A',
      instruction: 'Find the welcome desk. Tap it in the scene, then confirm the English name.',
      targetId: 'welcome',
      distractors: ['Name badge', 'Schedule', 'Clipboard'],
      variantGroup: 'front-welcome',
      hotspots: [
        { id: 'welcome', label: 'Welcome desk', answer: 'Welcome desk', imageKey: 'com-welcome', x: 36, y: 30, w: 28, h: 34 },
        { id: 'badge', label: 'Name badge', answer: 'Name badge', imageKey: 'com-badge', x: 12, y: 18, w: 18, h: 22 },
        { id: 'schedule', label: 'Schedule', answer: 'Schedule', imageKey: 'com-schedule', x: 70, y: 48, w: 20, h: 24 },
        { id: 'clipboard', label: 'Clipboard', answer: 'Clipboard', imageKey: 'com-clipboard', x: 14, y: 55, w: 22, h: 26 },
      ],
    },
    {
      id: 'front-b-welcome',
      title: 'Front lobby B',
      instruction: 'Find the welcome desk. Tap it in the scene, then confirm the English name.',
      targetId: 'welcome',
      distractors: ['Hygiene station', 'Work phone', 'Consent form'],
      variantGroup: 'front-welcome',
      hotspots: [
        { id: 'hygiene', label: 'Hygiene station', answer: 'Hygiene station', imageKey: 'com-hygiene', x: 10, y: 22, w: 20, h: 28 },
        { id: 'phone', label: 'Work phone', answer: 'Work phone', imageKey: 'com-phone', x: 72, y: 18, w: 18, h: 26 },
        { id: 'welcome', label: 'Welcome desk', answer: 'Welcome desk', imageKey: 'com-welcome', x: 40, y: 38, w: 28, h: 34 },
        { id: 'consent', label: 'Consent form', answer: 'Consent form', imageKey: 'com-consent', x: 68, y: 55, w: 22, h: 28 },
      ],
    },
  ],
  workplaceInstructions: [
    {
      text: 'Wear your name badge where people can see it.',
      correct: 'Wear your name badge where people can see it',
      imageKey: 'com-badge',
      options: [
        'Wear your name badge where people can see it',
        'Hide your badge in a pocket',
        'Leave your badge at home',
        'Share your personal password',
      ],
      supportHint: hint(
        'Wear your name badge where people can see it.',
        'Lleva la credencial donde se vea.',
        'ارتدِ بطاقة الاسم حيث يمكن رؤيتها.',
        'नाम बैज वहाँ पहनो जहाँ लोग देख सकें।',
        'የስም ካርድ ሰዎች የሚያዩበት ቦታ ያድርጉ።',
        'ናይ ስም ካርድ ኣብ ዝረአየሉ ቦታ ኣስድጉ።',
      ),
    },
    {
      text: 'Put on protective gloves before cleaning.',
      correct: 'Put on protective gloves before cleaning',
      imageKey: 'com-gloves',
      options: [
        'Put on protective gloves before cleaning',
        'Clean with bare hands',
        'Skip hand washing',
        'Share gloves with a client',
      ],
      supportHint: hint(
        'Put on protective gloves before cleaning.',
        'Ponte guantes antes de limpiar.',
        'ارتدِ القفازات الواقية قبل التنظيف.',
        'सफाई से पहले सुरक्षा दस्ताने पहनो।',
        'ከማጽዳት በፊት መከላከያ ጓንት ያድርጉ።',
        'ቅድሚ ምጽራይ መከላኸሊ ጓንቲ ኣስድጉ።',
      ),
    },
    {
      text: 'Check the schedule for your next visit.',
      correct: 'Check the schedule for your next visit',
      imageKey: 'com-schedule',
      options: [
        'Check the schedule for your next visit',
        'Guess the next address',
        'Skip the visit quietly',
        'Arrive without reading the plan',
      ],
      supportHint: hint(
        'Check the schedule for your next visit.',
        'Revisa el horario para tu próxima visita.',
        'راجع جدول المواعيد لزيارتك القادمة.',
        'अगली विज़िट के लिए समयसारिणी जाँचो।',
        'ለቀጣኛው ጉብኝት የጊዜ ሰሌዳውን ያረጋግጡ።',
        'ንዝቕጽል ምብጻሕ ናይ ግዜ ሰሌዳ ኣረጋግጹ።',
      ),
    },
    {
      text: 'Meet the visitor at the welcome desk.',
      correct: 'Meet the visitor at the welcome desk',
      imageKey: 'com-welcome',
      options: [
        'Meet the visitor at the welcome desk',
        'Ignore the visitor',
        'Leave them outside',
        'Ask them for money first',
      ],
      supportHint: hint(
        'Meet the visitor at the welcome desk.',
        'Recibe al visitante en recepción.',
        'قابل الزائر في مكتب الاستقبال.',
        'विज़िटर से स्वागत डेस्क पर मिलो।',
        'ጎብኚውን በአቀባበል ዴስክ ያግኙ።',
        'ንበጻሒ ኣብ ናይ ኣቀባብላ ዴስክ ተቓበሉ።',
      ),
    },
    {
      text: 'Call the supervisor on the work phone.',
      correct: 'Call the supervisor on the work phone',
      imageKey: 'com-phone',
      options: [
        'Call the supervisor on the work phone',
        'Post the issue on social media',
        'Do nothing',
        'Give a client your personal number',
      ],
      supportHint: hint(
        'Call the supervisor on the work phone.',
        'Llama al supervisor al teléfono de trabajo.',
        'اتصل بالمشرف على هاتف العمل.',
        'सुपरवाइज़र को काम के फ़ोन पर कॉल करो।',
        'ተቆጣጣሪውን በሥራ ስልክ ይደውሉ።',
        'ንሱፐርቫይዘር ብናይ ስራኽ ስልኪ ደውሉ።',
      ),
    },
    {
      text: 'Check the consent form before you enter.',
      correct: 'Check the consent form before you enter',
      imageKey: 'com-consent',
      options: [
        'Check the consent form before you enter',
        'Walk in without asking',
        'Ignore the person’s choice',
        'Start the task without permission',
      ],
      supportHint: hint(
        'Check the consent form before you enter.',
        'Revisa el formulario de consentimiento antes de entrar.',
        'راجع استمارة الموافقة قبل الدخول.',
        'अंदर जाने से पहले सहमति फॉर्म जाँचो।',
        'ከመግባት በፊት የፈቃድ ቅጹን ያረጋግጡ።',
        'ቅድሚ ምእታው ንናይ ፍቓድ ቅጥዒ ኣረጋግጹ።',
      ),
    },
    {
      text: 'Use the hygiene station before the task.',
      correct: 'Use the hygiene station before the task',
      imageKey: 'com-hygiene',
      options: [
        'Use the hygiene station before the task',
        'Skip hand cleaning',
        'Share used towels',
        'Start with dirty hands',
      ],
      supportHint: hint(
        'Use the hygiene station before the task.',
        'Usa la estación de higiene antes de la tarea.',
        'استخدم محطة النظافة قبل المهمة.',
        'कार्य से पहले स्वच्छता स्टेशन इस्तेमाल करो।',
        'ከተግባሩ በፊት የንፅህና ጣቢያ ይጠቀሙ።',
        'ቅድሚ ዕማም ናይ ጽሬት ጣብያ ተጠቐሙ።',
      ),
    },
    {
      text: 'Keep private notes covered from public view.',
      correct: 'Keep private notes covered from public view',
      imageKey: 'com-clipboard',
      options: [
        'Keep private notes covered from public view',
        'Leave files open on the welcome desk',
        'Read notes aloud in the lobby',
        'Post details online',
      ],
      supportHint: hint(
        'Keep private notes covered from public view.',
        'Mantén las notas privadas cubiertas.',
        'أبقِ الملاحظات الخاصة مغطاة عن الأنظار.',
        'निजी नोट्स को सार्वजनिक दृष्टि से ढककर रखो।',
        'የግል ማስታወሻዎችን ከሕዝብ እይታ ይሸፍኑ።',
        'ናይ ውልቀ መልክታት ካብ ሕዝባዊ ርእይቶ ኽደኑ።',
      ),
    },
    {
      text: 'Get the first aid kit from the wall.',
      correct: 'Get the first aid kit from the wall',
      imageKey: 'com-first-aid',
      options: [
        'Get the first aid kit from the wall',
        'Ignore a small injury',
        'Use random desk supplies',
        'Film the injury first',
      ],
      supportHint: hint(
        'Get the first aid kit from the wall.',
        'Toma el botiquín de la pared.',
        'خذ صندوق الإسعافات الأولية من الجدار.',
        'दीवार से प्राथमिक चिकित्सा पेटी लो।',
        'ከግድግዳው የመጀመሪያ እርዳታ ሳጥን ውሰዱ።',
        'ካብ መንደቅ ናይ ቀዳማይ ሓገዝ ሳንዱቕ ውሰዱ።',
      ),
    },
  ],
  sitePhrases: [
    {
      en: 'How can I help you today?',
      why: 'A calm, respectful opening that centres the person’s choice.',
      prompt: 'What is this phrase for?',
      answer: 'Offer help politely',
      options: ['Offer help politely', 'End the visit', 'Ask for money', 'Ignore the person'],
    },
    {
      en: 'May I come in?',
      why: 'Consent before entering a private space protects dignity.',
      prompt: 'When do you say this?',
      answer: 'Before entering a private room',
      options: [
        'Before entering a private room',
        'After you already walked in',
        'Only if a supervisor is watching',
        'Never — just open the door',
      ],
    },
    {
      en: 'Your information stays private.',
      why: 'Confidentiality builds trust and follows Care Certificate standards.',
      prompt: 'What does this phrase promise?',
      answer: 'Keep personal details confidential',
      options: [
        'Keep personal details confidential',
        'Post details publicly',
        'Share with strangers',
        'Sell the notes',
      ],
    },
    {
      en: 'I will call my supervisor.',
      why: 'Escalate when you are unsure, unsafe, or outside your role.',
      prompt: 'What are you doing?',
      answer: 'Getting help from a supervisor',
      options: [
        'Getting help from a supervisor',
        'Quitting the job',
        'Sharing private details online',
        'Guessing alone',
      ],
    },
    {
      en: 'Please wait here. I will check.',
      why: 'Gives people clarity while you confirm information.',
      prompt: 'What should the person do?',
      answer: 'Wait while you check',
      options: [
        'Wait while you check',
        'Leave immediately',
        'Enter a private room alone',
        'Take files home',
      ],
    },
    {
      en: 'You can say no. That is okay.',
      why: 'Choice and respect are person-centred values.',
      prompt: 'What does this phrase protect?',
      answer: 'The person’s right to refuse',
      options: [
        'The person’s right to refuse',
        'Your right to force a task',
        'A reason to gossip',
        'A password reset',
      ],
    },
    {
      en: 'I will knock and wait.',
      why: 'Privacy and dignity start at the door.',
      prompt: 'What habit does this phrase show?',
      answer: 'Respect private space before entering',
      options: [
        'Respect private space before entering',
        'Enter without warning',
        'Listen at the door for gossip',
        'Leave the door open for others',
      ],
    },
    {
      en: 'I support. I do not diagnose.',
      why: 'Role boundaries: support, observe, and report — not clinical advice.',
      prompt: 'What does this remind you?',
      answer: 'Stay in your support role',
      options: [
        'Stay in your support role',
        'Give medical diagnoses',
        'Counsel as a therapist',
        'Ignore all concerns',
      ],
    },
    {
      en: 'I will write what I saw, not what I guess.',
      why: 'Accurate documentation protects people and teams.',
      prompt: 'What belongs in notes?',
      answer: 'Facts you observed',
      options: [
        'Facts you observed',
        'Rumours from the lobby',
        'Your personal opinions only',
        'Someone else’s password',
      ],
    },
    {
      en: 'Stop. I need to report a concern.',
      why: 'Safeguarding and stop-work for people: escalate risk early.',
      prompt: 'When do you use this phrase?',
      answer: 'When something looks unsafe or wrong',
      options: [
        'When something looks unsafe or wrong',
        'Only after someone is hurt',
        'Never — keep quiet',
        'Only on social media',
      ],
    },
  ],
  safetyQuiz: [
    {
      id: 'cs1',
      prompt: 'What should you wear so people know who you are?',
      emoji: 'NB',
      imageKey: 'com-badge',
      options: ['Name badge', 'No identification', 'A costume mask', 'Someone else’s badge'],
      answer: 'Name badge',
      teachCorrect: 'Name badge visible builds trust and workplace safety.',
      teachWrong: 'Wear your own name badge where people can see it.',
    },
    {
      id: 'cs2',
      prompt: 'Before a cleaning or personal-care support task, you should…',
      emoji: 'GL',
      imageKey: 'com-gloves',
      options: [
        'Use the hygiene station, then put on protective gloves',
        'Use bare hands',
        'Skip hand hygiene',
        'Share used gloves',
      ],
      answer: 'Use the hygiene station, then put on protective gloves',
      teachCorrect: 'Clean hands and protective gloves protect you and the person you support.',
      teachWrong: 'Hygiene first, then gloves on before the task.',
    },
    {
      id: 'cs3',
      prompt: 'Someone asks you to share another person’s private details. Best action?',
      emoji: 'PV',
      imageKey: 'com-clipboard',
      options: [
        'Refuse politely and follow privacy rules / ask a supervisor if unsure',
        'Share the details quietly',
        'Post the story online',
        'Trade information for a favor',
      ],
      answer: 'Refuse politely and follow privacy rules / ask a supervisor if unsure',
      teachCorrect: 'A privacy breach starts when you share without permission. Confidentiality is non-negotiable.',
      teachWrong: 'Do not share private details. Escalate if you are unsure.',
    },
    {
      id: 'cs4',
      prompt: 'You are unsure about a private request outside your role. What do you do?',
      emoji: 'PH',
      imageKey: 'com-phone',
      options: [
        'Call your supervisor on the work phone',
        'Guess and hope',
        'Post online',
        'Share the story with friends',
      ],
      answer: 'Call your supervisor on the work phone',
      teachCorrect: 'Escalate early. Support, observe, report — do not diagnose or counsel alone.',
      teachWrong: 'Call your supervisor when unsure or outside your role.',
    },
    {
      id: 'cs5',
      prompt: 'Before you enter a private room for support, you should…',
      emoji: 'CF',
      imageKey: 'com-consent',
      options: [
        'Knock, ask permission / check consent, then enter',
        'Walk in without asking',
        'Open the door and start filming',
        'Enter only if the person looks busy',
      ],
      answer: 'Knock, ask permission / check consent, then enter',
      teachCorrect: 'Consent before enter protects dignity, privacy, and choice.',
      teachWrong: 'Always knock and get consent before you enter.',
    },
    {
      id: 'cs6',
      prompt: 'You see something that looks unsafe or wrong for a person you support. What do you do?',
      emoji: '!',
      imageKey: 'com-phone',
      options: [
        'Stop, keep the person safe if you can, and report the concern to a supervisor',
        'Ignore it and finish your tasks',
        'Gossip about it at lunch',
        'Post it on social media',
      ],
      answer: 'Stop, keep the person safe if you can, and report the concern to a supervisor',
      teachCorrect: 'Every worker can stop and report a concern. Safeguarding comes first.',
      teachWrong: 'Stop-work for people: report concerns to a supervisor right away.',
    },
    {
      id: 'cs7',
      prompt: 'Where should you go first for supplies for a small injury?',
      emoji: 'FA',
      imageKey: 'com-first-aid',
      options: [
        'The first aid kit on the wall (then follow trained steps / get a supervisor if needed)',
        'A random drawer of snacks',
        'Someone’s personal bag',
        'Social media for advice',
      ],
      answer: 'The first aid kit on the wall (then follow trained steps / get a supervisor if needed)',
      teachCorrect: 'Know the first aid kit location before you need it. Stay in trained steps and escalate when needed.',
      teachWrong: 'Use the marked first aid kit and get help if you are unsure.',
    },
  ],
  toolCategories: [
    {
      title: 'Identification',
      why: 'Badges and sign-in sheets show who is present and build trust.',
      mark: 'ID',
      prompt: 'Name badges belong to which group?',
      answer: 'Identification',
      options: ['Identification', 'Care/hygiene supplies', 'Communication', 'Forms & records'],
    },
    {
      title: 'Care/hygiene supplies',
      why: 'Gloves, first aid, and hygiene stations protect people during support tasks.',
      mark: 'CH',
      prompt: 'First aid kits, protective gloves, and hygiene stations belong to…',
      answer: 'Care/hygiene supplies',
      options: ['Communication', 'Care/hygiene supplies', 'Identification', 'Schedules'],
    },
    {
      title: 'Communication',
      why: 'Work phones keep the team connected for check-ins and escalation.',
      mark: 'CM',
      prompt: 'Work phones belong to which group?',
      answer: 'Communication',
      options: ['Care/hygiene supplies', 'Forms & records', 'Communication', 'Furniture'],
    },
    {
      title: 'Forms & records',
      why: 'Clipboards, schedules, consent forms, and notes keep support accurate and private.',
      mark: 'FR',
      prompt: 'Clipboards, schedules, and consent forms belong to…',
      answer: 'Forms & records',
      options: ['Forms & records', 'Care/hygiene supplies', 'Identification', 'Break rooms'],
    },
  ],
  systemTopics: [
    {
      title: 'Welcome & intake',
      why: 'Greet people, confirm needs, and start support safely with dignity.',
      mark: 'WI',
      prompt: 'Greeting a visitor and starting a file is part of…',
      answer: 'Welcome & intake',
      options: ['Welcome & intake', 'Follow-up / documentation', 'Closing', 'Inventory'],
    },
    {
      title: 'Daily support plan',
      why: 'Schedules and task lists guide respectful, person-centred care.',
      mark: 'DP',
      prompt: 'Checking today’s visits against a schedule is…',
      answer: 'Daily support plan',
      options: ['Shipping', 'Daily support plan', 'Payroll only', 'Marketing'],
    },
    {
      title: 'Privacy & dignity',
      why: 'Keep personal information confidential and treat every person with respect.',
      mark: 'PD',
      prompt: 'Covering private notes and asking before you enter belongs to…',
      answer: 'Privacy & dignity',
      options: ['Privacy & dignity', 'Public posting', 'Guesswork', 'Speed contests'],
    },
    {
      title: 'Escalation & safeguarding report',
      why: 'Call a supervisor when risk, uncertainty, or safeguarding concerns appear.',
      mark: 'ER',
      prompt: 'Calling a supervisor about a safety or safeguarding concern is…',
      answer: 'Escalation & safeguarding report',
      options: [
        'Escalation & safeguarding report',
        'Ignoring risk',
        'Social media',
        'Leaving early',
      ],
    },
    {
      title: 'Follow-up / documentation',
      why: 'Confirm people received help and write clear, factual notes.',
      mark: 'FU',
      prompt: 'Checking in after a visit and writing factual notes supports…',
      answer: 'Follow-up / documentation',
      options: [
        'Follow-up / documentation',
        'Ignoring outcomes',
        'Deleting notes',
        'Skipping the schedule',
      ],
    },
  ],
  observationScenarios: [
    {
      id: 'welcome-ready',
      title: 'Welcome desk readiness',
      situation: 'Your supervisor asks you to open the welcome desk ready for visitors.',
      skill: 'Welcome readiness',
      steps: [
        { id: 'badge', label: 'Name badge on and visible', correctOrder: 1 },
        { id: 'desk', label: 'Welcome desk tidy and stocked', correctOrder: 2 },
        { id: 'phone', label: 'Work phone charged and nearby', correctOrder: 3 },
        { id: 'open', label: 'Signal that you are ready to greet people', correctOrder: 4 },
      ],
      passNote: 'Competent welcome is prepared before the first visitor arrives.',
    },
    {
      id: 'knock-consent',
      title: 'Knock and consent before enter',
      situation: 'Your supervisor watches you approach a private room for a scheduled support visit.',
      skill: 'Consent before enter',
      steps: [
        { id: 'knock', label: 'Knock and wait for a response', correctOrder: 1 },
        { id: 'ask', label: 'Ask “May I come in?” / check consent', correctOrder: 2 },
        { id: 'wait', label: 'Wait for yes before you step in', correctOrder: 3 },
        { id: 'enter', label: 'Enter calmly and state why you are there', correctOrder: 4 },
      ],
      passNote: 'Dignity means you never enter a private space without consent.',
    },
    {
      id: 'privacy-notes',
      title: 'Protect private notes',
      situation: 'Your supervisor watches you handle a clipboard with personal information.',
      skill: 'Privacy',
      steps: [
        { id: 'cover', label: 'Keep private pages covered from public view', correctOrder: 1 },
        { id: 'write', label: 'Write only facts that are needed', correctOrder: 2 },
        { id: 'store', label: 'Return the clipboard to the secure place', correctOrder: 3 },
        { id: 'confirm', label: 'Confirm with the supervisor that notes are secure', correctOrder: 4 },
      ],
      passNote: 'Privacy means personal information stays covered, limited, and secure.',
    },
    {
      id: 'gloves-task',
      title: 'Gloves before the support task',
      situation: 'Your supervisor asks you to prepare for a cleaning support task.',
      skill: 'Hygiene and protective gloves',
      steps: [
        { id: 'hygiene', label: 'Use the hygiene station as trained', correctOrder: 1 },
        { id: 'gloves', label: 'Put on protective gloves', correctOrder: 2 },
        { id: 'task', label: 'Complete the cleaning task carefully', correctOrder: 3 },
        { id: 'dispose', label: 'Remove and dispose of gloves as trained', correctOrder: 4 },
      ],
      passNote: 'Hygiene then gloves — before the task — protects both you and the person you support.',
    },
    {
      id: 'escalate-document',
      title: 'Escalate, then document',
      situation: 'A visitor asks for something outside your role, or you notice a safeguarding concern.',
      skill: 'Escalation and documentation',
      steps: [
        { id: 'listen', label: 'Listen respectfully without promising what you cannot do', correctOrder: 1 },
        { id: 'call', label: 'Call the supervisor on the work phone', correctOrder: 2 },
        { id: 'follow', label: 'Follow the supervisor’s direction and update the person', correctOrder: 3 },
        { id: 'note', label: 'Write factual notes about what you saw and did', correctOrder: 4 },
      ],
      passNote: 'Competent support means escalate first, then document facts — never guess or diagnose.',
    },
  ],
  siteDecisions: [
    {
      id: 'lost-visitor',
      title: 'Lost visitor',
      scene: 'A visitor looks confused near the entrance.',
      prompt: 'What should you do first?',
      options: [
        'Greet them and ask how you can help',
        'Ignore them',
        'Ask for their passwords',
        'Tell them to leave',
      ],
      answer: 'Greet them and ask how you can help',
      teachCorrect: 'A calm welcome reduces stress and keeps people safe.',
      teachWrong: 'Start with a respectful greeting at the welcome desk.',
    },
    {
      id: 'private-ask',
      title: 'Private request',
      scene: 'Someone asks you to share another person’s private details.',
      prompt: 'Best action?',
      options: [
        'Refuse politely and follow privacy rules / ask a supervisor if unsure',
        'Share the details quietly',
        'Post the story online',
        'Trade information for a favor',
      ],
      answer: 'Refuse politely and follow privacy rules / ask a supervisor if unsure',
      teachCorrect: 'Privacy is non-negotiable. Confidentiality protects dignity.',
      teachWrong: 'Do not share private details. Escalate if unsure.',
    },
    {
      id: 'schedule-conflict',
      title: 'Schedule conflict',
      scene: 'Two visits appear at the same time on your schedule.',
      prompt: 'What should you do?',
      options: [
        'Call your supervisor and confirm the correct plan',
        'Pick one at random',
        'Skip both',
        'Arrive late without notice',
      ],
      answer: 'Call your supervisor and confirm the correct plan',
      teachCorrect: 'Escalate schedule conflicts early so people are not left waiting.',
      teachWrong: 'Confirm with a supervisor before changing the plan.',
    },
    {
      id: 'small-injury',
      title: 'Small injury',
      scene: 'A coworker has a small cut and asks for help.',
      prompt: 'Best first move?',
      options: [
        'Get the first aid kit and follow trained steps / get a supervisor if needed',
        'Ignore it',
        'Use random supplies from a desk',
        'Film the injury',
      ],
      answer: 'Get the first aid kit and follow trained steps / get a supervisor if needed',
      teachCorrect: 'Use the marked kit, stay in trained steps, and escalate when needed.',
      teachWrong: 'First aid kit location + trained steps + supervisor if unsure.',
    },
    {
      id: 'overhear-gossip',
      title: 'Overhearing gossip',
      scene: 'In the hallway you overhear coworkers gossiping about a person’s private situation.',
      prompt: 'Best response?',
      options: [
        'Do not join in; remind the team about privacy or tell a supervisor',
        'Add your own details to the story',
        'Record the gossip on your phone',
        'Repeat it at lunch',
      ],
      answer: 'Do not join in; remind the team about privacy or tell a supervisor',
      teachCorrect: 'Gossip is a privacy risk. Protect dignity and escalate if needed.',
      teachWrong: 'Never join gossip about people you support.',
    },
    {
      id: 'refuses-support',
      title: 'Person refuses support',
      scene: 'A person says “No” when you offer a scheduled support task.',
      prompt: 'What should you do?',
      options: [
        'Respect the refusal, stay calm, and tell your supervisor if needed',
        'Force the task anyway',
        'Get angry and leave without notes',
        'Argue until they agree',
      ],
      answer: 'Respect the refusal, stay calm, and tell your supervisor if needed',
      teachCorrect: 'Choice and respect are person-centred values. “No” is okay.',
      teachWrong: 'Never force support. Respect choice and escalate if required.',
    },
    {
      id: 'end-of-day',
      title: 'End-of-day notes',
      scene: 'You finished welcome desk support and two scheduled visits. Your supervisor was Sam.',
      prompt: 'What belongs in today’s placement notes?',
      options: [
        'Date, tasks you did, and supervisor name — facts only',
        'Only your lunch order',
        'Someone else’s private phone number',
        'Nothing. Notes are optional forever',
      ],
      answer: 'Date, tasks you did, and supervisor name — facts only',
      teachCorrect: 'Clear factual notes help instructors and employers trust your hours.',
      teachWrong: 'Log the date, real tasks, and who supervised you — no gossip.',
    },
  ],
  finalQuiz: [
    {
      id: 'cf1',
      prompt: 'Which item shows your name and role?',
      emoji: 'NB',
      imageKey: 'com-badge',
      options: ['Name badge', 'First aid kit', 'Clipboard', 'Schedule'],
      answer: 'Name badge',
      teachCorrect: 'The name badge shows who you are and builds trust.',
      teachWrong: 'Wear a name badge where people can see it.',
    },
    {
      id: 'cf2',
      prompt: 'Before cleaning support tasks, you should…',
      emoji: 'GL',
      imageKey: 'com-gloves',
      options: [
        'Use the hygiene station, then put on protective gloves',
        'Skip gloves',
        'Wear a visitor sticker only',
        'Put on headphones',
      ],
      answer: 'Use the hygiene station, then put on protective gloves',
      teachCorrect: 'Hygiene then gloves before the task.',
      teachWrong: 'Clean hands and gloves on first.',
    },
    {
      id: 'cf3',
      prompt: 'Greeting visitors and starting support is part of…',
      emoji: 'WI',
      options: ['Welcome & intake', 'Shipping', 'Inventory', 'Payroll only'],
      answer: 'Welcome & intake',
      teachCorrect: 'Welcome & intake starts support safely and with dignity.',
      teachWrong: 'Welcome & intake comes first.',
    },
    {
      id: 'cf4',
      prompt: 'If you are unsure about a private request, you should…',
      emoji: 'PH',
      imageKey: 'com-phone',
      options: [
        'Call your supervisor on the work phone',
        'Guess',
        'Post online',
        'Share with friends',
      ],
      answer: 'Call your supervisor on the work phone',
      teachCorrect: 'Escalate early. Stay in support / observe / report.',
      teachWrong: 'Call your supervisor when unsure.',
    },
    {
      id: 'cf5',
      prompt: '“May I come in?” protects…',
      emoji: 'CF',
      imageKey: 'com-consent',
      options: [
        'Consent, privacy, and dignity before you enter',
        'Faster task times only',
        'Your right to enter anytime',
        'Social media sharing',
      ],
      answer: 'Consent, privacy, and dignity before you enter',
      teachCorrect: 'Ask permission before you enter a private space.',
      teachWrong: 'Consent before enter is required.',
    },
    {
      id: 'cf6',
      prompt: 'Clipboards, schedules, and consent forms belong to…',
      emoji: 'FR',
      imageKey: 'com-clipboard',
      options: ['Forms & records', 'Care/hygiene supplies', 'Communication', 'Break rooms'],
      answer: 'Forms & records',
      teachCorrect: 'Forms & records keep support accurate and private.',
      teachWrong: 'Those tools are Forms & records.',
    },
    {
      id: 'cf7',
      prompt: 'A person refuses a support task. Best action?',
      emoji: 'CH',
      options: [
        'Respect the choice and tell a supervisor if needed',
        'Force the task',
        'Argue until they agree',
        'Gossip about the refusal',
      ],
      answer: 'Respect the choice and tell a supervisor if needed',
      teachCorrect: 'Person-centred support respects choice. “No” is okay.',
      teachWrong: 'Never force support. Respect refusal and escalate if required.',
    },
    {
      id: 'cf8',
      prompt: 'Calling a supervisor about a safeguarding concern is…',
      emoji: 'ER',
      imageKey: 'com-phone',
      options: [
        'Escalation & safeguarding report',
        'Ignoring risk',
        'Optional small talk',
        'A social media post',
      ],
      answer: 'Escalation & safeguarding report',
      teachCorrect: 'Safeguarding means escalate and document — do not stay silent.',
      teachWrong: 'Escalation & safeguarding report keeps people safe.',
    },
  ],
  employmentPrep: [
    {
      id: 'com-intro',
      prompt: 'An employer asks: “Why Purpose Academy?” Best answer?',
      options: [
        'I learned community support foundations, privacy, and workplace English with instructors who checked my skills',
        'I watched a few videos once',
        'I do not need privacy training',
        'I only want a paycheck with no learning',
      ],
      answer:
        'I learned community support foundations, privacy, and workplace English with instructors who checked my skills',
      teachCorrect: 'Connect your training to safety, dignity, language, and verified skill.',
      teachWrong: 'Employers want proof of foundations, not shortcuts.',
    },
    {
      id: 'com-privacy',
      prompt: 'Interview question: “How do you protect privacy?”',
      options: [
        'Keep notes covered, share only with approved people, ask a supervisor when unsure',
        'Talk about clients with friends',
        'Post stories online',
        'Leave files on the welcome desk overnight',
      ],
      answer: 'Keep notes covered, share only with approved people, ask a supervisor when unsure',
      teachCorrect: 'Privacy and dignity are core job skills.',
      teachWrong: 'Protect private information every time.',
    },
    {
      id: 'com-consent',
      prompt: 'An employer asks how you enter a private room. Best answer?',
      options: [
        'I knock, ask permission, and wait for consent before I enter',
        'I walk in if the door is unlocked',
        'I enter quickly so nobody notices',
        'I listen at the door first for gossip',
      ],
      answer: 'I knock, ask permission, and wait for consent before I enter',
      teachCorrect: 'Consent before enter shows person-centred practice.',
      teachWrong: 'Always knock and get consent before you enter.',
    },
    {
      id: 'com-boundaries',
      prompt: 'A partner says a person wants a diagnosis from you. You should…',
      options: [
        'Explain that you support, observe, and report — then call a supervisor',
        'Give a diagnosis to be helpful',
        'Counsel them as a therapist',
        'Ignore them completely',
      ],
      answer: 'Explain that you support, observe, and report — then call a supervisor',
      teachCorrect: 'Role boundaries protect people. Escalate clinical questions.',
      teachWrong: 'Do not diagnose or counsel. Support, observe, report.',
    },
    {
      id: 'com-schedule',
      prompt: 'A partner asks if you can start at 7:00 a.m. You should…',
      options: [
        'Give an honest answer about your availability',
        'Say yes to everything even if you cannot come',
        'Ignore the message',
        'Ask them to text your password',
      ],
      answer: 'Give an honest answer about your availability',
      teachCorrect: 'Clear, honest scheduling builds trust.',
      teachWrong: 'Be honest about when you can start work.',
    },
    {
      id: 'com-ready',
      prompt: 'You arrive for a placement walk-through. Best first move?',
      options: [
        'Bring your name badge and follow site privacy and safety rules',
        'Arrive without identification',
        'Share private stories first',
        'Skip meeting the supervisor',
      ],
      answer: 'Bring your name badge and follow site privacy and safety rules',
      teachCorrect: 'Show up ready: identified, respectful, on time.',
      teachWrong: 'Badge on and ready for the walk-through.',
    },
  ],
  unitCheckpoints: {
    3: [
      {
        id: 'uc3-c1',
        prompt: 'Which item shows your name and role?',
        emoji: 'NB',
        imageKey: 'com-badge',
        options: ['Name badge', 'Clipboard', 'Schedule', 'Work phone'],
        answer: 'Name badge',
        teachCorrect: 'Name badge shows who you are.',
        teachWrong: 'Wear a name badge.',
      },
      {
        id: 'uc3-c2',
        prompt: 'Before cleaning support tasks, put on…',
        emoji: 'GL',
        imageKey: 'com-gloves',
        options: ['Protective gloves', 'No gloves', 'A visitor sticker only', 'Headphones'],
        answer: 'Protective gloves',
        teachCorrect: 'Gloves on before the task (after hygiene).',
        teachWrong: 'Protective gloves first after clean hands.',
      },
      {
        id: 'uc3-c3',
        prompt: 'What records permission before you enter a private space?',
        emoji: 'CF',
        imageKey: 'com-consent',
        options: ['Consent form', 'Shipping label', 'Hard hat', 'Pallet'],
        answer: 'Consent form',
        teachCorrect: 'Consent form / asking permission protects dignity.',
        teachWrong: 'Check consent before you enter.',
      },
    ],
    4: [
      {
        id: 'uc4-c1',
        prompt: '“How can I help you today?” is used to…',
        emoji: 'HP',
        options: ['Offer help politely', 'End the visit', 'Ask for money', 'Ignore the person'],
        answer: 'Offer help politely',
        teachCorrect: 'A calm offer of help opens support with respect.',
        teachWrong: 'Offer help politely.',
      },
      {
        id: 'uc4-c2',
        prompt: '“Your information stays private” means…',
        emoji: 'PV',
        options: [
          'Keep personal details confidential',
          'Post details publicly',
          'Share with strangers',
          'Sell the notes',
        ],
        answer: 'Keep personal details confidential',
        teachCorrect: 'Privacy builds trust.',
        teachWrong: 'Keep details confidential.',
      },
      {
        id: 'uc4-c3',
        prompt: '“May I come in?” shows…',
        emoji: 'CF',
        imageKey: 'com-consent',
        options: [
          'Consent before entering a private room',
          'That you already entered',
          'That privacy does not matter',
          'That you are ending support',
        ],
        answer: 'Consent before entering a private room',
        teachCorrect: 'Ask permission before you enter.',
        teachWrong: 'Consent before enter protects dignity.',
      },
      {
        id: 'uc4-c4',
        prompt: 'A workplace instruction is…',
        emoji: 'WI',
        imageKey: 'com-schedule',
        options: [
          'A short English direction you must follow',
          'A song lyric',
          'Optional small talk',
          'Only for supervisors',
        ],
        answer: 'A short English direction you must follow',
        teachCorrect: 'Instructions keep the support team safe and coordinated.',
        teachWrong: 'Follow short English directions at work.',
      },
    ],
    5: [
      {
        id: 'uc5-c1',
        prompt: 'Greeting visitors and starting support is…',
        emoji: 'WI',
        options: ['Welcome & intake', 'Shipping', 'Inventory', 'Framing'],
        answer: 'Welcome & intake',
        teachCorrect: 'Welcome & intake starts the support path.',
        teachWrong: 'Welcome & intake comes first.',
      },
      {
        id: 'uc5-c2',
        prompt: 'Calling a supervisor about a safeguarding concern is…',
        emoji: 'ER',
        options: [
          'Escalation & safeguarding report',
          'Ignoring risk',
          'Social media',
          'Skipping work',
        ],
        answer: 'Escalation & safeguarding report',
        teachCorrect: 'Escalate early when unsure or unsafe.',
        teachWrong: 'Escalation & safeguarding report keeps people safe.',
      },
      {
        id: 'uc5-c3',
        prompt: 'First aid kits, gloves, and hygiene stations belong to…',
        emoji: 'CH',
        imageKey: 'com-hygiene',
        options: [
          'Care/hygiene supplies',
          'Identification only',
          'Communication only',
          'Break rooms',
        ],
        answer: 'Care/hygiene supplies',
        teachCorrect: 'Care/hygiene supplies protect people during support tasks.',
        teachWrong: 'Those tools are Care/hygiene supplies.',
      },
    ],
    6: [
      {
        id: 'uc6-c1',
        prompt: 'Competent observation means…',
        emoji: 'O',
        imageKey: 'com-badge',
        options: [
          'You show the skill correctly for an instructor',
          'You watched a video once',
          'You skipped privacy rules',
          'You guessed the steps',
        ],
        answer: 'You show the skill correctly for an instructor',
        teachCorrect: 'Observation proves real skill under review.',
        teachWrong: 'Show the correct steps for the instructor.',
      },
      {
        id: 'uc6-c2',
        prompt: 'A good placement note includes…',
        emoji: 'L',
        imageKey: 'com-clipboard',
        options: [
          'Date, tasks, and supervisor — facts only',
          'Only memes',
          'Other people’s passwords',
          'Gossip from the hallway',
        ],
        answer: 'Date, tasks, and supervisor — facts only',
        teachCorrect: 'Clear factual notes build trust.',
        teachWrong: 'Log date, tasks, and who supervised you.',
      },
      {
        id: 'uc6-c3',
        prompt: 'In an interview, lead with…',
        emoji: 'P',
        imageKey: 'com-welcome',
        options: [
          'Privacy, dignity, foundations, and verified skills',
          'Skipping training',
          'Avoiding English',
          'Guessing support words',
        ],
        answer: 'Privacy, dignity, foundations, and verified skills',
        teachCorrect: 'Employers want person-centred practice and proof of skill.',
        teachWrong: 'Talk about privacy, dignity, and what you can do.',
      },
    ],
  },
}
