import type { PathwayPack } from '../types'
import { gloss, hint } from '../packHelpers'

/**
 * Community Support Foundations content pack.
 * Same progression skeleton — people-care / support-work imagery and language.
 */
export const communityPack: PathwayPack = {
  id: 'community',
  skillDomains: {
    vocabulary: 'Vocabulary',
    safety: 'Safety',
    tools: 'Support tools',
    systems: 'Community skills',
  },
  unitGoals: {
    3: {
      goal: 'Learn the Level-1 support words you will hear in community workplaces.',
      outcomes: ['See each object and hear English', 'Connect the English word to the real action'],
    },
    4: {
      goal: 'Use English with support, then prove you can find and follow support-language cues.',
      outcomes: [
        'Match pictures to English words',
        'Find objects in a busy welcome area',
        'Follow short workplace instructions',
        'Understand common support phrases',
      ],
    },
    5: {
      goal: 'Build the digital, safety, tool, and systems foundations community roles expect.',
      outcomes: [
        'Practice school computer tasks',
        'Pass required safety checks',
        'Name support tools and community systems',
      ],
    },
    6: {
      goal: 'Prove readiness under observation, then connect to community employment support.',
      outcomes: [
        'Rehearse competent skill order',
        'Make respectful placement decisions',
        'Pass the final checks and open employment support',
      ],
    },
  },
  stepTitles: {
    12: {
      title: 'Support Language',
      help: 'Hear a community-support phrase. Choose what it means.',
      purpose: 'Useful English you will hear in Alberta community support workplaces.',
    },
    15: {
      title: 'Support Tools & Materials',
      help: 'Learn each support tool group. Answer one check.',
      purpose: 'Safe naming before safe use with an instructor.',
    },
    16: {
      title: 'Community Systems',
      help: 'Learn each system. Answer one check.',
      purpose: 'Your task helps people stay safe, informed, and supported.',
    },
    18: {
      title: 'Placement Training',
      help: 'Make support decisions and log the day like a real team member.',
      purpose: 'Daily judgment, notes, and supervisor feedback.',
    },
  },
  vocab: [
    {
      id: 'badge',
      english: 'Name badge',
      emoji: 'NB',
      imageKey: 'com-badge',
      definition: 'An ID card that shows your name and role.',
      sentence: 'Wear your name badge where people can see it.',
      gloss: gloss('Credencial', 'Bitaqa', 'Name badge', 'Name badge', 'Name badge'),
    },
    {
      id: 'clipboard',
      english: 'Clipboard',
      emoji: 'CB',
      imageKey: 'com-clipboard',
      definition: 'A board that holds papers for notes and forms.',
      sentence: 'Write the notes on the clipboard.',
      gloss: gloss('Portapapeles', 'Lawh kitabah', 'Clipboard', 'Clipboard', 'Clipboard'),
    },
    {
      id: 'first-aid',
      english: 'First aid kit',
      emoji: 'FA',
      imageKey: 'com-first-aid',
      definition: 'A box with supplies for small injuries.',
      sentence: 'Get the first aid kit from the wall.',
      gloss: gloss('Botiquin', 'Sanduq isaf', 'First aid kit', 'First aid kit', 'First aid kit'),
    },
    {
      id: 'gloves',
      english: 'Protective gloves',
      emoji: 'GL',
      imageKey: 'com-gloves',
      definition: 'Gloves that protect your hands during support tasks.',
      sentence: 'Put on protective gloves before cleaning.',
      gloss: gloss('Guantes protectores', 'Quffazat', 'Protective gloves', 'Protective gloves', 'Protective gloves'),
    },
    {
      id: 'schedule',
      english: 'Schedule',
      emoji: 'SCH',
      imageKey: 'com-schedule',
      definition: 'A plan that shows times and tasks for the day.',
      sentence: 'Check the schedule for your next visit.',
      gloss: gloss('Horario', 'Jadwal', 'Schedule', 'Schedule', 'Schedule'),
    },
    {
      id: 'phone',
      english: 'Work phone',
      emoji: 'PH',
      imageKey: 'com-phone',
      definition: 'A phone used for work calls and check-ins.',
      sentence: 'Call the supervisor on the work phone.',
      gloss: gloss('Telefono de trabajo', 'Hatiff amal', 'Work phone', 'Work phone', 'Work phone'),
    },
    {
      id: 'welcome',
      english: 'Welcome desk',
      emoji: 'WD',
      imageKey: 'com-welcome',
      definition: 'The front desk where people arrive and ask for help.',
      sentence: 'Meet the visitor at the welcome desk.',
      gloss: gloss('Recepcion', 'Maktab istiqbal', 'Welcome desk', 'Welcome desk', 'Welcome desk'),
    },
  ],
  wordActions: [
    {
      id: 'wa-badge',
      termId: 'badge',
      title: 'Name badge in action',
      body: 'Clip the badge where clients and coworkers can read it.',
      actionCue: 'Badge visible. Name clear. Role clear.',
    },
    {
      id: 'wa-clipboard',
      termId: 'clipboard',
      title: 'Clipboard in action',
      body: 'Write clear notes. Keep private information covered.',
      actionCue: 'Clear notes. Private papers covered.',
    },
    {
      id: 'wa-first-aid',
      termId: 'first-aid',
      title: 'First aid kit in action',
      body: 'Know where the kit is. Tell a supervisor if supplies are low.',
      actionCue: 'Know the location. Report low supplies.',
    },
    {
      id: 'wa-gloves',
      termId: 'gloves',
      title: 'Protective gloves in action',
      body: 'Put gloves on before cleaning or personal-care support tasks.',
      actionCue: 'Gloves on before the task. Dispose as trained.',
    },
    {
      id: 'wa-schedule',
      termId: 'schedule',
      title: 'Schedule in action',
      body: 'Check times before each visit. Arrive a few minutes early.',
      actionCue: 'Check the schedule. Arrive ready.',
    },
    {
      id: 'wa-phone',
      termId: 'phone',
      title: 'Work phone in action',
      body: 'Use a calm voice. Confirm the name before you share details.',
      actionCue: 'Calm voice. Confirm identity. Keep notes.',
    },
    {
      id: 'wa-welcome',
      termId: 'welcome',
      title: 'Welcome desk in action',
      body: 'Greet people kindly. Ask how you can help.',
      actionCue: 'Greet. Listen. Guide to the right support.',
    },
  ],
  eyeSpyScenes: [
    {
      id: 'desk-a-badge',
      title: 'Welcome area A',
      instruction: 'Find the name badge. Tap it in the scene, then confirm the English name.',
      targetId: 'badge',
      distractors: ['Clipboard', 'Work phone', 'Schedule'],
      variantGroup: 'desk-badge',
      hotspots: [
        { id: 'badge', label: 'Name badge', answer: 'Name badge', imageKey: 'com-badge', x: 16, y: 22, w: 20, h: 24 },
        { id: 'clipboard', label: 'Clipboard', answer: 'Clipboard', imageKey: 'com-clipboard', x: 52, y: 48, w: 24, h: 28 },
        { id: 'phone', label: 'Work phone', answer: 'Work phone', imageKey: 'com-phone', x: 72, y: 20, w: 18, h: 26 },
        { id: 'schedule', label: 'Schedule', answer: 'Schedule', imageKey: 'com-schedule', x: 34, y: 55, w: 22, h: 24 },
      ],
    },
    {
      id: 'desk-b-badge',
      title: 'Welcome area B',
      instruction: 'Find the name badge. Tap it in the scene, then confirm the English name.',
      targetId: 'badge',
      distractors: ['First aid kit', 'Protective gloves', 'Welcome desk'],
      variantGroup: 'desk-badge',
      hotspots: [
        { id: 'first-aid', label: 'First aid kit', answer: 'First aid kit', imageKey: 'com-first-aid', x: 12, y: 18, w: 22, h: 26 },
        { id: 'badge', label: 'Name badge', answer: 'Name badge', imageKey: 'com-badge', x: 58, y: 40, w: 20, h: 24 },
        { id: 'gloves', label: 'Protective gloves', answer: 'Protective gloves', imageKey: 'com-gloves', x: 38, y: 58, w: 22, h: 22 },
        { id: 'welcome', label: 'Welcome desk', answer: 'Welcome desk', imageKey: 'com-welcome', x: 74, y: 14, w: 20, h: 28 },
      ],
    },
    {
      id: 'room-a-kit',
      title: 'Support room A',
      instruction: 'Find the first aid kit. Tap it in the scene, then confirm the English name.',
      targetId: 'first-aid',
      distractors: ['Clipboard', 'Name badge', 'Schedule'],
      variantGroup: 'room-kit',
      hotspots: [
        { id: 'first-aid', label: 'First aid kit', answer: 'First aid kit', imageKey: 'com-first-aid', x: 20, y: 20, w: 22, h: 28 },
        { id: 'clipboard', label: 'Clipboard', answer: 'Clipboard', imageKey: 'com-clipboard', x: 55, y: 50, w: 24, h: 26 },
        { id: 'badge', label: 'Name badge', answer: 'Name badge', imageKey: 'com-badge', x: 70, y: 18, w: 18, h: 22 },
        { id: 'schedule', label: 'Schedule', answer: 'Schedule', imageKey: 'com-schedule', x: 40, y: 55, w: 22, h: 24 },
      ],
    },
    {
      id: 'room-b-kit',
      title: 'Support room B',
      instruction: 'Find the first aid kit. Tap it in the scene, then confirm the English name.',
      targetId: 'first-aid',
      distractors: ['Protective gloves', 'Work phone', 'Welcome desk'],
      variantGroup: 'room-kit',
      hotspots: [
        { id: 'gloves', label: 'Protective gloves', answer: 'Protective gloves', imageKey: 'com-gloves', x: 14, y: 52, w: 22, h: 22 },
        { id: 'first-aid', label: 'First aid kit', answer: 'First aid kit', imageKey: 'com-first-aid', x: 48, y: 20, w: 22, h: 28 },
        { id: 'phone', label: 'Work phone', answer: 'Work phone', imageKey: 'com-phone', x: 72, y: 48, w: 18, h: 26 },
        { id: 'welcome', label: 'Welcome desk', answer: 'Welcome desk', imageKey: 'com-welcome', x: 30, y: 12, w: 22, h: 28 },
      ],
    },
  ],
  workplaceInstructions: [
    {
      text: 'Wear your name badge where people can see it.',
      correct: 'Wear your name badge where people can see it',
      imageKey: 'com-badge',
      options: [
        'Wear your name badge where people can see it',
        'Hide your badge in a pocket',
        'Leave your badge at home',
        'Share your personal password',
      ],
      supportHint: hint(
        'Wear your name badge where people can see it.',
        'Lleva la credencial donde se vea.',
        'Irtiadi al-bitaqa haythu yuraha.',
        'Name badge dikhai de jahan log dekh saken.',
        'Yesem badge sewoch yemayayuyibat asdigu.',
        'Name badge ab zireAalo asdugu.',
      ),
    },
    {
      text: 'Put on protective gloves before cleaning.',
      correct: 'Put on protective gloves before cleaning',
      imageKey: 'com-gloves',
      options: [
        'Put on protective gloves before cleaning',
        'Clean with bare hands',
        'Skip hand washing',
        'Share gloves with a client',
      ],
      supportHint: hint(
        'Put on protective gloves before cleaning.',
        'Ponte guantes antes de limpiar.',
        'Irtiadi al-quffazat qabla al-tanzif.',
        'Safai se pehle protective gloves pehno.',
        'Ke maTbat befit protective gloves asdigu.',
        'Qidmi misray protective gloves asdugu.',
      ),
    },
    {
      text: 'Check the schedule for your next visit.',
      correct: 'Check the schedule for your next visit',
      imageKey: 'com-schedule',
      options: [
        'Check the schedule for your next visit',
        'Guess the next address',
        'Skip the visit quietly',
        'Arrive without reading the plan',
      ],
      supportHint: hint(
        'Check the schedule for your next visit.',
        'Revisa el horario para tu proxima visita.',
        'Raji al-jadwal lil-ziyara al-qadima.',
        'Agli visit ke liye schedule check karo.',
        'Lepotch gubet schedule yaregagtu.',
        'Natti asbab schedule aregagtsu.',
      ),
    },
    {
      text: 'Meet the visitor at the welcome desk.',
      correct: 'Meet the visitor at the welcome desk',
      imageKey: 'com-welcome',
      options: [
        'Meet the visitor at the welcome desk',
        'Ignore the visitor',
        'Leave them outside',
        'Ask them for money first',
      ],
      supportHint: hint(
        'Meet the visitor at the welcome desk.',
        'Recibe al visitante en recepcion.',
        'Iqabil al-za’ir fi maktab al-istiqbal.',
        'Visitor ko welcome desk par milo.',
        'Teadarinin be welcome desk asteweldu.',
        'NaAgagi ab welcome desk qebelu.',
      ),
    },
    {
      text: 'Call the supervisor on the work phone.',
      correct: 'Call the supervisor on the work phone',
      imageKey: 'com-phone',
      options: [
        'Call the supervisor on the work phone',
        'Post the issue on social media',
        'Do nothing',
        'Give a client your personal number',
      ],
      supportHint: hint(
        'Call the supervisor on the work phone.',
        'Llama al supervisor al telefono de trabajo.',
        'Ittasil bil-mushrif ala hatif al-amal.',
        'Supervisor ko work phone par call karo.',
        'Supervisorun be work phone deru.',
        'Supervisor b work phone deru.',
      ),
    },
  ],
  sitePhrases: [
    {
      en: 'How can I help you today?',
      why: 'A calm, respectful opening.',
      prompt: 'What is this phrase for?',
      answer: 'Offer help politely',
      options: ['Offer help politely', 'End the visit', 'Ask for money', 'Ignore the person'],
    },
    {
      en: 'Please wait here. I will check.',
      why: 'Gives people clarity while you confirm information.',
      prompt: 'What should the person do?',
      answer: 'Wait while you check',
      options: ['Wait while you check', 'Leave immediately', 'Enter a private room alone', 'Take files home'],
    },
    {
      en: 'I will call my supervisor.',
      why: 'Escalate when you are unsure or need support.',
      prompt: 'What are you doing?',
      answer: 'Getting help from a supervisor',
      options: ['Getting help from a supervisor', 'Quitting the job', 'Sharing private details online', 'Guessing alone'],
    },
    {
      en: 'Your information stays private.',
      why: 'Confidentiality builds trust.',
      prompt: 'What does this phrase promise?',
      answer: 'Keep personal details confidential',
      options: ['Keep personal details confidential', 'Post details publicly', 'Share with strangers', 'Sell the notes'],
    },
  ],
  safetyQuiz: [
    {
      id: 'cs1',
      prompt: 'What should you wear so people know who you are?',
      emoji: 'NB',
      imageKey: 'com-badge',
      options: ['Name badge', 'No identification', 'A costume mask', 'Someone else’s badge'],
      answer: 'Name badge',
      teachCorrect: 'Name badge visible builds trust and safety.',
      teachWrong: 'Wear your own name badge.',
    },
    {
      id: 'cs2',
      prompt: 'Before a cleaning or personal-care support task, you should…',
      emoji: 'GL',
      imageKey: 'com-gloves',
      options: ['Put on protective gloves', 'Use bare hands', 'Skip hand hygiene', 'Share used gloves'],
      answer: 'Put on protective gloves',
      teachCorrect: 'Protective gloves protect you and the person you support.',
      teachWrong: 'Gloves on before the task.',
    },
    {
      id: 'cs3',
      prompt: 'A visitor looks lost at the entrance. Best first action?',
      emoji: 'WD',
      imageKey: 'com-welcome',
      options: ['Greet them at the welcome desk and ask how you can help', 'Ignore them', 'Ask for personal passwords', 'Leave the building'],
      answer: 'Greet them at the welcome desk and ask how you can help',
      teachCorrect: 'Warm, clear welcome is the first safety and support step.',
      teachWrong: 'Meet people at the welcome desk.',
    },
    {
      id: 'cs4',
      prompt: 'You are unsure about a private request. What do you do?',
      emoji: 'PH',
      imageKey: 'com-phone',
      options: ['Call your supervisor on the work phone', 'Guess and hope', 'Post online', 'Share the story with friends'],
      answer: 'Call your supervisor on the work phone',
      teachCorrect: 'Escalate early. Privacy and safety come first.',
      teachWrong: 'Call your supervisor when unsure.',
    },
  ],
  toolCategories: [
    {
      title: 'Identification tools',
      why: 'Badges and sign-in sheets show who is present.',
      mark: 'ID',
      prompt: 'Name badges belong to which group?',
      answer: 'Identification tools',
      options: ['Identification tools', 'Care supplies', 'Communication tools', 'Forms & records'],
    },
    {
      title: 'Care supplies',
      why: 'Gloves, first aid, and hygiene items protect people.',
      mark: 'CS',
      prompt: 'First aid kits and protective gloves belong to…',
      answer: 'Care supplies',
      options: ['Communication tools', 'Care supplies', 'Identification tools', 'Schedules'],
    },
    {
      title: 'Communication tools',
      why: 'Work phones and radios keep the team connected.',
      mark: 'CM',
      prompt: 'Work phones belong to which group?',
      answer: 'Communication tools',
      options: ['Care supplies', 'Forms & records', 'Communication tools', 'Furniture'],
    },
    {
      title: 'Forms & records',
      why: 'Clipboards, schedules, and notes keep support accurate.',
      mark: 'FR',
      prompt: 'Clipboards and schedules belong to…',
      answer: 'Forms & records',
      options: ['Forms & records', 'Care supplies', 'Identification tools', 'Break rooms'],
    },
  ],
  systemTopics: [
    {
      title: 'Welcome & intake',
      why: 'Greet people, confirm needs, and start support safely.',
      mark: 'WI',
      prompt: 'Greeting a visitor and starting a file is part of…',
      answer: 'Welcome & intake',
      options: ['Welcome & intake', 'Follow-up', 'Closing', 'Inventory'],
    },
    {
      title: 'Daily support plan',
      why: 'Schedules and task lists guide respectful care.',
      mark: 'DP',
      prompt: 'Checking today’s visits against a schedule is…',
      answer: 'Daily support plan',
      options: ['Shipping', 'Daily support plan', 'Payroll only', 'Marketing'],
    },
    {
      title: 'Privacy & dignity',
      why: 'Keep personal information confidential and respectful.',
      mark: 'PD',
      prompt: 'Covering private notes belongs to…',
      answer: 'Privacy & dignity',
      options: ['Privacy & dignity', 'Public posting', 'Guesswork', 'Speed contests'],
    },
    {
      title: 'Escalation & reporting',
      why: 'Call a supervisor when risk or uncertainty appears.',
      mark: 'ER',
      prompt: 'Calling a supervisor about a safety concern is…',
      answer: 'Escalation & reporting',
      options: ['Escalation & reporting', 'Ignoring risk', 'Social media', 'Leaving early'],
    },
    {
      title: 'Follow-up',
      why: 'Confirm people received the help they needed.',
      mark: 'FU',
      prompt: 'Checking in after a visit supports…',
      answer: 'Follow-up',
      options: ['Follow-up', 'Ignoring outcomes', 'Deleting notes', 'Skipping the schedule'],
    },
  ],
  observationScenarios: [
    {
      id: 'badge-ready',
      title: 'Ready at the welcome desk',
      situation: 'Your supervisor asks you to open the welcome desk ready for visitors.',
      skill: 'Welcome readiness',
      steps: [
        { id: 'badge', label: 'Name badge on and visible', correctOrder: 1 },
        { id: 'desk', label: 'Welcome desk tidy and stocked', correctOrder: 2 },
        { id: 'phone', label: 'Work phone charged and nearby', correctOrder: 3 },
        { id: 'open', label: 'Signal that you are ready to greet people', correctOrder: 4 },
      ],
      passNote: 'Competent welcome is prepared before the first visitor arrives.',
    },
    {
      id: 'privacy-notes',
      title: 'Protect private notes',
      situation: 'Your supervisor watches you handle a clipboard with personal information.',
      skill: 'Privacy',
      steps: [
        { id: 'cover', label: 'Keep private pages covered from public view', correctOrder: 1 },
        { id: 'write', label: 'Write only what is needed', correctOrder: 2 },
        { id: 'store', label: 'Return the clipboard to the secure place', correctOrder: 3 },
        { id: 'confirm', label: 'Confirm with the supervisor that notes are secure', correctOrder: 4 },
      ],
      passNote: 'Dignity means private information stays private.',
    },
    {
      id: 'gloves-task',
      title: 'Protective gloves before the task',
      situation: 'Your supervisor asks you to prepare for a cleaning support task.',
      skill: 'Protective gloves',
      steps: [
        { id: 'wash', label: 'Clean your hands as trained', correctOrder: 1 },
        { id: 'gloves', label: 'Put on protective gloves', correctOrder: 2 },
        { id: 'task', label: 'Complete the cleaning task carefully', correctOrder: 3 },
        { id: 'dispose', label: 'Remove and dispose of gloves as trained', correctOrder: 4 },
      ],
      passNote: 'Gloves protect both you and the person you support.',
    },
    {
      id: 'escalate',
      title: 'Escalate when unsure',
      situation: 'A visitor asks for something outside your role.',
      skill: 'Escalation',
      steps: [
        { id: 'listen', label: 'Listen respectfully without promising what you cannot do', correctOrder: 1 },
        { id: 'explain', label: 'Explain that you will check with a supervisor', correctOrder: 2 },
        { id: 'call', label: 'Call the supervisor on the work phone', correctOrder: 3 },
        { id: 'follow', label: 'Follow the supervisor’s direction and update the visitor', correctOrder: 4 },
      ],
      passNote: 'Competent support means knowing when to ask for help.',
    },
  ],
  siteDecisions: [
    {
      id: 'lost-visitor',
      title: 'Lost visitor',
      scene: 'A visitor looks confused near the entrance.',
      prompt: 'What should you do first?',
      options: [
        'Greet them and ask how you can help',
        'Ignore them',
        'Ask for their passwords',
        'Tell them to leave',
      ],
      answer: 'Greet them and ask how you can help',
      teachCorrect: 'A calm welcome reduces stress and keeps people safe.',
      teachWrong: 'Start with a respectful greeting.',
    },
    {
      id: 'private-ask',
      title: 'Private request',
      scene: 'Someone asks you to share another person’s private details.',
      prompt: 'Best action?',
      options: [
        'Refuse politely and follow privacy rules / ask a supervisor if unsure',
        'Share the details quietly',
        'Post the story online',
        'Trade information for a favor',
      ],
      answer: 'Refuse politely and follow privacy rules / ask a supervisor if unsure',
      teachCorrect: 'Privacy is non-negotiable.',
      teachWrong: 'Do not share private details.',
    },
    {
      id: 'schedule-conflict',
      title: 'Schedule conflict',
      scene: 'Two visits appear at the same time on your schedule.',
      prompt: 'What should you do?',
      options: [
        'Call your supervisor and confirm the correct plan',
        'Pick one at random',
        'Skip both',
        'Arrive late without notice',
      ],
      answer: 'Call your supervisor and confirm the correct plan',
      teachCorrect: 'Escalate schedule conflicts early.',
      teachWrong: 'Confirm with a supervisor before changing the plan.',
    },
    {
      id: 'first-aid',
      title: 'Small injury',
      scene: 'A coworker has a small cut and asks for help.',
      prompt: 'Best first move?',
      options: [
        'Get the first aid kit and follow trained steps / get a supervisor if needed',
        'Ignore it',
        'Use random supplies from a desk',
        'Film the injury',
      ],
      answer: 'Get the first aid kit and follow trained steps / get a supervisor if needed',
      teachCorrect: 'Use the kit and escalate when needed.',
      teachWrong: 'First aid kit + trained steps.',
    },
  ],
  finalQuiz: [
    {
      id: 'cf1',
      prompt: 'Which item shows your name and role?',
      emoji: 'NB',
      imageKey: 'com-badge',
      options: ['Name badge', 'First aid kit', 'Clipboard', 'Schedule'],
      answer: 'Name badge',
      teachCorrect: 'The name badge shows who you are.',
      teachWrong: 'Wear a name badge.',
    },
    {
      id: 'cf2',
      prompt: 'Before cleaning support tasks, put on…',
      emoji: 'GL',
      imageKey: 'com-gloves',
      options: ['Protective gloves', 'No gloves', 'A visitor badge only', 'Headphones'],
      answer: 'Protective gloves',
      teachCorrect: 'Protective gloves before the task.',
      teachWrong: 'Gloves on first.',
    },
    {
      id: 'cf3',
      prompt: 'Greeting visitors and starting support is part of…',
      emoji: 'WI',
      options: ['Welcome & intake', 'Shipping', 'Inventory', 'Payroll only'],
      answer: 'Welcome & intake',
      teachCorrect: 'Welcome & intake starts support safely.',
      teachWrong: 'Welcome & intake comes first.',
    },
    {
      id: 'cf4',
      prompt: 'If you are unsure about a private request, you should…',
      emoji: 'PH',
      options: ['Call your supervisor on the work phone', 'Guess', 'Post online', 'Share with friends'],
      answer: 'Call your supervisor on the work phone',
      teachCorrect: 'Escalate early.',
      teachWrong: 'Call your supervisor.',
    },
  ],
  employmentPrep: [
    {
      id: 'com-intro',
      prompt: 'An employer asks: “Why Purpose Academy?” Best answer?',
      options: [
        'I learned community support foundations, safety, and workplace English with instructors who checked my skills',
        'I watched a few videos once',
        'I do not need privacy training',
        'I only want a paycheck with no learning',
      ],
      answer: 'I learned community support foundations, safety, and workplace English with instructors who checked my skills',
      teachCorrect: 'Connect your training to safety, language, and verified skill.',
      teachWrong: 'Employers want proof of foundations, not shortcuts.',
    },
    {
      id: 'com-safety',
      prompt: 'Interview question: “How do you protect privacy?”',
      options: [
        'Keep notes covered, share only with approved people, ask a supervisor when unsure',
        'Talk about clients with friends',
        'Post stories online',
        'Leave files on the welcome desk overnight',
      ],
      answer: 'Keep notes covered, share only with approved people, ask a supervisor when unsure',
      teachCorrect: 'Privacy and dignity are core job skills.',
      teachWrong: 'Protect private information every time.',
    },
    {
      id: 'com-team',
      prompt: 'A partner says: “Please wait here. I will check.” This shows…',
      options: [
        'Clear communication while you confirm information',
        'That you are ignoring the person',
        'That you are ending support',
        'That privacy does not matter',
      ],
      answer: 'Clear communication while you confirm information',
      teachCorrect: 'Short, calm phrases keep people informed.',
      teachWrong: 'Explain waits clearly.',
    },
    {
      id: 'com-learn',
      prompt: 'An employer asks how you learn new tasks. Best answer?',
      options: [
        'I listen, practise with an instructor, and ask when I am unsure',
        'I guess and hope nobody notices',
        'I refuse to learn English for the job',
        'I skip privacy rules if it slows me down',
      ],
      answer: 'I listen, practise with an instructor, and ask when I am unsure',
      teachCorrect: 'Employers hire people who learn carefully and ask good questions.',
      teachWrong: 'Show that you practise with guidance and ask when unsure.',
    },
    {
      id: 'com-schedule',
      prompt: 'A partner asks if you can start at 7:00 a.m. You should…',
      options: [
        'Give an honest answer about your availability',
        'Say yes to everything even if you cannot come',
        'Ignore the message',
        'Ask them to text your password',
      ],
      answer: 'Give an honest answer about your availability',
      teachCorrect: 'Clear, honest scheduling builds trust.',
      teachWrong: 'Be honest about when you can start work.',
    },
    {
      id: 'com-ready',
      prompt: 'You arrive for a placement walk-through. Best first move?',
      options: [
        'Bring your name badge and follow site safety rules',
        'Arrive without identification',
        'Share private stories first',
        'Skip meeting the supervisor',
      ],
      answer: 'Bring your name badge and follow site safety rules',
      teachCorrect: 'Show up ready: identified, respectful, on time.',
      teachWrong: 'Badge on and ready for the walk-through.',
    },
  ],
  unitCheckpoints: {
    3: [
      {
        id: 'uc3-c1',
        prompt: 'Which item shows your name and role?',
        emoji: 'NB',
        imageKey: 'com-badge',
        options: ['Name badge', 'Clipboard', 'Schedule', 'Work phone'],
        answer: 'Name badge',
        teachCorrect: 'Name badge shows who you are.',
        teachWrong: 'Wear a name badge.',
      },
      {
        id: 'uc3-c2',
        prompt: 'Before cleaning support tasks, put on…',
        emoji: 'GL',
        imageKey: 'com-gloves',
        options: ['Protective gloves', 'No gloves', 'A visitor sticker only', 'Headphones'],
        answer: 'Protective gloves',
        teachCorrect: 'Gloves on before the task.',
        teachWrong: 'Protective gloves first.',
      },
      {
        id: 'uc3-c3',
        prompt: 'Where do visitors usually arrive?',
        emoji: 'WD',
        imageKey: 'com-welcome',
        options: ['Welcome desk', 'Storage rack', 'Forklift bay', 'Tool crib'],
        answer: 'Welcome desk',
        teachCorrect: 'Meet people at the welcome desk.',
        teachWrong: 'Welcome desk is the arrival point.',
      },
    ],
    4: [
      {
        id: 'uc4-c1',
        prompt: '“How can I help you today?” is used to…',
        emoji: 'HP',
        options: ['Offer help politely', 'End the visit', 'Ask for money', 'Ignore the person'],
        answer: 'Offer help politely',
        teachCorrect: 'A calm offer of help opens support.',
        teachWrong: 'Offer help politely.',
      },
      {
        id: 'uc4-c2',
        prompt: '“Your information stays private” means…',
        emoji: 'PV',
        options: ['Keep personal details confidential', 'Post details publicly', 'Share with strangers', 'Sell the notes'],
        answer: 'Keep personal details confidential',
        teachCorrect: 'Privacy builds trust.',
        teachWrong: 'Keep details confidential.',
      },
    ],
    5: [
      {
        id: 'uc5-c1',
        prompt: 'Greeting visitors and starting support is…',
        emoji: 'WI',
        options: ['Welcome & intake', 'Shipping', 'Inventory', 'Framing'],
        answer: 'Welcome & intake',
        teachCorrect: 'Welcome & intake starts the support path.',
        teachWrong: 'Welcome & intake comes first.',
      },
      {
        id: 'uc5-c2',
        prompt: 'Calling a supervisor about a safety concern is…',
        emoji: 'ER',
        options: ['Escalation & reporting', 'Ignoring risk', 'Social media', 'Skipping work'],
        answer: 'Escalation & reporting',
        teachCorrect: 'Escalate early when unsure or unsafe.',
        teachWrong: 'Escalation & reporting keeps people safe.',
      },
    ],
  },
}
