/**
 * Purpose Academy Daily Conversation Vocabulary — words 1–200.
 * Shared across Construction, Logistics, and Community Support streams.
 * Exact worksheet translations (Amharic, Tigrinya, Arabic, Spanish, Hindi — no French)
 * and example sentences from Daily Conversation Vocabulary (pages 1–10).
 * Images: public/media/daily-conversation-vv/dc-vv-NNN.jpg
 * Generated from worksheet pages + gloss-overrides.json — do not hand-edit bulk rows.
 */
import type { VocabTerm } from '../../student/journeyCurriculum'
import { gloss } from '../packHelpers'

export const DAILY_CONVERSATION_VOCAB_200: VocabTerm[] = [
  {
    id: 'hi-001',
    english: 'Hi',
    emoji: 'HI',
    imageKey: 'dc-vv-001',
    definition: 'A friendly short greeting you say when you see someone.',
    sentence: 'Hi, I\'m Sara.',
    gloss: gloss('Hola', 'مرحبًا', 'नमस्ते', 'ሰላም', 'ሰላም'),
  },
  {
    id: 'hello-002',
    english: 'Hello',
    emoji: 'HE',
    imageKey: 'dc-vv-002',
    definition: 'A clear greeting used when you meet or answer someone.',
    sentence: 'Hello, everyone.',
    gloss: gloss('Hola', 'أهلاً', 'हैलो', 'ሰላም / ሄሎ', 'ሰላም / ሄሎ'),
  },
  {
    id: 'hey-003',
    english: 'Hey',
    emoji: 'HE',
    imageKey: 'dc-vv-003',
    definition: 'An informal greeting used with friends or to get attention.',
    sentence: 'Hey! Over here!',
    gloss: gloss('Oye / Hola', 'هاي', 'अरे / हे', 'ሄይ', 'ሄይ'),
  },
  {
    id: 'good-morning-004',
    english: 'Good morning',
    emoji: 'GM',
    imageKey: 'dc-vv-004',
    definition: 'A greeting used in the morning.',
    sentence: 'Good morning, boss.',
    gloss: gloss('Buenos días', 'صباح الخير', 'सुप्रभात', 'እንደምን አደርክ', 'ከመይ ሓዲርካ'),
  },
  {
    id: 'good-afternoon-005',
    english: 'Good afternoon',
    emoji: 'GA',
    imageKey: 'dc-vv-005',
    definition: 'A greeting used after midday.',
    sentence: 'Good afternoon, class.',
    gloss: gloss('Buenas tardes', 'مساء الخير', 'नमस्कार (दोपहर)', 'እንደምን ዋልክ', 'ከመይ ውዒልካ'),
  },
  {
    id: 'good-evening-006',
    english: 'Good evening',
    emoji: 'GE',
    imageKey: 'dc-vv-006',
    definition: 'A greeting used in the evening.',
    sentence: 'Good evening. Come in.',
    gloss: gloss('Buenas noches', 'مساء الخير', 'शुभ संध्या', 'እንደምን አመሸህ', 'ከመይ ኣምሲካ'),
  },
  {
    id: 'how-are-you-007',
    english: 'How are you?',
    emoji: 'HA',
    imageKey: 'dc-vv-007',
    definition: 'A polite question asking about someone\'s feelings or day.',
    sentence: 'Hi Tom, how are you?',
    gloss: gloss('¿Cómo estás?', 'كيف حالك؟', 'आप कैसे हैं?', 'እንዴት ነህ?', 'ከመይ ኣለካ?'),
  },
  {
    id: 'how-s-it-going-008',
    english: 'How\'s it going?',
    emoji: 'HS',
    imageKey: 'dc-vv-008',
    definition: 'An informal question asking how someone is doing.',
    sentence: 'Hey, how\'s it going?',
    gloss: gloss('¿Qué tal?', 'كيف الأمور؟', 'कैसा चल रहा है?', 'እንዴት ነው?', 'ከመይ ኣሎ?'),
  },
  {
    id: 'what-s-up-009',
    english: 'What\'s up?',
    emoji: 'WS',
    imageKey: 'dc-vv-009',
    definition: 'A casual question asking what is happening.',
    sentence: 'What\'s up, man?',
    gloss: gloss('¿Qué onda?', 'ما الأخبار؟', 'क्या चल रहा है?', 'ምን አዲስ ነገር?', 'እንታይ ሓድሽ?'),
  },
  {
    id: 'i-m-good-010',
    english: 'I\'m good',
    emoji: 'IM',
    imageKey: 'dc-vv-010',
    definition: 'A short reply that you are fine.',
    sentence: 'I\'m good, thanks.',
    gloss: gloss('Estoy bien', 'أنا بخير', 'मैं ठीक हूँ', 'ደህና ነኝ', 'ደሓን እየ'),
  },
  {
    id: 'not-bad-011',
    english: 'Not bad',
    emoji: 'NB',
    imageKey: 'dc-vv-011',
    definition: 'A reply that things are okay — not perfect, not terrible.',
    sentence: 'Not bad. And you?',
    gloss: gloss('No está mal', 'ليس سيئًا', 'बुरा नहीं', 'መጥፎ አይደለም', 'ሕማቅ ኣይኮነን'),
  },
  {
    id: 'pretty-good-012',
    english: 'Pretty good',
    emoji: 'PG',
    imageKey: 'dc-vv-012',
    definition: 'A reply that things are going well.',
    sentence: 'I\'m pretty good today.',
    gloss: gloss('Bastante bien', 'جيد جدًا', 'काफ़ी अच्छा', 'በጣም ጥሩ', 'ብጣዕሚ ጽቡቕ'),
  },
  {
    id: 'how-about-you-013',
    english: 'How about you?',
    emoji: 'HA',
    imageKey: 'dc-vv-013',
    definition: 'A follow-up question that turns the question back to the other person.',
    sentence: 'I\'m fine. How about you?',
    gloss: gloss('¿Y tú?', 'وأنت؟', 'और आप?', 'አንተስ?', 'ንስካከ?'),
  },
  {
    id: 'nice-to-meet-you-014',
    english: 'Nice to meet you',
    emoji: 'NT',
    imageKey: 'dc-vv-014',
    definition: 'A polite phrase when you meet someone for the first time.',
    sentence: 'Nice to meet you, Ali.',
    gloss: gloss('Mucho gusto', 'تشرفت بمعرفتك', 'मिलकर अच्छा लगा', 'ስለተዋወቅን ደስ ብሎኛል', 'ብምልላይና ተሓጉሰ'),
  },
  {
    id: 'what-s-your-name-015',
    english: 'What\'s your name?',
    emoji: 'WS',
    imageKey: 'dc-vv-015',
    definition: 'A question asking for someone\'s name.',
    sentence: 'Hi! What\'s your name?',
    gloss: gloss('¿Cómo te llamas?', 'ما اسمك؟', 'आपका नाम क्या है?', 'ስምህ ማን ነው?', 'ስምካ መን እዩ?'),
  },
  {
    id: 'my-name-is-016',
    english: 'My name is...',
    emoji: 'MN',
    imageKey: 'dc-vv-016',
    definition: 'A phrase used to tell someone your name.',
    sentence: 'My name is Daniel.',
    gloss: gloss('Me llamo...', '...اسمي', 'मेरा नाम ... है', 'ስሜ ... ነው', 'ስመይ ... እዩ'),
  },
  {
    id: 'where-are-you-from-017',
    english: 'Where are you from?',
    emoji: 'WA',
    imageKey: 'dc-vv-017',
    definition: 'A question asking about someone\'s home country or city.',
    sentence: 'Where are you from, Maria?',
    gloss: gloss('¿De dónde eres?', 'من أين أنت؟', 'आप कहाँ से हैं?', 'ከየት ነህ?', 'ካበይ ኢካ?'),
  },
  {
    id: 'i-m-from-018',
    english: 'I\'m from...',
    emoji: 'IM',
    imageKey: 'dc-vv-018',
    definition: 'A phrase used to say your home country or city.',
    sentence: 'I\'m from Canada.',
    gloss: gloss('Soy de...', 'أنا من...', 'मैं ... से हूँ', 'ከ... ነኝ', 'ካብ ... እየ'),
  },
  {
    id: 'long-time-no-see-019',
    english: 'Long time no see',
    emoji: 'LT',
    imageKey: 'dc-vv-019',
    definition: 'A friendly phrase when you meet someone after a long time.',
    sentence: 'Long time no see, friend!',
    gloss: gloss('¡Cuánto tiempo!', 'لم أرك منذ زمن', 'बहुत दिनों बाद मिले', 'ከተያየን ቆየን', 'ካብ እንራኣኣ ነዊሕ ኮይኑ.'),
  },
  {
    id: 'welcome-020',
    english: 'Welcome',
    emoji: 'WE',
    imageKey: 'dc-vv-020',
    definition: 'A warm phrase used when someone arrives.',
    sentence: 'Welcome to our school.',
    gloss: gloss('Bienvenido', 'أهلاً وسهلاً', 'स्वागत है', 'እንኻን ደህና መጣህ', 'እንቋዕ ብደሓን መጻእካ'),
  },
  {
    id: 'please-021',
    english: 'Please',
    emoji: 'PL',
    imageKey: 'dc-vv-021',
    definition: 'A polite word used when you ask for something.',
    sentence: 'Please sit down.',
    gloss: gloss('Por favor', 'من فضلك', 'कृपया', 'እባክህ', 'በጃካ'),
  },
  {
    id: 'thank-you-022',
    english: 'Thank you',
    emoji: 'TY',
    imageKey: 'dc-vv-022',
    definition: 'A polite phrase used to show gratitude.',
    sentence: 'Thank you for your help.',
    gloss: gloss('Gracias', 'شكراً لك', 'धन्यवाद', 'አመሰግናለሁ', 'የቐንየለይ'),
  },
  {
    id: 'thanks-023',
    english: 'Thanks',
    emoji: 'TH',
    imageKey: 'dc-vv-023',
    definition: 'A short, friendly way to say thank you.',
    sentence: 'Thanks, see you tomorrow.',
    gloss: gloss('Gracias', 'شكراً', 'शुक्रिया', 'አመሰግናለሁ', 'የቐንየለይ'),
  },
  {
    id: 'thanks-a-lot-024',
    english: 'Thanks a lot',
    emoji: 'TA',
    imageKey: 'dc-vv-024',
    definition: 'A stronger thank-you for bigger help.',
    sentence: 'Thanks a lot for the ride.',
    gloss: gloss('Muchas gracias', 'شُكْرًا جَزِيلًا', 'बहुत धन्यवाद', 'በጣም አመሰግናለሁ', 'ብዙሕ የቐንየለይ'),
  },
  {
    id: 'you-re-welcome-025',
    english: 'You\'re welcome',
    emoji: 'YR',
    imageKey: 'dc-vv-025',
    definition: 'A polite reply after someone thanks you.',
    sentence: 'Thanks! You\'re welcome.',
    gloss: gloss('De nada', 'عَفْوًا', 'आपका स्वागत है', 'ምንም አይደለም', 'ገለ አይኮነን'),
  },
  {
    id: 'no-problem-026',
    english: 'No problem',
    emoji: 'NP',
    imageKey: 'dc-vv-026',
    definition: 'A friendly reply that the request or thanks is easy.',
    sentence: 'No problem, I can help.',
    gloss: gloss('No hay problema', 'لا مشكلة', 'कोई बात नहीं', 'ችግር የለም', 'ጸገም የለን'),
  },
  {
    id: 'excuse-me-027',
    english: 'Excuse me',
    emoji: 'EM',
    imageKey: 'dc-vv-027',
    definition: 'A polite phrase to get attention or pass by someone.',
    sentence: 'Excuse me, where is the bus?',
    gloss: gloss('Disculpe', 'عفوًا / المعذرة', 'माफ़ कीजिए', 'ይቅርታ', 'ይቅሬታ'),
  },
  {
    id: 'sorry-028',
    english: 'Sorry',
    emoji: 'SO',
    imageKey: 'dc-vv-028',
    definition: 'A short apology when you make a small mistake.',
    sentence: 'Sorry, I\'m late.',
    gloss: gloss('Perdón', 'آسف', 'सॉरी', 'ይቅርታ', 'ይቅሬታ'),
  },
  {
    id: 'i-m-sorry-029',
    english: 'I\'m sorry',
    emoji: 'IM',
    imageKey: 'dc-vv-029',
    definition: 'A fuller apology when you want to show regret.',
    sentence: 'I\'m sorry, I forgot.',
    gloss: gloss('Lo siento', 'أنا آسف', 'मुझे खेद है', 'አዝናለሁ', 'ይቅሬታ ግበረለይ'),
  },
  {
    id: 'that-s-okay-030',
    english: 'That\'s okay',
    emoji: 'TS',
    imageKey: 'dc-vv-030',
    definition: 'A reply that forgives a small problem.',
    sentence: 'That\'s okay, don\'t worry.',
    gloss: gloss('Está bien', 'لا بأس', 'कोई बात नहीं', 'ምንም አይደለም', 'ደሓን እዩ'),
  },
  {
    id: 'don-t-worry-031',
    english: 'Don\'t worry',
    emoji: 'DT',
    imageKey: 'dc-vv-031',
    definition: 'A calming phrase telling someone not to feel stressed.',
    sentence: 'Don\'t worry, it\'s fine.',
    gloss: gloss('No te preocupes', 'لا تقلق', 'चिंता मत करो', 'አትጨነቅ', 'ኣይትሻቐል'),
  },
  {
    id: 'after-you-032',
    english: 'After you',
    emoji: 'AY',
    imageKey: 'dc-vv-032',
    definition: 'A polite phrase letting someone go first.',
    sentence: 'Please, after you.',
    gloss: gloss('Usted primero', 'تفضل أولاً', 'पहले आप', 'አንተ ቅደም', 'ንስካ ቅደም'),
  },
  {
    id: 'go-ahead-033',
    english: 'Go ahead',
    emoji: 'GA',
    imageKey: 'dc-vv-033',
    definition: 'Permission for someone to speak or act first.',
    sentence: 'Go ahead and ask.',
    gloss: gloss('Adelante', 'تفضل', 'आगे बढ़िए', 'ቀጥል', 'ቀጽል'),
  },
  {
    id: 'may-i-034',
    english: 'May I...?',
    emoji: 'MI',
    imageKey: 'dc-vv-034',
    definition: 'A polite way to ask for permission.',
    sentence: 'May I come in?',
    gloss: gloss('¿Puedo...?', 'هل يمكنني...?', 'क्या मैं...?', 'ይቻላል...?', 'ይክእል ድዩ...?'),
  },
  {
    id: 'could-you-035',
    english: 'Could you...?',
    emoji: 'CY',
    imageKey: 'dc-vv-035',
    definition: 'A polite way to ask someone to do something.',
    sentence: 'Could you help me?',
    gloss: gloss('¿Podría...?', 'هل يمكنك...؟', 'क्या आप...?', 'ትችላለህ...?', 'ትኽእል ዶ...?'),
  },
  {
    id: 'would-you-mind-036',
    english: 'Would you mind...?',
    emoji: 'WY',
    imageKey: 'dc-vv-036',
    definition: 'A very polite request asking if an action is okay.',
    sentence: 'Would you mind closing the door?',
    gloss: gloss('¿Le importaría...?', 'هل تمانع...؟', 'बुरा न मानें तो...?', 'ቅር ካላለህ...?', 'ዘይጽገመካ...?'),
  },
  {
    id: 'i-appreciate-it-037',
    english: 'I appreciate it',
    emoji: 'IA',
    imageKey: 'dc-vv-037',
    definition: 'A warm way to show thanks for help.',
    sentence: 'Thank you. I appreciate it.',
    gloss: gloss('Lo agradezco', 'أقدّر ذلك', 'मैं आभारी हूँ', 'በጣም አደንቃለሁ', 'የመስግነካ'),
  },
  {
    id: 'of-course-038',
    english: 'Of course',
    emoji: 'OC',
    imageKey: 'dc-vv-038',
    definition: 'A clear yes — you are happy to agree.',
    sentence: 'Of course I can help.',
    gloss: gloss('Claro', 'بالطبع', 'बिल्कुल', 'በእርግጥ', 'ብርግጽ'),
  },
  {
    id: 'sure-039',
    english: 'Sure',
    emoji: 'SU',
    imageKey: 'dc-vv-039',
    definition: 'An informal yes.',
    sentence: 'Sure, no problem.',
    gloss: gloss('Seguro', 'أكيد', 'ज़रूर', 'እሺ', 'ሕራይ'),
  },
  {
    id: 'no-thank-you-040',
    english: 'No, thank you',
    emoji: 'NT',
    imageKey: 'dc-vv-040',
    definition: 'A polite way to refuse an offer.',
    sentence: 'No, thank you. I\'m full.',
    gloss: gloss('No, gracias', 'لا، شكراً', 'नहीं, धन्यवाद', 'አይ፣ አመሰግናለሁ', 'አይፋል፣ የቐንየለይ'),
  },
  {
    id: 'yes-041',
    english: 'Yes',
    emoji: 'YE',
    imageKey: 'dc-vv-041',
    definition: 'A word that agrees or accepts.',
    sentence: 'Yes, I understand.',
    gloss: gloss('Sí', 'نعم', 'हाँ', 'አዎ', 'እወ'),
  },
  {
    id: 'no-042',
    english: 'No',
    emoji: 'NO',
    imageKey: 'dc-vv-042',
    definition: 'A word that refuses or disagrees.',
    sentence: 'No, I don\'t.',
    gloss: gloss('No', 'لا', 'नहीं', 'አይ', 'አይፋል'),
  },
  {
    id: 'maybe-043',
    english: 'Maybe',
    emoji: 'MA',
    imageKey: 'dc-vv-043',
    definition: 'A word that means you are not sure yet.',
    sentence: 'Maybe tomorrow.',
    gloss: gloss('Tal vez', 'ربما', 'शायद', 'ምናልባት', 'ምናልባት'),
  },
  {
    id: 'i-don-t-understand-044',
    english: 'I don\'t understand',
    emoji: 'ID',
    imageKey: 'dc-vv-044',
    definition: 'A phrase used when meaning is unclear.',
    sentence: 'Sorry, I don\'t understand.',
    gloss: gloss('No entiendo', 'لا أفهم', 'मुझे समझ नहीं आया', 'አልገባኝም', 'ኣይተረዳኣንን'),
  },
  {
    id: 'please-repeat-045',
    english: 'Please repeat',
    emoji: 'PR',
    imageKey: 'dc-vv-045',
    definition: 'A polite request to hear something again.',
    sentence: 'Please repeat that.',
    gloss: gloss('Repita, por favor', 'أعد من فضلك', 'कृपया दोहराइए', 'እባክህ ድገመው', 'በጃካ ድገሞ'),
  },
  {
    id: 'speak-slowly-046',
    english: 'Speak slowly',
    emoji: 'SS',
    imageKey: 'dc-vv-046',
    definition: 'A request for clearer, slower speech.',
    sentence: 'Please speak slowly.',
    gloss: gloss('Hable despacio', 'تكلم ببطء', 'धीरे बोलिए', 'ቀስ ብለህ ተናገር', 'ቀስ ኢልካ ተዛረብ'),
  },
  {
    id: 'what-does-it-mean-047',
    english: 'What does it mean?',
    emoji: 'WD',
    imageKey: 'dc-vv-047',
    definition: 'A question asking for the meaning of a word.',
    sentence: 'What does "shift" mean?',
    gloss: gloss('¿Qué significa?', 'ماذا يعني؟', 'इसका मतलब क्या है?', 'ትርጉሙ ምንድን ነው?', 'ትርጉሙ እንታይ እዩ?'),
  },
  {
    id: 'i-need-048',
    english: 'I need',
    emoji: 'IN',
    imageKey: 'dc-vv-048',
    definition: 'A phrase used when something is necessary.',
    sentence: 'I need a pen.',
    gloss: gloss('Necesito', 'أحتاج', 'मुझे चाहिए', 'ያስፈልገኛል', 'የድልየኒ'),
  },
  {
    id: 'i-want-049',
    english: 'I want',
    emoji: 'IW',
    imageKey: 'dc-vv-049',
    definition: 'A phrase used when you desire something.',
    sentence: 'I want some coffee.',
    gloss: gloss('Quiero', 'أريد', 'मैं चाहता हूँ', 'እፈልጋለሁ', 'ደልየ'),
  },
  {
    id: 'i-would-like-050',
    english: 'I would like',
    emoji: 'IW',
    imageKey: 'dc-vv-050',
    definition: 'A polite way to ask for something.',
    sentence: 'I would like water, please.',
    gloss: gloss('Me gustaría', 'أودُّ', 'मैं चाहूँगा', 'ብፈልግ ደስ ይለኛል', 'ምደለኽ'),
  },
  {
    id: 'how-much-051',
    english: 'How much?',
    emoji: 'HM',
    imageKey: 'dc-vv-051',
    definition: 'A question asking the price or amount.',
    sentence: 'How much is this?',
    gloss: gloss('¿Cuánto cuesta?', 'بكم ؟', 'कितने का है?', 'ስንት ነው?', 'ክንደይ እዩ?'),
  },
  {
    id: 'where-052',
    english: 'Where?',
    emoji: 'WH',
    imageKey: 'dc-vv-052',
    definition: 'A question asking about place or location.',
    sentence: 'Where is the bathroom?',
    gloss: gloss('¿Dónde?', 'أين؟', 'कहाँ?', 'የት?', 'ኣበይ?'),
  },
  {
    id: 'when-053',
    english: 'When?',
    emoji: 'WH',
    imageKey: 'dc-vv-053',
    definition: 'A question asking about time.',
    sentence: 'When does class start?',
    gloss: gloss('¿Cuándo?', 'متى؟', 'कब?', 'መቼ?', 'መዓስ?'),
  },
  {
    id: 'today-054',
    english: 'Today',
    emoji: 'TO',
    imageKey: 'dc-vv-054',
    definition: 'This day — the day happening now.',
    sentence: 'I work today.',
    gloss: gloss('Hoy', 'اليوم', 'आज', 'ዛሬ', 'ሎሚ'),
  },
  {
    id: 'tomorrow-055',
    english: 'Tomorrow',
    emoji: 'TO',
    imageKey: 'dc-vv-055',
    definition: 'The day after today.',
    sentence: 'See you tomorrow.',
    gloss: gloss('Mañana', 'غَدًا', 'कल (आने वाला)', 'ነገ', 'ጽባሕ'),
  },
  {
    id: 'yesterday-056',
    english: 'Yesterday',
    emoji: 'YE',
    imageKey: 'dc-vv-056',
    definition: 'The day before today.',
    sentence: 'I was sick yesterday.',
    gloss: gloss('Ayer', 'أمس', 'कल (बीता हुआ)', 'ትናንት', 'ትማሊ'),
  },
  {
    id: 'now-057',
    english: 'Now',
    emoji: 'NO',
    imageKey: 'dc-vv-057',
    definition: 'At this moment.',
    sentence: 'Come now, please.',
    gloss: gloss('Ahora', 'الآن', 'अभी', 'አሁን', 'ሕጂ'),
  },
  {
    id: 'later-058',
    english: 'Later',
    emoji: 'LA',
    imageKey: 'dc-vv-058',
    definition: 'At a time after now.',
    sentence: 'I\'ll call you later.',
    gloss: gloss('Más tarde', 'لاحقًا', 'बाद में', 'በክዋላ', 'ደሓር'),
  },
  {
    id: 'busy-059',
    english: 'Busy',
    emoji: 'BU',
    imageKey: 'dc-vv-059',
    definition: 'Having a lot to do; not free right now.',
    sentence: 'Sorry, I\'m busy now.',
    gloss: gloss('Ocupado', 'مشغول', 'व्यस्त', 'ሥራ ይዛለሁ', 'ስራሕ ሒዘ'),
  },
  {
    id: 'hungry-060',
    english: 'Hungry',
    emoji: 'HU',
    imageKey: 'dc-vv-060',
    definition: 'Needing or wanting food.',
    sentence: 'I\'m hungry. Let\'s eat.',
    gloss: gloss('Tengo hambre', 'جائع', 'भूख लगी है', 'ርቦኛል', 'ጠምየ'),
  },
  {
    id: 'tired-061',
    english: 'Tired',
    emoji: 'TI',
    imageKey: 'dc-vv-061',
    definition: 'Needing rest after work or activity.',
    sentence: 'I\'m tired after work.',
    gloss: gloss('Cansado', 'متعب', 'थका हुआ', 'ደክሞኛል', 'ደኽመ'),
  },
  {
    id: 'see-you-later-062',
    english: 'See you later',
    emoji: 'SY',
    imageKey: 'dc-vv-062',
    definition: 'A friendly goodbye when you will meet again later.',
    sentence: 'Bye! See you later.',
    gloss: gloss('Hasta luego', 'أراك لاحقًا', 'बाद में मिलते हैं', 'በክዋለ እንገናኝ', 'ደሓር ንራከብ'),
  },
  {
    id: 'take-care-063',
    english: 'Take care',
    emoji: 'TC',
    imageKey: 'dc-vv-063',
    definition: 'A warm goodbye wishing someone safety and well-being.',
    sentence: 'Goodbye, take care.',
    gloss: gloss('Cuídate', 'اعتن بنفسك', 'अपना ध्यान रखना', 'ራስህን ጠብቅ', 'ተከናከን'),
  },
  {
    id: 'good-night-064',
    english: 'Good night',
    emoji: 'GN',
    imageKey: 'dc-vv-064',
    definition: 'A goodbye used at night before sleep.',
    sentence: 'Good night, sleep well.',
    gloss: gloss('Buenas noches', 'تصبح على خير', 'शुभ रात्रि', 'ደህና እደር', 'ብሰላም ሕደር'),
  },
  {
    id: 'have-a-good-day-065',
    english: 'Have a good day',
    emoji: 'HA',
    imageKey: 'dc-vv-065',
    definition: 'A friendly wish for someone\'s day.',
    sentence: 'Thanks! Have a good day.',
    gloss: gloss('Que tengas buen día', 'يومًا سعيدًا', 'आपका दिन अच्छा हो', 'መልካም ቀን', 'ጽቡቕ መዓልቲ'),
  },
  {
    id: 'goodbye-066',
    english: 'Goodbye',
    emoji: 'GO',
    imageKey: 'dc-vv-066',
    definition: 'A standard phrase used when leaving.',
    sentence: 'Goodbye, see you Monday.',
    gloss: gloss('Adiós', 'مع السلامة', 'अलविया', 'ቻው / ደህና ሁን', 'ቻው / ብሰላም'),
  },
  {
    id: 'see-you-soon-067',
    english: 'See you soon',
    emoji: 'SY',
    imageKey: 'dc-vv-067',
    definition: 'A goodbye when you expect to meet again soon.',
    sentence: 'See you soon, friend.',
    gloss: gloss('Hasta pronto', 'أراك قريبًا', 'जल्द मिलेंगे', 'በቅርቡ እንገናኝ', 'ቀልጢፍና ንራከብ'),
  },
  {
    id: 'take-a-break-068',
    english: 'Take a break',
    emoji: 'TA',
    imageKey: 'dc-vv-068',
    definition: 'Stop working for a short rest.',
    sentence: 'Let\'s take a break.',
    gloss: gloss('Toma un descanso', 'خذ استراحة', 'थोड़ा आराम करो', 'እረፍት ውሰድ', 'ዕረፍቲ ውሰድ'),
  },
  {
    id: 'let-s-go-069',
    english: 'Let\'s go',
    emoji: 'LS',
    imageKey: 'dc-vv-069',
    definition: 'An invitation to leave or start moving together.',
    sentence: 'Let\'s go to lunch.',
    gloss: gloss('Vamos', 'هيا بنا', 'चलो', 'እንሂድ', 'ንኽድ'),
  },
  {
    id: 'come-here-070',
    english: 'Come here',
    emoji: 'CH',
    imageKey: 'dc-vv-070',
    definition: 'A request for someone to move toward you.',
    sentence: 'Come here, please.',
    gloss: gloss('Ven aquí', 'تعال هنا', 'यहाँ आओ', 'ወደዚህ ና', 'ናብዚ ንዓ'),
  },
  {
    id: 'wait-071',
    english: 'Wait',
    emoji: 'WA',
    imageKey: 'dc-vv-071',
    definition: 'Stay in place for a short time.',
    sentence: 'Wait for me!',
    gloss: gloss('Espera', 'انتظر', 'रुको', 'ቆይ', 'ጽናሕ'),
  },
  {
    id: 'stop-072',
    english: 'Stop',
    emoji: 'ST',
    imageKey: 'dc-vv-072',
    definition: 'Do not continue; halt an action.',
    sentence: 'Stop! A car is coming.',
    gloss: gloss('Alto / Para', 'قف', 'रुकिए', 'ቁም', 'ደው በል'),
  },
  {
    id: 'look-073',
    english: 'Look',
    emoji: 'LO',
    imageKey: 'dc-vv-073',
    definition: 'Use your eyes to notice something.',
    sentence: 'Look at the board.',
    gloss: gloss('Mira', 'انظر', 'देखो', 'ተመልከት', 'ርአ'),
  },
  {
    id: 'listen-074',
    english: 'Listen',
    emoji: 'LI',
    imageKey: 'dc-vv-074',
    definition: 'Use your ears to hear carefully.',
    sentence: 'Listen to the teacher.',
    gloss: gloss('Escucha', 'استمع', 'सुनो', 'አዳምጥ', 'ስማዕ'),
  },
  {
    id: 'read-075',
    english: 'Read',
    emoji: 'RE',
    imageKey: 'dc-vv-075',
    definition: 'Look at words and understand them.',
    sentence: 'Read page five.',
    gloss: gloss('Lee', 'اقرأ', 'पढ़ो', 'አንብብ', 'አንብብ'),
  },
  {
    id: 'write-076',
    english: 'Write',
    emoji: 'WR',
    imageKey: 'dc-vv-076',
    definition: 'Put words on paper or a screen.',
    sentence: 'Write your name here.',
    gloss: gloss('Escribe', 'اكتب', 'लिखो', 'ጻፍ', 'ጽሓፍ'),
  },
  {
    id: 'open-077',
    english: 'Open',
    emoji: 'OP',
    imageKey: 'dc-vv-077',
    definition: 'Move something so it is not closed.',
    sentence: 'Open the door, please.',
    gloss: gloss('Abre', 'افتح', 'खोलो', 'ክፈት', 'ክፈት'),
  },
  {
    id: 'close-078',
    english: 'Close',
    emoji: 'CL',
    imageKey: 'dc-vv-078',
    definition: 'Move something so it is shut.',
    sentence: 'Close the window.',
    gloss: gloss('Cierra', 'أغلق', 'बंद करो', 'ዝጋ', 'ዕጸው'),
  },
  {
    id: 'sit-down-079',
    english: 'Sit down',
    emoji: 'SD',
    imageKey: 'dc-vv-079',
    definition: 'Take a seat.',
    sentence: 'Please sit down.',
    gloss: gloss('Siéntate', 'اجلس', 'बैठ जाइए', 'ተቀመጥ', 'ኮፍ በል'),
  },
  {
    id: 'stand-up-080',
    english: 'Stand up',
    emoji: 'SU',
    imageKey: 'dc-vv-080',
    definition: 'Rise onto your feet.',
    sentence: 'Stand up, everyone.',
    gloss: gloss('Levántate', 'قف', 'खड़े हो जाइए', 'ተነስ', 'ተንስእ'),
  },
  {
    id: 'sit-here-081',
    english: 'Sit here',
    emoji: 'SH',
    imageKey: 'dc-vv-081',
    definition: 'Take a seat in this place.',
    sentence: 'You can sit here.',
    gloss: gloss('Siéntate aquí', 'اجلس هنا', 'यहाँ बैठिए', 'እዚህ ተቀመጥ', 'ኣብዚ ኮፍ በል'),
  },
  {
    id: 'stand-here-082',
    english: 'Stand here',
    emoji: 'SH',
    imageKey: 'dc-vv-082',
    definition: 'Stay on your feet in this place.',
    sentence: 'Stand here and wait.',
    gloss: gloss('Párate aquí', 'قف هنا', 'यहाँ खड़े होइए', 'እዚህ ቁም', 'ኣብዚ ደው በል'),
  },
  {
    id: 'turn-left-083',
    english: 'Turn left',
    emoji: 'TL',
    imageKey: 'dc-vv-083',
    definition: 'Change direction toward the left.',
    sentence: 'Turn left at the light.',
    gloss: gloss('Gira a la izquierda', 'انعطف يسارًا', 'बाएँ मुड़िए', 'ወደ ግራ ታጠፍ', 'ናብ ጸጋም ተጠወ'),
  },
  {
    id: 'turn-right-084',
    english: 'Turn right',
    emoji: 'TR',
    imageKey: 'dc-vv-084',
    definition: 'Change direction toward the right.',
    sentence: 'Turn right after the bank.',
    gloss: gloss('Gira a la derecha', 'انعطف يمينًا', 'दाएँ मुड़िए', 'ወደ ቀኝ ታጠፍ', 'ናብ የማን ተጠወ'),
  },
  {
    id: 'straight-ahead-085',
    english: 'Straight ahead',
    emoji: 'SA',
    imageKey: 'dc-vv-085',
    definition: 'Keep going forward without turning.',
    sentence: 'Go straight ahead.',
    gloss: gloss('Todo recto', 'إلى الأمام مباشرة', 'सीधे आगे', 'ቀጥ ብለህ', 'ብቐጥታ'),
  },
  {
    id: 'next-086',
    english: 'Next',
    emoji: 'NE',
    imageKey: 'dc-vv-086',
    definition: 'The one that comes after this.',
    sentence: 'Next, please!',
    gloss: gloss('Siguiente', 'التالي', 'अगला', 'ቀጣይ', 'ዝቅጽል'),
  },
  {
    id: 'before-087',
    english: 'Before',
    emoji: 'BE',
    imageKey: 'dc-vv-087',
    definition: 'Earlier than something else.',
    sentence: 'Wash your hands before eating.',
    gloss: gloss('Antes', 'قبل', 'पहले', 'በፊት', 'ቅድሚ'),
  },
  {
    id: 'after-088',
    english: 'After',
    emoji: 'AF',
    imageKey: 'dc-vv-088',
    definition: 'Later than something else.',
    sentence: 'We rest after lunch.',
    gloss: gloss('Después', 'بعد', 'बाद में', 'በክዋላ', 'ድሕሪ'),
  },
  {
    id: 'first-089',
    english: 'First',
    emoji: 'FI',
    imageKey: 'dc-vv-089',
    definition: 'Number one in order.',
    sentence: 'First, read the question.',
    gloss: gloss('Primero', 'أولًا', 'पहला', 'መጀመሪያ', 'ቀዳማይ'),
  },
  {
    id: 'last-090',
    english: 'Last',
    emoji: 'LA',
    imageKey: 'dc-vv-090',
    definition: 'The final one in order.',
    sentence: 'This is the last one.',
    gloss: gloss('Último', 'الأخير', 'आख़िरी', 'የ መጨረሻ', 'ናይ መወዳእታ'),
  },
  {
    id: 'again-091',
    english: 'Again',
    emoji: 'AG',
    imageKey: 'dc-vv-091',
    definition: 'One more time.',
    sentence: 'Say it again, please.',
    gloss: gloss('Otra vez', 'مرة أخرى', 'फिर से', 'እንደገና', 'ደጊምካ'),
  },
  {
    id: 'together-092',
    english: 'Together',
    emoji: 'TO',
    imageKey: 'dc-vv-092',
    definition: 'With each other as a group.',
    sentence: 'Let\'s work together.',
    gloss: gloss('Juntos', 'معًا', 'साथ में', 'አብረን', 'ብሓባር'),
  },
  {
    id: 'separate-093',
    english: 'Separate',
    emoji: 'SE',
    imageKey: 'dc-vv-093',
    definition: 'Apart; not mixed or joined.',
    sentence: 'Keep them separate.',
    gloss: gloss('Separado', 'منفصل', 'अलग', 'ለየብቻ', 'ብበይኑ'),
  },
  {
    id: 'same-094',
    english: 'Same',
    emoji: 'SA',
    imageKey: 'dc-vv-094',
    definition: 'Not different; alike.',
    sentence: 'These two are the same.',
    gloss: gloss('Igual', 'نفس الشيء', 'एक जैसा', 'ተመሳሳይ', 'ሓደ ዓይነት'),
  },
  {
    id: 'different-095',
    english: 'Different',
    emoji: 'DI',
    imageKey: 'dc-vv-095',
    definition: 'Not the same.',
    sentence: 'An apple is different.',
    gloss: gloss('Diferente', 'مختلف', 'अलग', 'የተለየ', 'ዝተፈልየ'),
  },
  {
    id: 'more-096',
    english: 'More',
    emoji: 'MO',
    imageKey: 'dc-vv-096',
    definition: 'A larger amount.',
    sentence: 'Can I have more water?',
    gloss: gloss('Más', 'أكثر', 'और ज़्यादा', 'ተጨማሪ', 'ተወሳኽ'),
  },
  {
    id: 'less-097',
    english: 'Less',
    emoji: 'LE',
    imageKey: 'dc-vv-097',
    definition: 'A smaller amount.',
    sentence: 'Use less salt.',
    gloss: gloss('Menos', 'أقل', 'कम', 'ያነሰ', 'ዝውሓደ'),
  },
  {
    id: 'everything-098',
    english: 'Everything',
    emoji: 'EV',
    imageKey: 'dc-vv-098',
    definition: 'All things; the whole set.',
    sentence: 'Everything is ready.',
    gloss: gloss('Todo', 'كل شيء', 'सब कुछ', 'ሁሉም ነገር', 'ኩሉ ነገር'),
  },
  {
    id: 'nothing-099',
    english: 'Nothing',
    emoji: 'NO',
    imageKey: 'dc-vv-099',
    definition: 'Not anything; zero things.',
    sentence: 'There is nothing in the box.',
    gloss: gloss('Nada', 'لا شيء', 'कुछ नहीं', 'ምንም', 'ዋላ ሓንቲ'),
  },
  {
    id: 'enough-100',
    english: 'Enough',
    emoji: 'EN',
    imageKey: 'dc-vv-100',
    definition: 'As much as you need; no more required.',
    sentence: 'That\'s enough, thank you.',
    gloss: gloss('Suficiente', 'يكفي', 'काफ़ी है', 'በቃ', 'ይእክል'),
  },
  {
    id: 'too-much-101',
    english: 'Too much',
    emoji: 'TM',
    imageKey: 'dc-vv-101',
    definition: 'More than is needed or comfortable.',
    sentence: 'This is too much food.',
    gloss: gloss('Demasiado', 'كثير جدًّا', 'बहुत ज़्यादा', 'በጣም ብዙ', 'ብዙሕ'),
  },
  {
    id: 'too-little-102',
    english: 'Too little',
    emoji: 'TL',
    imageKey: 'dc-vv-102',
    definition: 'Less than is needed.',
    sentence: 'This is too little.',
    gloss: gloss('Muy poco', 'قليل جدًا', 'बहुत कम', 'በጣም ትንሽ', 'ቁሩብ'),
  },
  {
    id: 'big-103',
    english: 'Big',
    emoji: 'BI',
    imageKey: 'dc-vv-103',
    definition: 'Large in size.',
    sentence: 'An elephant is big.',
    gloss: gloss('Grande', 'كبير', 'बड़ा', 'ትልቅ', 'ዓቢ'),
  },
  {
    id: 'small-104',
    english: 'Small',
    emoji: 'SM',
    imageKey: 'dc-vv-104',
    definition: 'Little in size.',
    sentence: 'The kitten is small.',
    gloss: gloss('Pequeño', 'صغير', 'छोटा', 'ትንሽ', 'ንእሽቶ'),
  },
  {
    id: 'hot-105',
    english: 'Hot',
    emoji: 'HO',
    imageKey: 'dc-vv-105',
    definition: 'High temperature.',
    sentence: 'The coffee is hot.',
    gloss: gloss('Caliente', 'ساخن', 'गरम', 'ትኩስ', 'ውዑይ'),
  },
  {
    id: 'cold-106',
    english: 'Cold',
    emoji: 'CO',
    imageKey: 'dc-vv-106',
    definition: 'Low temperature.',
    sentence: 'The water is cold.',
    gloss: gloss('Frío', 'بارد', 'ठंडा', 'ቀዝቃዛ', 'ዝሑል'),
  },
  {
    id: 'happy-107',
    english: 'Happy',
    emoji: 'HA',
    imageKey: 'dc-vv-107',
    definition: 'Feeling good and glad.',
    sentence: 'I\'m happy today.',
    gloss: gloss('Feliz', 'سعيد', 'खुश', 'ደስተኛ', 'ሕጉስ'),
  },
  {
    id: 'sad-108',
    english: 'Sad',
    emoji: 'SA',
    imageKey: 'dc-vv-108',
    definition: 'Feeling unhappy.',
    sentence: 'Why are you sad?',
    gloss: gloss('Triste', 'حزين', 'उदास', 'አዝኛለሁ', 'ሕዙን'),
  },
  {
    id: 'angry-109',
    english: 'Angry',
    emoji: 'AN',
    imageKey: 'dc-vv-109',
    definition: 'Feeling mad or upset.',
    sentence: 'Don\'t be angry.',
    gloss: gloss('Enojado', 'غاضب', 'गुस्सा', 'ተናድጃለሁ', 'ሕሩቅ'),
  },
  {
    id: 'excited-110',
    english: 'Excited',
    emoji: 'EX',
    imageKey: 'dc-vv-110',
    definition: 'Feeling very happy and eager.',
    sentence: 'I\'m excited for the trip!',
    gloss: gloss('Emocionado', 'متحمس', 'उत्साहित', 'በጣም ተደስቻለሁ', 'ተሃንጥየ'),
  },
  {
    id: 'bored-111',
    english: 'Bored',
    emoji: 'BO',
    imageKey: 'dc-vv-111',
    definition: 'Feeling uninterested; nothing to do.',
    sentence: 'I\'m bored at home.',
    gloss: gloss('Aburrido', 'ملول', 'ऊबा हुआ', 'ሰልችቶኛል', 'ደሪቐ'),
  },
  {
    id: 'surprised-112',
    english: 'Surprised',
    emoji: 'SU',
    imageKey: 'dc-vv-112',
    definition: 'Feeling shocked by something unexpected.',
    sentence: 'Wow! I\'m surprised.',
    gloss: gloss('Sorprendido', 'متفاجئ', 'हैरान', 'ተገርሜያለሁ', 'ተገሪመ'),
  },
  {
    id: 'scared-113',
    english: 'Scared',
    emoji: 'SC',
    imageKey: 'dc-vv-113',
    definition: 'Feeling afraid.',
    sentence: 'I\'m scared of dogs.',
    gloss: gloss('Asustado', 'خائف', 'डरा हुआ', 'ፈርቻለሁ', 'ፈሪሐ'),
  },
  {
    id: 'confused-114',
    english: 'Confused',
    emoji: 'CO',
    imageKey: 'dc-vv-114',
    definition: 'Not clear about what something means.',
    sentence: 'I\'m confused. Help me.',
    gloss: gloss('Confundido', 'مرتبك', 'उलझन में', 'ግራ ተጋብቻለሁ', 'ተደናጊረ'),
  },
  {
    id: 'ready-115',
    english: 'Ready',
    emoji: 'RE',
    imageKey: 'dc-vv-115',
    definition: 'Prepared to start.',
    sentence: 'Are you ready? Let\'s go!',
    gloss: gloss('Listo', 'جاهز', 'तैयार', 'ዝግጁ', 'ድሉው'),
  },
  {
    id: 'not-ready-116',
    english: 'Not ready',
    emoji: 'NR',
    imageKey: 'dc-vv-116',
    definition: 'Not prepared yet.',
    sentence: 'Wait, I\'m not ready.',
    gloss: gloss('No estoy listo', 'لست جاهزًا', 'तैयार नहीं', 'ዝግጁ አይደለሁም', 'ድሉው አይኮንኩን'),
  },
  {
    id: 'easy-117',
    english: 'Easy',
    emoji: 'EA',
    imageKey: 'dc-vv-117',
    definition: 'Not hard to do.',
    sentence: 'This test is easy.',
    gloss: gloss('Fácil', 'سهل', 'आसान', 'ቀላል', 'ቀሊል'),
  },
  {
    id: 'difficult-118',
    english: 'Difficult',
    emoji: 'DI',
    imageKey: 'dc-vv-118',
    definition: 'Hard to do or understand.',
    sentence: 'English is difficult.',
    gloss: gloss('Difícil', 'صعب', 'मुश्किल', 'ከባድ', 'ከቢድ'),
  },
  {
    id: 'important-119',
    english: 'Important',
    emoji: 'IM',
    imageKey: 'dc-vv-119',
    definition: 'Matters a lot; take it seriously.',
    sentence: 'This is important.',
    gloss: gloss('Importante', 'مهم', 'ज़रूरी', 'አስፈላጊ', 'ኣገዳሲ'),
  },
  {
    id: 'not-important-120',
    english: 'Not important',
    emoji: 'NI',
    imageKey: 'dc-vv-120',
    definition: 'Does not matter much right now.',
    sentence: 'Don\'t worry, it\'s not important.',
    gloss: gloss('No es importante', 'غير مهم', 'ज़रूरी नहीं', 'አስፈላጊ አይደለም', 'ኣገዳሲ ኣይኮነን'),
  },
  {
    id: 'good-121',
    english: 'Good',
    emoji: 'GO',
    imageKey: 'dc-vv-121',
    definition: 'Positive quality; well done.',
    sentence: 'Good job!',
    gloss: gloss('Bueno', 'جيد', 'अच्छा', 'ጥሩ', 'ጽቡቕ'),
  },
  {
    id: 'bad-122',
    english: 'Bad',
    emoji: 'BA',
    imageKey: 'dc-vv-122',
    definition: 'Negative quality; not good.',
    sentence: 'The weather is bad.',
    gloss: gloss('Malo', 'سيئ', 'बुरा', 'መጥፎ', 'ሕማቅ'),
  },
  {
    id: 'better-123',
    english: 'Better',
    emoji: 'BE',
    imageKey: 'dc-vv-123',
    definition: 'Improved compared with before.',
    sentence: 'I feel better today.',
    gloss: gloss('Mejor', 'أفضل', 'बेहतर', 'የተሻለ', 'ዝሓሸ'),
  },
  {
    id: 'worse-124',
    english: 'Worse',
    emoji: 'WO',
    imageKey: 'dc-vv-124',
    definition: 'More bad than before.',
    sentence: 'The traffic is worse today.',
    gloss: gloss('Peor', 'أسوأ', 'और बुरा', 'የባሰ', 'ዝከፍአ'),
  },
  {
    id: 'best-125',
    english: 'Best',
    emoji: 'BE',
    imageKey: 'dc-vv-125',
    definition: 'The highest quality; number one.',
    sentence: 'You are the best!',
    gloss: gloss('El mejor', 'الأفضل', 'सबसे अच्छा', 'ምርጥ', 'ዝበለጸ'),
  },
  {
    id: 'worst-126',
    english: 'Worst',
    emoji: 'WO',
    imageKey: 'dc-vv-126',
    definition: 'The lowest quality; the most bad.',
    sentence: 'That was the worst day.',
    gloss: gloss('El peor', 'الأسوأ', 'सबसे बुरा', 'በጣም መጥፎ', 'ዝከፍአ'),
  },
  {
    id: 'early-127',
    english: 'Early',
    emoji: 'EA',
    imageKey: 'dc-vv-127',
    definition: 'Before the usual or expected time.',
    sentence: 'I wake up early.',
    gloss: gloss('Temprano', 'مبكرًا', 'जल्दी', 'በጊዜ', 'ኣቐዲሙ'),
  },
  {
    id: 'late-128',
    english: 'Late',
    emoji: 'LA',
    imageKey: 'dc-vv-128',
    definition: 'After the expected time.',
    sentence: 'Don\'t be late.',
    gloss: gloss('Tarde', 'متأخر', 'देर से', 'ዘግይቶ', 'ደንጉዩ'),
  },
  {
    id: 'on-time-129',
    english: 'On time',
    emoji: 'OT',
    imageKey: 'dc-vv-129',
    definition: 'At the correct planned time.',
    sentence: 'Please come on time.',
    gloss: gloss('A tiempo', 'في الوقت', 'समय पर', 'በሰዓቱ', 'ብግዜኡ'),
  },
  {
    id: 'delay-130',
    english: 'Delay',
    emoji: 'DE',
    imageKey: 'dc-vv-130',
    definition: 'A wait that makes something later than planned.',
    sentence: 'The flight has a delay.',
    gloss: gloss('Retraso', 'تأخير', 'देरी', 'መዘግየት', 'ምድንጉኣይ'),
  },
  {
    id: 'plan-131',
    english: 'Plan',
    emoji: 'PL',
    imageKey: 'dc-vv-131',
    definition: 'A set of steps for what you will do.',
    sentence: 'What\'s your plan today?',
    gloss: gloss('Plan', 'خطة', 'योजना', 'ዕቅድ', 'መደብ'),
  },
  {
    id: 'decide-132',
    english: 'Decide',
    emoji: 'DE',
    imageKey: 'dc-vv-132',
    definition: 'Choose one option after thinking.',
    sentence: 'I can\'t decide.',
    gloss: gloss('Decidir', 'قرر', 'फ़ैसला करना', 'ወስን', 'ወስን'),
  },
  {
    id: 'choose-133',
    english: 'Choose',
    emoji: 'CH',
    imageKey: 'dc-vv-133',
    definition: 'Pick one thing from options.',
    sentence: 'Choose A or B.',
    gloss: gloss('Elegir', 'اختر', 'चुनना', 'ምረጥ', 'ምረጽ'),
  },
  {
    id: 'change-134',
    english: 'Change',
    emoji: 'CH',
    imageKey: 'dc-vv-134',
    definition: 'Make something different.',
    sentence: 'I need to change my shirt.',
    gloss: gloss('Cambiar', 'غَيِّر', 'बदलना', 'ቀይር', 'ቀይር'),
  },
  {
    id: 'keep-135',
    english: 'Keep',
    emoji: 'KE',
    imageKey: 'dc-vv-135',
    definition: 'Hold onto something; do not give it away.',
    sentence: 'Keep this book.',
    gloss: gloss('Guardar', 'احتفظ', 'रखना', 'ያዝ', 'ሓዝ'),
  },
  {
    id: 'give-136',
    english: 'Give',
    emoji: 'GI',
    imageKey: 'dc-vv-136',
    definition: 'Hand something to someone.',
    sentence: 'Give me the gift, please.',
    gloss: gloss('Dar', 'أعط', 'देना', 'ስጥ', 'ሃብ'),
  },
  {
    id: 'get-137',
    english: 'Get',
    emoji: 'GE',
    imageKey: 'dc-vv-137',
    definition: 'Receive or obtain something.',
    sentence: 'I got a gift.',
    gloss: gloss('Obtener / Recibir', 'احصل', 'पाना', 'አግኝ', 'ርኸብ'),
  },
  {
    id: 'take-138',
    english: 'Take',
    emoji: 'TA',
    imageKey: 'dc-vv-138',
    definition: 'Accept something into your hand or care.',
    sentence: 'Take this book.',
    gloss: gloss('Tomar', 'خذ', 'लेना', 'ውሰድ', 'ውሰድ'),
  },
  {
    id: 'bring-139',
    english: 'Bring',
    emoji: 'BR',
    imageKey: 'dc-vv-139',
    definition: 'Carry something with you to a place.',
    sentence: 'Bring some food.',
    gloss: gloss('Traer', 'أحضر', 'लाना', 'አምጣ', 'ኣምጽእ'),
  },
  {
    id: 'carry-140',
    english: 'Carry',
    emoji: 'CA',
    imageKey: 'dc-vv-140',
    definition: 'Hold and move something from one place to another.',
    sentence: 'Carry the box, please.',
    gloss: gloss('Cargar', 'احمل', 'उठाना', 'ተሸከም', 'ጹር'),
  },
  {
    id: 'put-141',
    english: 'Put',
    emoji: 'PU',
    imageKey: 'dc-vv-141',
    definition: 'Place something in a position.',
    sentence: 'Put the book on the table.',
    gloss: gloss('Poner', 'ضع', 'रखना', 'አስቀምጥ', 'ኣንብር'),
  },
  {
    id: 'hold-142',
    english: 'Hold',
    emoji: 'HO',
    imageKey: 'dc-vv-142',
    definition: 'Keep something in your hands.',
    sentence: 'Hold the cup.',
    gloss: gloss('Sostener', 'أمسك', 'पकड़ना', 'ያዝ', 'ሓዝ'),
  },
  {
    id: 'drop-143',
    english: 'Drop',
    emoji: 'DR',
    imageKey: 'dc-vv-143',
    definition: 'Let something fall.',
    sentence: 'Don\'t drop the cup!',
    gloss: gloss('Dejar caer', 'أسقط', 'गिराना', 'ጣል', 'ኣውድቕ'),
  },
  {
    id: 'pick-up-144',
    english: 'Pick up',
    emoji: 'PU',
    imageKey: 'dc-vv-144',
    definition: 'Lift something from a lower place.',
    sentence: 'Pick up the book.',
    gloss: gloss('Recoger', 'التقط', 'उठाना', 'አንሳ', 'ኣልዕል'),
  },
  {
    id: 'use-145',
    english: 'Use',
    emoji: 'US',
    imageKey: 'dc-vv-145',
    definition: 'Do a task with a tool or object.',
    sentence: 'Use the computer.',
    gloss: gloss('Usar', 'استخدم', 'इस्तेमाल करना', 'ተጠቅም', 'ተጠቐም'),
  },
  {
    id: 'turn-on-146',
    english: 'Turn on',
    emoji: 'TO',
    imageKey: 'dc-vv-146',
    definition: 'Start a machine or light.',
    sentence: 'Turn on the light.',
    gloss: gloss('Encender', 'شغّل', 'चालू करना', 'አብራ', 'ወልዕ'),
  },
  {
    id: 'turn-off-147',
    english: 'Turn off',
    emoji: 'TO',
    imageKey: 'dc-vv-147',
    definition: 'Stop a machine or light.',
    sentence: 'Turn off the light.',
    gloss: gloss('Apagar', 'أطفئ', 'बंद करना', 'አጥፉ', 'አጥፍእ'),
  },
  {
    id: 'plug-in-148',
    english: 'Plug in',
    emoji: 'PI',
    imageKey: 'dc-vv-148',
    definition: 'Connect a cord to power.',
    sentence: 'Plug in the phone.',
    gloss: gloss('Enchufar', 'أوصل', 'प्लग लगाना', 'ሰካ', 'ስኻዕ'),
  },
  {
    id: 'unplug-149',
    english: 'Unplug',
    emoji: 'UN',
    imageKey: 'dc-vv-149',
    definition: 'Remove a cord from power.',
    sentence: 'Unplug it before you clean.',
    gloss: gloss('Desenchufar', 'افصل', 'प्लग निकालना', 'ንቀል', 'ንቐል'),
  },
  {
    id: 'charge-150',
    english: 'Charge',
    emoji: 'CH',
    imageKey: 'dc-vv-150',
    definition: 'Add power to a battery.',
    sentence: 'Charge your phone.',
    gloss: gloss('Cargar', 'اشحن', 'चार्ज करना', 'ቻርጅ አድርግ', 'ቻርጅ ግበር'),
  },
  {
    id: 'call-151',
    english: 'Call',
    emoji: 'CA',
    imageKey: 'dc-vv-151',
    definition: 'Phone someone.',
    sentence: 'Call me tonight.',
    gloss: gloss('Llamar', 'اتصل', 'फ़ोन करना', 'ደውል', 'ደውል'),
  },
  {
    id: 'text-152',
    english: 'Text',
    emoji: 'TE',
    imageKey: 'dc-vv-152',
    definition: 'Send a written message on a phone.',
    sentence: 'Text me the address.',
    gloss: gloss('Enviar mensaje', 'أرسل رسالة', 'मैसेज करना', 'መልዕክት ላክ', 'መልእኽቲ ስደድ'),
  },
  {
    id: 'check-153',
    english: 'Check',
    emoji: 'CH',
    imageKey: 'dc-vv-153',
    definition: 'Look carefully to confirm something.',
    sentence: 'Check the time.',
    gloss: gloss('Revisar', 'تحقق', 'जाँचना', 'አረጋግጥ', 'አረጋግጹ'),
  },
  {
    id: 'wait-154',
    english: 'Wait',
    emoji: 'WA',
    imageKey: 'dc-vv-154',
    definition: 'Stay in place for a short time.',
    sentence: 'Wait for the bus.',
    gloss: gloss('Esperar', 'انتظر', 'इंतज़ार करना', 'ጠብቅ', 'ተጸበ'),
  },
  {
    id: 'hurry-155',
    english: 'Hurry',
    emoji: 'HU',
    imageKey: 'dc-vv-155',
    definition: 'Move or act quickly.',
    sentence: 'Hurry! We\'re late.',
    gloss: gloss('Apurarse', 'أسرع', 'जल्दी करो', 'ፍጠን', 'ቅልጥፍ በል'),
  },
  {
    id: 'leave-156',
    english: 'Leave',
    emoji: 'LE',
    imageKey: 'dc-vv-156',
    definition: 'Go away from a place.',
    sentence: 'I leave at 8 o\'clock.',
    gloss: gloss('Salir', 'غادر', 'जाना / निकलना', 'ሂድ / ውጣ', 'ኺድ / ውጻእ'),
  },
  {
    id: 'arrive-157',
    english: 'Arrive',
    emoji: 'AR',
    imageKey: 'dc-vv-157',
    definition: 'Reach a place.',
    sentence: 'We arrive at noon.',
    gloss: gloss('Llegar', 'وصل', 'पहुँचना', 'ድረስ', 'ብጻሕ'),
  },
  {
    id: 'stay-158',
    english: 'Stay',
    emoji: 'ST',
    imageKey: 'dc-vv-158',
    definition: 'Remain in a place.',
    sentence: 'Stay at home today.',
    gloss: gloss('Quedarse', 'ابقَ', 'रुकना', 'ቆይ', 'ጽንሕ'),
  },
  {
    id: 'live-159',
    english: 'Live',
    emoji: 'LI',
    imageKey: 'dc-vv-159',
    definition: 'Have your home in a place.',
    sentence: 'I live in Calgary.',
    gloss: gloss('Vivir', 'يعيش', 'रहना', 'ኑር', 'ንበር'),
  },
  {
    id: 'work-160',
    english: 'Work',
    emoji: 'WO',
    imageKey: 'dc-vv-160',
    definition: 'Do a job or paid task.',
    sentence: 'I work at a construction site.',
    gloss: gloss('Trabajar', 'يعمل', 'काम करना', 'ሥራ', 'ስራሕ'),
  },
  {
    id: 'study-161',
    english: 'Study',
    emoji: 'ST',
    imageKey: 'dc-vv-161',
    definition: 'Spend time learning.',
    sentence: 'I study every night.',
    gloss: gloss('Estudiar', 'ادرس', 'पढ़ाई करना', 'አጥና', 'ኣጽንዕ'),
  },
  {
    id: 'learn-162',
    english: 'Learn',
    emoji: 'LE',
    imageKey: 'dc-vv-162',
    definition: 'Gain new knowledge or skill.',
    sentence: 'I learn new words.',
    gloss: gloss('Aprender', 'تعلّم', 'सीखना', 'ተማር', 'ተማሃር'),
  },
  {
    id: 'understand-163',
    english: 'Understand',
    emoji: 'UN',
    imageKey: 'dc-vv-163',
    definition: 'Know the meaning of something.',
    sentence: 'Do you understand?',
    gloss: gloss('Entender', 'افهم', 'समझना', 'ተረዳ', 'ተረዳእ'),
  },
  {
    id: 'remember-164',
    english: 'Remember',
    emoji: 'RE',
    imageKey: 'dc-vv-164',
    definition: 'Keep something in your mind.',
    sentence: 'Remember your keys.',
    gloss: gloss('Recordar', 'تذكّر', 'याद रखना', 'አስታውስ', 'ዘክር'),
  },
  {
    id: 'forget-165',
    english: 'Forget',
    emoji: 'FO',
    imageKey: 'dc-vv-165',
    definition: 'Fail to remember something.',
    sentence: 'Don\'t forget your lunch.',
    gloss: gloss('Olvidar', 'انَسَى', 'भूलना', 'እርሳ', 'ረስዕ'),
  },
  {
    id: 'know-166',
    english: 'Know',
    emoji: 'KN',
    imageKey: 'dc-vv-166',
    definition: 'Have information or skill in your mind.',
    sentence: 'I know the answer.',
    gloss: gloss('Saber', 'اعرف', 'जानना', 'እወቅ', 'ፍለጥ'),
  },
  {
    id: 'try-167',
    english: 'Try',
    emoji: 'TR',
    imageKey: 'dc-vv-167',
    definition: 'Make an attempt.',
    sentence: 'Try again.',
    gloss: gloss('Intentar', 'حاول', 'कोशिश करना', 'ሞክር', 'ፈትን'),
  },
  {
    id: 'practice-168',
    english: 'Practice',
    emoji: 'PR',
    imageKey: 'dc-vv-168',
    definition: 'Do something again to get better.',
    sentence: 'Practice every day.',
    gloss: gloss('Practicar', 'تدرّب', 'अभ्यास करना', 'ተለማመዱ', 'ተለማመዱ'),
  },
  {
    id: 'improve-169',
    english: 'Improve',
    emoji: 'IM',
    imageKey: 'dc-vv-169',
    definition: 'Become better over time.',
    sentence: 'My English will improve.',
    gloss: gloss('Mejorar', 'حسّن', 'सुधारना', 'አሻሽል', 'ኣመሓይሽ'),
  },
  {
    id: 'start-170',
    english: 'Start',
    emoji: 'ST',
    imageKey: 'dc-vv-170',
    definition: 'Begin an action.',
    sentence: 'Let\'s start the class.',
    gloss: gloss('Empezar', 'ابدأ', 'शुरू करना', 'ጀምር', 'ጀምር'),
  },
  {
    id: 'finish-171',
    english: 'Finish',
    emoji: 'FI',
    imageKey: 'dc-vv-171',
    definition: 'Complete an action.',
    sentence: 'Finish your work.',
    gloss: gloss('Terminar', 'أنهِ', 'ख़त्म करना', 'ጨርስ', 'ወድእ'),
  },
  {
    id: 'continue-172',
    english: 'Continue',
    emoji: 'CO',
    imageKey: 'dc-vv-172',
    definition: 'Keep going without stopping.',
    sentence: 'Please continue.',
    gloss: gloss('Continuar', 'تابع', 'जारी रखना', 'ቀጥል', 'ቀጽል'),
  },
  {
    id: 'stop-173',
    english: 'Stop',
    emoji: 'ST',
    imageKey: 'dc-vv-173',
    definition: 'Do not continue; halt an action.',
    sentence: 'Stop the music.',
    gloss: gloss('Parar', 'توقف', 'रोकना', 'አቁም', 'ደው ኣብል'),
  },
  {
    id: 'pause-174',
    english: 'Pause',
    emoji: 'PA',
    imageKey: 'dc-vv-174',
    definition: 'Stop briefly, then you may continue.',
    sentence: 'Pause the video.',
    gloss: gloss('Pausar', 'إيقاف مؤقت', 'रोकना (थोड़ा)', 'ለእፍታ አቁም', 'ንቕሩብ ደው ኣብል'),
  },
  {
    id: 'restart-175',
    english: 'Restart',
    emoji: 'RE',
    imageKey: 'dc-vv-175',
    definition: 'Start again from the beginning.',
    sentence: 'Restart the computer.',
    gloss: gloss('Reiniciar', 'أعد التشغيل', 'फिर से शुरू करना', 'እንደገና ጀምር', 'ዳግማይ ጀምር'),
  },
  {
    id: 'save-176',
    english: 'Save',
    emoji: 'SA',
    imageKey: 'dc-vv-176',
    definition: 'Keep a file or work so it is not lost.',
    sentence: 'Save the file.',
    gloss: gloss('Guardar', 'احفظ', 'सेव करना', 'አስቀምጥ (ሴቭ)', 'ዕቀብ (ሴቭ)'),
  },
  {
    id: 'delete-177',
    english: 'Delete',
    emoji: 'DE',
    imageKey: 'dc-vv-177',
    definition: 'Remove something permanently.',
    sentence: 'Delete the old photos.',
    gloss: gloss('Borrar', 'احذف', 'डिलीट करना', 'አጥፋ', 'ደምስስ'),
  },
  {
    id: 'send-178',
    english: 'Send',
    emoji: 'SE',
    imageKey: 'dc-vv-178',
    definition: 'Pass a message or file to someone.',
    sentence: 'Send me an email.',
    gloss: gloss('Enviar', 'أرسل', 'भेजना', 'ላክ', 'ስደድ'),
  },
  {
    id: 'receive-179',
    english: 'Receive',
    emoji: 'RE',
    imageKey: 'dc-vv-179',
    definition: 'Get a message or item that was sent.',
    sentence: 'I received your letter.',
    gloss: gloss('Recibir', 'استلم', 'प्राप्त करना', 'ተቀበል', 'ተቐበል'),
  },
  {
    id: 'share-180',
    english: 'Share',
    emoji: 'SH',
    imageKey: 'dc-vv-180',
    definition: 'Let others see or use something with you.',
    sentence: 'Share the photo with me.',
    gloss: gloss('Compartir', 'شارك', 'शेयर करना', 'አጋራ', 'ኣካፍል'),
  },
  {
    id: 'help-181',
    english: 'Help',
    emoji: 'HE',
    imageKey: 'dc-vv-181',
    definition: 'Do something useful for another person.',
    sentence: 'Can you help me?',
    gloss: gloss('Ayudar', 'ساعد', 'मदद करना', 'እርዳታ', 'ሓገዝ'),
  },
  {
    id: 'support-182',
    english: 'Support',
    emoji: 'SU',
    imageKey: 'dc-vv-182',
    definition: 'Give help or encouragement.',
    sentence: 'We support each other.',
    gloss: gloss('Apoyar', 'ادعم', 'सहारा देना', 'ድጋፍ', 'ደገፍ'),
  },
  {
    id: 'cooperate-183',
    english: 'Cooperate',
    emoji: 'CO',
    imageKey: 'dc-vv-183',
    definition: 'Work with others toward one goal.',
    sentence: 'Let\'s cooperate as a team.',
    gloss: gloss('Cooperar', 'تعاون', 'सहयोग करना', 'ተባበር', 'ተሓባበር'),
  },
  {
    id: 'communicate-184',
    english: 'Communicate',
    emoji: 'CO',
    imageKey: 'dc-vv-184',
    definition: 'Share information by talking or writing.',
    sentence: 'We communicate every day.',
    gloss: gloss('Comunicarse', 'تواصل', 'बातचीत करना', 'ተግባባ', 'ተዛራረብ'),
  },
  {
    id: 'listen-185',
    english: 'Listen',
    emoji: 'LI',
    imageKey: 'dc-vv-185',
    definition: 'Use your ears to hear carefully.',
    sentence: 'Listen carefully.',
    gloss: gloss('Escuchar', 'استمع', 'सुनना', 'አዳምጥ', 'ስማዕ'),
  },
  {
    id: 'speak-186',
    english: 'Speak',
    emoji: 'SP',
    imageKey: 'dc-vv-186',
    definition: 'Say words out loud.',
    sentence: 'Speak English in class.',
    gloss: gloss('Hablar', 'تَكَلَّمْ', 'बोलना', 'ተናገር', 'ተዛረብ'),
  },
  {
    id: 'ask-187',
    english: 'Ask',
    emoji: 'AS',
    imageKey: 'dc-vv-187',
    definition: 'Request information or help with a question.',
    sentence: 'Ask the teacher.',
    gloss: gloss('Preguntar', 'اسأل', 'पूछना', 'ጠይቅ', 'ሕተት'),
  },
  {
    id: 'answer-188',
    english: 'Answer',
    emoji: 'AN',
    imageKey: 'dc-vv-188',
    definition: 'Reply to a question.',
    sentence: 'Answer the question.',
    gloss: gloss('Responder', 'أجب', 'जवाब देना', 'መልስ', 'መልሲ'),
  },
  {
    id: 'agree-189',
    english: 'Agree',
    emoji: 'AG',
    imageKey: 'dc-vv-189',
    definition: 'Have the same opinion.',
    sentence: 'I agree with you.',
    gloss: gloss('Estar de acuerdo', 'أوافق', 'सहमत होना', 'እስማማለሁ', 'ይሰማማዕ'),
  },
  {
    id: 'disagree-190',
    english: 'Disagree',
    emoji: 'DI',
    imageKey: 'dc-vv-190',
    definition: 'Have a different opinion.',
    sentence: 'Sorry, I disagree.',
    gloss: gloss('No estar de acuerdo', 'لا أوافق', 'असहमत होना', 'አልስማማም', 'ኣይሰማማዕን'),
  },
  {
    id: 'problem-191',
    english: 'Problem',
    emoji: 'PR',
    imageKey: 'dc-vv-191',
    definition: 'Something wrong that needs fixing.',
    sentence: 'We have a problem.',
    gloss: gloss('Problema', 'مشكلة', 'समस्या', 'ችግር', 'ጸገም'),
  },
  {
    id: 'solution-192',
    english: 'Solution',
    emoji: 'SO',
    imageKey: 'dc-vv-192',
    definition: 'An answer that fixes a problem.',
    sentence: 'I found a solution.',
    gloss: gloss('Solución', 'حل', 'समाधान', 'መፍትሔ', 'ፍታሕ'),
  },
  {
    id: 'idea-193',
    english: 'Idea',
    emoji: 'ID',
    imageKey: 'dc-vv-193',
    definition: 'A thought or suggestion.',
    sentence: 'That\'s a good idea!',
    gloss: gloss('Idea', 'فكرة', 'विचार', 'ሐሳብ', 'ሓሳብ'),
  },
  {
    id: 'plan-194',
    english: 'Plan',
    emoji: 'PL',
    imageKey: 'dc-vv-194',
    definition: 'A set of steps for what you will do.',
    sentence: 'Make a plan for the week.',
    gloss: gloss('Plan', 'خطة', 'योजना', 'ዕቅድ', 'መደብ'),
  },
  {
    id: 'goal-195',
    english: 'Goal',
    emoji: 'GO',
    imageKey: 'dc-vv-195',
    definition: 'Something you want to achieve.',
    sentence: 'My goal is to learn English.',
    gloss: gloss('Meta', 'هدف', 'लक्ष्य', 'ግብ', 'ዕላማ'),
  },
  {
    id: 'success-196',
    english: 'Success',
    emoji: 'SU',
    imageKey: 'dc-vv-196',
    definition: 'A good result after effort.',
    sentence: 'Hard work brings success.',
    gloss: gloss('Éxito', 'نجاح', 'सफलता', 'ስኬት', 'ዓወት'),
  },
  {
    id: 'challenge-197',
    english: 'Challenge',
    emoji: 'CH',
    imageKey: 'dc-vv-197',
    definition: 'A hard task that tests you.',
    sentence: 'This job is a challenge.',
    gloss: gloss('Desafío', 'تحدّ', 'चुनौती', 'ፈተና', 'ብድሆ'),
  },
  {
    id: 'opportunity-198',
    english: 'Opportunity',
    emoji: 'OP',
    imageKey: 'dc-vv-198',
    definition: 'A good chance to do something useful.',
    sentence: 'This is a great opportunity.',
    gloss: gloss('Oportunidad', 'فرصة', 'अवसर', 'ዕድል', 'ዕድል'),
  },
  {
    id: 'future-199',
    english: 'Future',
    emoji: 'FU',
    imageKey: 'dc-vv-199',
    definition: 'The time that comes after now.',
    sentence: 'I have a bright future.',
    gloss: gloss('Futuro', 'المستقبل', 'भविष्य', 'ወደፊት', 'መጻኢ'),
  },
  {
    id: 'thank-you-200',
    english: 'Thank you',
    emoji: 'TY',
    imageKey: 'dc-vv-200',
    definition: 'A polite phrase used to show gratitude.',
    sentence: 'Thank you for learning with us!',
    gloss: gloss('Gracias', 'شكرًا لك', 'धन्यवाद', 'አመሰግናለሁ', 'የቐንየለይ'),
  },
]
