import type { PathwayPack } from '../types'
import { gloss, hint } from '../packHelpers'

/**
 * Logistics Foundations content pack.
 * Matches Construction Foundations craftsmanship depth (MSSC CLA/CLT flow,
 * OSHA pedestrian / MHE awareness). Powered forklifts = awareness / stay clear
 * only — never claimed as certification.
 */
export const logisticsPack: PathwayPack = {
  id: 'logistics',
  skillDomains: {
    vocabulary: 'Vocabulary',
    safety: 'Safety',
    tools: 'Equipment',
    systems: 'Logistics skills',
  },
  unitGoals: {
    3: {
      goal: 'Learn the Level-1 warehouse words you will hear on an Alberta logistics floor.',
      outcomes: [
        'See each object and hear English',
        'Connect the English word to the real warehouse action',
      ],
    },
    4: {
      goal: 'Use English with support, then prove you can find and follow warehouse language.',
      outcomes: [
        'Match pictures to English words',
        'Find objects in a busy bay',
        'Follow short workplace instructions',
        'Understand common warehouse phrases',
      ],
    },
    5: {
      goal: 'Build the digital, safety, equipment, and systems foundations every warehouse expects.',
      outcomes: [
        'Practice school computer tasks',
        'Pass required safety checks',
        'Name equipment groups and logistics systems (receive → store → pick → ship)',
      ],
    },
    6: {
      goal: 'Prove floor readiness under observation, then connect to logistics employment support.',
      outcomes: [
        'Rehearse competent skill order with measurable steps',
        'Make safe floor decisions, including OS&D and stop-work',
        'Pass the final checks and open employment support',
      ],
    },
  },
  stepTitles: {
    12: {
      title: 'Warehouse Language',
      help: 'Hear a warehouse phrase. Choose what it means.',
      purpose: 'Useful English you will hear in Alberta logistics workplaces.',
    },
    15: {
      title: 'Equipment & Materials',
      help: 'Learn each equipment group. Answer one check.',
      purpose: 'Safe naming before safe use with an instructor.',
    },
    16: {
      title: 'Logistics Systems',
      help: 'Learn each system. Answer one check.',
      purpose: 'Your task keeps goods moving safely and on time.',
    },
    18: {
      title: 'Warehouse Floor Training',
      help: 'Make floor decisions and log the day like a real team member.',
      purpose: 'Daily judgment, notes, and supervisor feedback.',
    },
  },
  vocab: [
    {
      id: 'pallet',
      english: 'Pallet',
      emoji: 'PL',
      imageKey: 'log-pallet',
      definition: 'A flat wooden or plastic platform used to stack and move goods.',
      sentence: 'Load the boxes evenly onto the pallet.',
      gloss: gloss('Paleta', 'Tabiq naqil', 'Palette', 'Palette', 'Palette'),
    },
    {
      id: 'scanner',
      english: 'Scanner',
      emoji: 'SC',
      imageKey: 'log-scanner',
      definition: 'A handheld device that reads barcodes on labels.',
      sentence: 'Scan the barcode and wait for the beep.',
      gloss: gloss('Escaner', 'Masah', 'Scanner', 'Scanner', 'Scanner'),
    },
    {
      id: 'label',
      english: 'Shipping label',
      emoji: 'LB',
      imageKey: 'log-label',
      definition: 'A sticker that shows destination, barcode, and order details.',
      sentence: 'Check the shipping label before you stage the box.',
      gloss: gloss('Etiqueta de envio', 'Bitagat shahn', 'Shipping label', 'Shipping label', 'Shipping label'),
    },
    {
      id: 'vest',
      english: 'Safety vest',
      emoji: 'SV',
      imageKey: 'log-vest',
      definition: 'A bright high-visibility vest that helps people and drivers see you.',
      sentence: 'Put on your safety vest before you enter the floor.',
      gloss: gloss('Chaleco de seguridad', 'Sitra amn', 'Safety vest', 'Safety vest', 'Safety vest'),
    },
    {
      id: 'dolly',
      english: 'Hand truck',
      emoji: 'HT',
      imageKey: 'log-dolly',
      definition: 'A two-wheel cart for moving heavy boxes by hand.',
      sentence: 'Use the hand truck for the heavy boxes.',
      gloss: gloss('Carretilla', 'Arabat yad', 'Hand truck', 'Hand truck', 'Hand truck'),
    },
    {
      id: 'manifest',
      english: 'Manifest',
      emoji: 'MF',
      imageKey: 'log-manifest',
      definition: 'A list of what is on a shipment, pallet, or truck.',
      sentence: 'Check the manifest before you sign for the load.',
      gloss: gloss('Manifiesto', 'Qaimat shahn', 'Manifest', 'Manifest', 'Manifest'),
    },
    {
      id: 'rack',
      english: 'Storage rack',
      emoji: 'RK',
      imageKey: 'log-rack',
      definition: 'Industrial shelving used to store pallets and cartons by location.',
      sentence: 'Place the pallet squarely on the storage rack.',
      gloss: gloss('Estanteria', 'Raf takhzin', 'Storage rack', 'Storage rack', 'Storage rack'),
    },
    {
      id: 'jack',
      english: 'Pallet jack',
      emoji: 'PJ',
      imageKey: 'log-jack',
      definition: 'A manual jack that slides under a pallet so you can roll it short distances.',
      sentence: 'Slide the pallet jack under the pallet before you lift.',
      gloss: gloss('Gato de paleta', 'Rafi at al-tabiq', 'Pallet jack', 'Pallet jack', 'Pallet jack'),
    },
    {
      id: 'wrap',
      english: 'Stretch wrap',
      emoji: 'SW',
      imageKey: 'log-wrap',
      definition: 'Plastic film wrapped tightly around a pallet to keep the load stable.',
      sentence: 'Wrap the pallet with stretch wrap before shipping.',
      gloss: gloss('Film estirable', 'Ghilaf mutamatit', 'Stretch wrap', 'Stretch wrap', 'Stretch wrap'),
    },
  ],
  wordActions: [
    {
      id: 'wa-pallet',
      termId: 'pallet',
      title: 'Pallet in action',
      body: 'Stack boxes evenly on a sound pallet. Keep weight balanced and corners clear of overhang.',
      actionCue: 'Even stack. Balanced load. No overhang.',
    },
    {
      id: 'wa-scanner',
      termId: 'scanner',
      title: 'Scanner in action',
      body: 'Aim the scanner at the barcode. Wait for the beep and confirm the screen before you stage.',
      actionCue: 'Aim. Beep. Confirm the screen.',
    },
    {
      id: 'wa-label',
      termId: 'label',
      title: 'Shipping label in action',
      body: 'Read the destination and order codes before you move the package. Scan before you stage.',
      actionCue: 'Read the label. Match the bay. Then move.',
    },
    {
      id: 'wa-vest',
      termId: 'vest',
      title: 'Safety vest before entry',
      body: 'Put the bright vest on before you cross onto the warehouse floor. Visibility is a duty, not optional.',
      actionCue: 'Vest on before you enter.',
    },
    {
      id: 'wa-dolly',
      termId: 'dolly',
      title: 'Hand truck in action',
      body: 'Clear the path, load a balanced stack, tilt back carefully, and walk at a steady pace.',
      actionCue: 'Clear path. Tilt. Steady walk.',
    },
    {
      id: 'wa-manifest',
      termId: 'manifest',
      title: 'Manifest check',
      body: 'Count items against the list. Note overage, shortage, or damage (OS&D) before you sign.',
      actionCue: 'Count. Match the list. Report OS&D.',
    },
    {
      id: 'wa-rack',
      termId: 'rack',
      title: 'Storage rack in action',
      body: 'Place the pallet squarely in the assigned location. Never climb the rack. Keep hands clear of beams.',
      actionCue: 'Square place. No climbing. Hands clear.',
    },
    {
      id: 'wa-jack',
      termId: 'jack',
      title: 'Pallet jack in action',
      body: 'Slide forks fully under the pallet, pump to lift just clear of the floor, then roll with a clear path. Stay clear of powered forklifts — those need separate certification.',
      actionCue: 'Forks under. Lift clear. Path clear.',
    },
    {
      id: 'wa-wrap',
      termId: 'wrap',
      title: 'Stretch wrap in action',
      body: 'Anchor the film at the base, wrap upward with tension, and cover the top corners so the load cannot shift.',
      actionCue: 'Anchor base. Tension wrap. Secure top.',
    },
  ],
  eyeSpyScenes: [
    {
      id: 'bay-a-scanner',
      title: 'Receiving bay A',
      instruction: 'Find the scanner. Tap it in the scene, then confirm the English name.',
      targetId: 'scanner',
      distractors: ['Pallet', 'Safety vest', 'Hand truck'],
      variantGroup: 'bay-scanner',
      hotspots: [
        { id: 'scanner', label: 'Scanner', answer: 'Scanner', imageKey: 'log-scanner', x: 14, y: 40, w: 22, h: 28 },
        { id: 'pallet', label: 'Pallet', answer: 'Pallet', imageKey: 'log-pallet', x: 55, y: 50, w: 28, h: 26 },
        { id: 'vest', label: 'Safety vest', answer: 'Safety vest', imageKey: 'log-vest', x: 40, y: 12, w: 20, h: 24 },
        { id: 'dolly', label: 'Hand truck', answer: 'Hand truck', imageKey: 'log-dolly', x: 72, y: 30, w: 20, h: 30 },
      ],
    },
    {
      id: 'bay-b-scanner',
      title: 'Receiving bay B',
      instruction: 'Find the scanner. Tap it in the scene, then confirm the English name.',
      targetId: 'scanner',
      distractors: ['Shipping label', 'Manifest', 'Storage rack'],
      variantGroup: 'bay-scanner',
      hotspots: [
        { id: 'label', label: 'Shipping label', answer: 'Shipping label', imageKey: 'log-label', x: 10, y: 18, w: 22, h: 22 },
        { id: 'scanner', label: 'Scanner', answer: 'Scanner', imageKey: 'log-scanner', x: 58, y: 42, w: 22, h: 28 },
        { id: 'manifest', label: 'Manifest', answer: 'Manifest', imageKey: 'log-manifest', x: 36, y: 55, w: 22, h: 24 },
        { id: 'rack', label: 'Storage rack', answer: 'Storage rack', imageKey: 'log-rack', x: 74, y: 12, w: 20, h: 30 },
      ],
    },
    {
      id: 'floor-a-vest',
      title: 'Floor walk A',
      instruction: 'Find the safety vest. Tap it in the scene, then confirm the English name.',
      targetId: 'vest',
      distractors: ['Pallet', 'Hand truck', 'Scanner'],
      variantGroup: 'floor-vest',
      hotspots: [
        { id: 'vest', label: 'Safety vest', answer: 'Safety vest', imageKey: 'log-vest', x: 20, y: 20, w: 22, h: 28 },
        { id: 'pallet', label: 'Pallet', answer: 'Pallet', imageKey: 'log-pallet', x: 55, y: 55, w: 28, h: 24 },
        { id: 'dolly', label: 'Hand truck', answer: 'Hand truck', imageKey: 'log-dolly', x: 70, y: 25, w: 20, h: 32 },
        { id: 'scanner', label: 'Scanner', answer: 'Scanner', imageKey: 'log-scanner', x: 40, y: 48, w: 18, h: 24 },
      ],
    },
    {
      id: 'floor-b-vest',
      title: 'Floor walk B',
      instruction: 'Find the safety vest. Tap it in the scene, then confirm the English name.',
      targetId: 'vest',
      distractors: ['Manifest', 'Shipping label', 'Storage rack'],
      variantGroup: 'floor-vest',
      hotspots: [
        { id: 'manifest', label: 'Manifest', answer: 'Manifest', imageKey: 'log-manifest', x: 12, y: 50, w: 22, h: 24 },
        { id: 'vest', label: 'Safety vest', answer: 'Safety vest', imageKey: 'log-vest', x: 48, y: 18, w: 22, h: 28 },
        { id: 'label', label: 'Shipping label', answer: 'Shipping label', imageKey: 'log-label', x: 70, y: 55, w: 20, h: 22 },
        { id: 'rack', label: 'Storage rack', answer: 'Storage rack', imageKey: 'log-rack', x: 30, y: 12, w: 22, h: 30 },
      ],
    },
    {
      id: 'stage-a-label',
      title: 'Staging lane A',
      instruction: 'Find the shipping label. Tap it in the scene, then confirm the English name.',
      targetId: 'label',
      distractors: ['Scanner', 'Pallet', 'Stretch wrap'],
      variantGroup: 'stage-label',
      hotspots: [
        { id: 'label', label: 'Shipping label', answer: 'Shipping label', imageKey: 'log-label', x: 18, y: 22, w: 22, h: 24 },
        { id: 'scanner', label: 'Scanner', answer: 'Scanner', imageKey: 'log-scanner', x: 52, y: 48, w: 22, h: 28 },
        { id: 'pallet', label: 'Pallet', answer: 'Pallet', imageKey: 'log-pallet', x: 68, y: 20, w: 26, h: 24 },
        { id: 'wrap', label: 'Stretch wrap', answer: 'Stretch wrap', imageKey: 'log-wrap', x: 36, y: 55, w: 20, h: 26 },
      ],
    },
    {
      id: 'stage-b-label',
      title: 'Staging lane B',
      instruction: 'Find the shipping label. Tap it in the scene, then confirm the English name.',
      targetId: 'label',
      distractors: ['Manifest', 'Hand truck', 'Pallet jack'],
      variantGroup: 'stage-label',
      hotspots: [
        { id: 'manifest', label: 'Manifest', answer: 'Manifest', imageKey: 'log-manifest', x: 10, y: 48, w: 22, h: 24 },
        { id: 'label', label: 'Shipping label', answer: 'Shipping label', imageKey: 'log-label', x: 55, y: 16, w: 22, h: 24 },
        { id: 'dolly', label: 'Hand truck', answer: 'Hand truck', imageKey: 'log-dolly', x: 72, y: 42, w: 20, h: 32 },
        { id: 'jack', label: 'Pallet jack', answer: 'Pallet jack', imageKey: 'log-jack', x: 30, y: 28, w: 24, h: 28 },
      ],
    },
    {
      id: 'aisle-a-jack',
      title: 'Put-away aisle A',
      instruction: 'Find the pallet jack. Tap it in the scene, then confirm the English name.',
      targetId: 'jack',
      distractors: ['Storage rack', 'Pallet', 'Safety vest'],
      variantGroup: 'aisle-jack',
      hotspots: [
        { id: 'jack', label: 'Pallet jack', answer: 'Pallet jack', imageKey: 'log-jack', x: 16, y: 45, w: 26, h: 30 },
        { id: 'rack', label: 'Storage rack', answer: 'Storage rack', imageKey: 'log-rack', x: 58, y: 12, w: 22, h: 32 },
        { id: 'pallet', label: 'Pallet', answer: 'Pallet', imageKey: 'log-pallet', x: 70, y: 52, w: 26, h: 24 },
        { id: 'vest', label: 'Safety vest', answer: 'Safety vest', imageKey: 'log-vest', x: 40, y: 20, w: 20, h: 26 },
      ],
    },
    {
      id: 'aisle-b-jack',
      title: 'Put-away aisle B',
      instruction: 'Find the pallet jack. Tap it in the scene, then confirm the English name.',
      targetId: 'jack',
      distractors: ['Hand truck', 'Stretch wrap', 'Scanner'],
      variantGroup: 'aisle-jack',
      hotspots: [
        { id: 'dolly', label: 'Hand truck', answer: 'Hand truck', imageKey: 'log-dolly', x: 12, y: 22, w: 20, h: 32 },
        { id: 'jack', label: 'Pallet jack', answer: 'Pallet jack', imageKey: 'log-jack', x: 48, y: 40, w: 26, h: 30 },
        { id: 'wrap', label: 'Stretch wrap', answer: 'Stretch wrap', imageKey: 'log-wrap', x: 72, y: 18, w: 20, h: 26 },
        { id: 'scanner', label: 'Scanner', answer: 'Scanner', imageKey: 'log-scanner', x: 32, y: 55, w: 18, h: 24 },
      ],
    },
    {
      id: 'ship-a-wrap',
      title: 'Shipping dock A',
      instruction: 'Find the stretch wrap. Tap it in the scene, then confirm the English name.',
      targetId: 'wrap',
      distractors: ['Pallet', 'Manifest', 'Shipping label'],
      variantGroup: 'ship-wrap',
      hotspots: [
        { id: 'wrap', label: 'Stretch wrap', answer: 'Stretch wrap', imageKey: 'log-wrap', x: 22, y: 30, w: 22, h: 28 },
        { id: 'pallet', label: 'Pallet', answer: 'Pallet', imageKey: 'log-pallet', x: 55, y: 50, w: 28, h: 26 },
        { id: 'manifest', label: 'Manifest', answer: 'Manifest', imageKey: 'log-manifest', x: 70, y: 16, w: 22, h: 24 },
        { id: 'label', label: 'Shipping label', answer: 'Shipping label', imageKey: 'log-label', x: 40, y: 55, w: 20, h: 22 },
      ],
    },
    {
      id: 'ship-b-wrap',
      title: 'Shipping dock B',
      instruction: 'Find the stretch wrap. Tap it in the scene, then confirm the English name.',
      targetId: 'wrap',
      distractors: ['Pallet jack', 'Storage rack', 'Hand truck'],
      variantGroup: 'ship-wrap',
      hotspots: [
        { id: 'jack', label: 'Pallet jack', answer: 'Pallet jack', imageKey: 'log-jack', x: 10, y: 42, w: 24, h: 30 },
        { id: 'wrap', label: 'Stretch wrap', answer: 'Stretch wrap', imageKey: 'log-wrap', x: 50, y: 20, w: 22, h: 28 },
        { id: 'rack', label: 'Storage rack', answer: 'Storage rack', imageKey: 'log-rack', x: 74, y: 12, w: 20, h: 30 },
        { id: 'dolly', label: 'Hand truck', answer: 'Hand truck', imageKey: 'log-dolly', x: 34, y: 52, w: 20, h: 30 },
      ],
    },
  ],
  workplaceInstructions: [
    {
      text: 'Scan the shipping label.',
      correct: 'Scan the shipping label',
      imageKey: 'log-label',
      options: ['Scan the shipping label', 'Move the pallet first', 'Remove your vest', 'Climb the rack'],
      supportHint: hint(
        'Scan the shipping label.',
        'Escanea la etiqueta de envio.',
        'Imsah bitagat al-shahn.',
        'Shipping label scan karo.',
        'Shipping label scan adirgu.',
        'Shipping label scan gebiru.',
      ),
    },
    {
      text: 'Put on your safety vest before you enter.',
      correct: 'Put on your safety vest before you enter',
      imageKey: 'log-vest',
      options: [
        'Put on your safety vest before you enter',
        'Leave the vest in the break room',
        'Start loading without gear',
        'Stand in the forklift path',
      ],
      supportHint: hint(
        'Put on your safety vest before you enter.',
        'Ponte el chaleco antes de entrar.',
        'Irtiadi al-sitra qabla al-dukhul.',
        'Andar jane se pehle safety vest pehno.',
        'Ke megebat befit safety vest asdigu.',
        'Qidmi meAtat safety vest asdugu.',
      ),
    },
    {
      text: 'Load the boxes onto the pallet.',
      correct: 'Load the boxes onto the pallet',
      imageKey: 'log-pallet',
      options: ['Load the boxes onto the pallet', 'Throw boxes into the aisle', 'Block the exit', 'Ignore the manifest'],
      supportHint: hint(
        'Load the boxes onto the pallet.',
        'Carga las cajas en la paleta.',
        'Hammal al-sanadiq ala al-tabiq.',
        'Boxes ko palette par load karo.',
        'Sandukochun be palette lay asferu.',
        'Sandukkat ab palette asferu.',
      ),
    },
    {
      text: 'Check the manifest before loading.',
      correct: 'Check the manifest before loading',
      imageKey: 'log-manifest',
      options: [
        'Check the manifest before loading',
        'Load anything nearby',
        'Skip the count',
        'Sign a blank page',
      ],
      supportHint: hint(
        'Check the manifest before loading.',
        'Revisa el manifiesto antes de cargar.',
        'Raji al-qaima qabla al-tahmil.',
        'Load se pehle manifest check karo.',
        'Ke meferat befit manifest yaregagtu.',
        'Qidmi meferat manifest aregagtsu.',
      ),
    },
    {
      text: 'Use the hand truck for heavy boxes.',
      correct: 'Use the hand truck for heavy boxes',
      imageKey: 'log-dolly',
      options: [
        'Use the hand truck for heavy boxes',
        'Carry overloaded stacks alone',
        'Slide boxes with your feet',
        'Climb onto the rack',
      ],
      supportHint: hint(
        'Use the hand truck for heavy boxes.',
        'Usa la carretilla para cajas pesadas.',
        'Istakhdim arabat al-yad lil-sanadiq al-thaqila.',
        'Bhari boxes ke liye hand truck use karo.',
        'Lezinu sandukoch le hand truck techemu.',
        'Nkabd sandukkat hand truck tegberu.',
      ),
    },
    {
      text: 'Slide the pallet jack under the pallet.',
      correct: 'Slide the pallet jack under the pallet',
      imageKey: 'log-jack',
      options: [
        'Slide the pallet jack under the pallet',
        'Drive a forklift without training',
        'Pull the pallet by the stretch wrap',
        'Leave the jack blocking the aisle',
      ],
      supportHint: hint(
        'Slide the pallet jack under the pallet.',
        'Desliza el gato de paleta bajo la paleta.',
        'Adkhil rafi at al-tabiq taht al-tabiq.',
        'Pallet jack ko palette ke neeche slide karo.',
        'Pallet jackun ke pallet tac asgedu.',
        'Pallet jack ab pallet tichti asgedu.',
      ),
    },
    {
      text: 'Wrap the pallet with stretch wrap.',
      correct: 'Wrap the pallet with stretch wrap',
      imageKey: 'log-wrap',
      options: [
        'Wrap the pallet with stretch wrap',
        'Leave the load loose',
        'Tape only one corner',
        'Stack past the rack beam',
      ],
      supportHint: hint(
        'Wrap the pallet with stretch wrap.',
        'Envuelve la paleta con film estirable.',
        'Luff al-tabiq bil-ghilaf al-mutamatit.',
        'Palette ko stretch wrap se wrap karo.',
        'Palette be stretch wrap tififu.',
        'Palette bstretch wrap tififu.',
      ),
    },
    {
      text: 'Stage the pallet in bay three.',
      correct: 'Stage the pallet in bay three',
      imageKey: 'log-pallet',
      options: [
        'Stage the pallet in bay three',
        'Leave it in the main aisle',
        'Put it wherever is closest',
        'Load it on a truck without scanning',
      ],
      supportHint: hint(
        'Stage the pallet in bay three.',
        'Coloca la paleta en la bahia tres.',
        'Waddi al-tabiq ila al-maqarr al-thalith.',
        'Palette ko bay three mein stage karo.',
        'Palette bay sost lay asferu.',
        'Palette nab bay seleste asferu.',
      ),
    },
    {
      text: 'Keep the aisle clear.',
      correct: 'Keep the aisle clear',
      imageKey: 'log-rack',
      options: [
        'Keep the aisle clear',
        'Stack boxes in the walkway',
        'Park the jack across the path',
        'Ignore spills on the floor',
      ],
      supportHint: hint(
        'Keep the aisle clear.',
        'Mantén el pasillo despejado.',
        'Abqi al-mamarr wafihan.',
        'Aisle clear rakho.',
        'Mengedun kefitu yadrigu.',
        'Mengedi kefitu yegberu.',
      ),
    },
  ],
  sitePhrases: [
    {
      en: 'Scan before you stage.',
      why: 'Accuracy before placement — wrong bay costs time and inventory.',
      prompt: 'What does this phrase mean?',
      answer: 'Scan the label before you place the item',
      options: [
        'Scan the label before you place the item',
        'Place first, scan later',
        'Skip scanning if you are busy',
        'Mark it by hand only',
      ],
    },
    {
      en: 'Watch the forklift path.',
      why: 'Powered equipment always gets space. Stay clear — you are not certified to operate it here.',
      prompt: 'What should you do?',
      answer: 'Stay clear of moving equipment',
      options: [
        'Stay clear of moving equipment',
        'Stand behind it closely',
        'Wave it to speed up',
        'Remove your vest to hear better',
      ],
    },
    {
      en: 'Keep the aisle clear.',
      why: 'People and machines need a safe path. Blocked aisles cause collisions.',
      prompt: 'What does this phrase mean?',
      answer: 'Do not block the walkway',
      options: [
        'Do not block the walkway',
        'Stack boxes in the aisle',
        'Park across the path',
        'Leave litter on the floor',
      ],
    },
    {
      en: 'Stage it in bay three.',
      why: 'Short placement direction you will hear every shift.',
      prompt: 'What should you do?',
      answer: 'Put it in bay three for now',
      options: [
        'Put it in bay three for now',
        'Throw it away',
        'Take it home',
        'Ignore the order',
      ],
    },
    {
      en: 'Count against the manifest.',
      why: 'Receiving accuracy starts with a real count, not a guess.',
      prompt: 'What does this phrase mean?',
      answer: 'Check each item against the shipment list',
      options: [
        'Check each item against the shipment list',
        'Sign without looking',
        'Count only the top layer',
        'Skip damaged cartons',
      ],
    },
    {
      en: 'Report OS and D right away.',
      why: 'Overage, shortage, or damage must be escalated before goods move further.',
      prompt: 'What should you do?',
      answer: 'Tell a supervisor about overage, shortage, or damage',
      options: [
        'Tell a supervisor about overage, shortage, or damage',
        'Hide the shortage and keep going',
        'Change the label yourself',
        'Ship damaged goods without a note',
      ],
    },
    {
      en: 'Wrap before you ship.',
      why: 'Unsecured loads shift, tip, and injure people.',
      prompt: 'What does this phrase mean?',
      answer: 'Secure the pallet with stretch wrap before shipping',
      options: [
        'Secure the pallet with stretch wrap before shipping',
        'Ship the loose stack as-is',
        'Tape one corner only',
        'Wrap after the truck leaves',
      ],
    },
    {
      en: 'Two-person lift on that carton.',
      why: 'Team lifts prevent injury and product damage.',
      prompt: 'What should you do?',
      answer: 'Lift the carton with a partner',
      options: [
        'Lift the carton with a partner',
        'Drag it alone across the floor',
        'Throw it from the dock',
        'Ask a visitor to carry it alone',
      ],
    },
    {
      en: 'Tag that damaged pallet out.',
      why: 'Damaged product or equipment leaves the flow until someone decides next steps.',
      prompt: 'What happens to the damaged pallet?',
      answer: 'It is tagged and taken out of use',
      options: [
        'It is tagged and taken out of use',
        'You keep shipping it carefully',
        'You hide it behind the rack',
        'You give it to a new learner',
      ],
    },
    {
      en: 'Report near misses the same day.',
      why: 'Near misses teach the floor before someone gets hurt.',
      prompt: 'When should you report a near miss?',
      answer: 'The same day it happens',
      options: [
        'The same day it happens',
        'Only if someone is injured',
        'Next month in a meeting',
        'Never. Near misses do not count',
      ],
    },
  ],
  safetyQuiz: [
    {
      id: 'ls1',
      prompt: 'Look at this gear. What must you wear before entering the warehouse floor?',
      emoji: 'SV',
      imageKey: 'log-vest',
      options: ['Safety vest / required PPE', 'Sandals', 'Loose scarf only', 'Nothing'],
      answer: 'Safety vest / required PPE',
      teachCorrect: 'Bright vest and required PPE on before you cross onto the floor.',
      teachWrong: 'Safety vest / required PPE first — people and drivers must see you.',
    },
    {
      id: 'ls2',
      prompt: 'A forklift is moving toward your aisle. What do you do?',
      emoji: 'FK',
      options: [
        'Step clear, make eye contact, wait for a clear path',
        'Walk behind it closely',
        'Wave it to speed up',
        'Stand in the path to save time',
      ],
      answer: 'Step clear, make eye contact, wait for a clear path',
      teachCorrect: 'Pedestrians yield to powered equipment. Stay clear — forklift operation needs separate certification.',
      teachWrong: 'Never stand in a forklift path. Give equipment space and confirm the driver sees you.',
    },
    {
      id: 'ls3',
      prompt: 'You see a spill in the aisle. First action?',
      emoji: 'SP',
      options: [
        'Stop work in that area, report it, keep people clear',
        'Walk through it',
        'Cover it with cardboard and leave',
        'Ignore it if traffic is light',
      ],
      answer: 'Stop work in that area, report it, keep people clear',
      teachCorrect: 'Spills cause falls. Stop, control the area, and report — that is stop-work competence.',
      teachWrong: 'Do not walk through or hide a spill. Report and control it immediately.',
    },
    {
      id: 'ls4',
      prompt: 'Where do heavy boxes belong when moving them?',
      emoji: 'HT',
      imageKey: 'log-dolly',
      options: [
        'On a hand truck, pallet jack, or approved cart',
        'Balanced on your head',
        'Dragged across the floor',
        'Stacked past your eyesight while walking',
      ],
      answer: 'On a hand truck, pallet jack, or approved cart',
      teachCorrect: 'Use the right handling tool. Protect your back and the product.',
      teachWrong: 'Hand truck, pallet jack, or approved cart — not overloaded free-hand carries.',
    },
    {
      id: 'ls5',
      prompt: 'Someone is hurt on the floor. What is your first job?',
      emoji: 'EM',
      imageKey: 'log-vest',
      options: [
        'Call for help / follow emergency steps',
        'Keep picking to hit the rate',
        'Move heavy equipment alone',
        'Film the scene first',
      ],
      answer: 'Call for help / follow emergency steps',
      teachCorrect: 'Get help first. People before production.',
      teachWrong: 'In an emergency, follow the warehouse plan and get help right away.',
    },
    {
      id: 'ls6',
      prompt: 'Who can tell you to stop work if something looks unsafe?',
      emoji: '!',
      imageKey: 'log-vest',
      options: [
        'You. Every worker has stop-work authority',
        'Only the warehouse owner',
        'Only after an injury',
        'Nobody. Keep producing',
      ],
      answer: 'You. Every worker has stop-work authority',
      teachCorrect: 'Stop-work authority belongs to every worker on the floor.',
      teachWrong: 'If it looks unsafe, you can and should stop the work.',
    },
    {
      id: 'ls7',
      prompt: 'Eye protection is required when…',
      emoji: 'EP',
      options: [
        'Cutting bands, wrapping under tension, or any task with flying debris',
        'Only outdoors',
        'Only if the supervisor is nearby',
        'Never near stretch wrap',
      ],
      answer: 'Cutting bands, wrapping under tension, or any task with flying debris',
      teachCorrect: 'Protect your eyes whenever particles, straps, or wrap can snap or fly.',
      teachWrong: 'Eye protection is for banding, debris, and similar warehouse tasks.',
    },
  ],
  toolCategories: [
    {
      title: 'Manual handling tools',
      why: 'Hand trucks, carts, and manual pallet jacks you push or pull with your body.',
      mark: 'MH',
      prompt: 'Hand trucks and manual pallet jacks belong to which group?',
      answer: 'Manual handling tools',
      options: ['Manual handling tools', 'Powered equipment', 'Packaging materials', 'Scanning devices'],
    },
    {
      title: 'Powered equipment',
      why: 'Forklifts and powered lifts need certified training. Learners stay clear — awareness only.',
      mark: 'PE',
      prompt: 'Forklifts belong to which group?',
      answer: 'Powered equipment',
      options: ['Packaging materials', 'Powered equipment', 'Manual handling tools', 'Paperwork'],
    },
    {
      title: 'Packaging materials',
      why: 'Pallets, stretch wrap, and cartons protect goods in motion.',
      mark: 'PK',
      prompt: 'Pallets and stretch wrap belong to which group?',
      answer: 'Packaging materials',
      options: ['Scanning devices', 'Powered equipment', 'Packaging materials', 'Floor markings'],
    },
    {
      title: 'Scanning devices',
      why: 'Scanners and label printers keep inventory and shipping accurate.',
      mark: 'SD',
      prompt: 'Barcode scanners belong to which group?',
      answer: 'Scanning devices',
      options: ['Manual handling tools', 'Packaging materials', 'Scanning devices', 'Powered equipment'],
    },
  ],
  systemTopics: [
    {
      title: 'Receiving',
      why: 'Goods arrive, get checked against the manifest, and enter inventory.',
      mark: 'RC',
      prompt: 'Checking inbound goods against the manifest is part of…',
      answer: 'Receiving',
      options: ['Receiving', 'Shipping', 'Returns', 'Inventory counts'],
    },
    {
      title: 'Put-away/storage',
      why: 'Move received goods to the correct rack location so the system stays true.',
      mark: 'PA',
      prompt: 'Placing goods into the right rack location is…',
      answer: 'Put-away/storage',
      options: ['Shipping', 'Put-away/storage', 'Returns', 'Cycle count'],
    },
    {
      title: 'Picking/order processing',
      why: 'Collect ordered items accurately and on time for outbound orders.',
      mark: 'PK',
      prompt: 'Collecting items for an order is…',
      answer: 'Picking/order processing',
      options: ['Receiving', 'Picking/order processing', 'Staging only', 'Returns'],
    },
    {
      title: 'Packaging & shipping',
      why: 'Wrap, label, stage, load, and send outbound orders safely.',
      mark: 'SH',
      prompt: 'Wrapping, labeling, and loading a truck for delivery is part of…',
      answer: 'Packaging & shipping',
      options: ['Put-away/storage', 'Receiving', 'Packaging & shipping', 'Inventory counts'],
    },
    {
      title: 'Inventory accuracy',
      why: 'Counts, scans, and OS&D reports keep the system matched to the floor.',
      mark: 'IA',
      prompt: 'Scan-and-count checks and OS&D reports support…',
      answer: 'Inventory accuracy',
      options: ['Inventory accuracy', 'Break schedules', 'Parking rules', 'Uniforms'],
    },
  ],
  observationScenarios: [
    {
      id: 'vest-entry',
      title: 'Safety vest before entry',
      situation: 'Your supervisor asks you to enter the warehouse floor ready for work.',
      skill: 'Safety vest check',
      steps: [
        { id: 'vest', label: 'Safety vest on and visible', correctOrder: 1 },
        { id: 'shoes', label: 'Closed footwear confirmed', correctOrder: 2 },
        { id: 'path', label: 'Check the aisle is clear of equipment', correctOrder: 3 },
        { id: 'enter', label: 'Enter the floor only after gear is ready', correctOrder: 4 },
      ],
      passNote: 'Competent means gear is correct BEFORE you cross the line, every time.',
    },
    {
      id: 'scan-stage',
      title: 'Scan before you stage',
      situation: 'Your supervisor watches you prepare a package for staging.',
      skill: 'Scanner',
      steps: [
        { id: 'read', label: 'Read the shipping label', correctOrder: 1 },
        { id: 'scan', label: 'Scan the barcode and wait for confirmation', correctOrder: 2 },
        { id: 'match', label: 'Match the screen to the destination bay', correctOrder: 3 },
        { id: 'stage', label: 'Stage the package in the correct bay', correctOrder: 4 },
      ],
      passNote: 'Scan first. Stage second. Accuracy beats speed.',
    },
    {
      id: 'pallet-load',
      title: 'Build and secure a stable pallet',
      situation: 'Your supervisor asks you to show a safe pallet build ready for shipping.',
      skill: 'Pallet & stretch wrap',
      steps: [
        { id: 'base', label: 'Start with a sound, flat pallet', correctOrder: 1 },
        { id: 'stack', label: 'Stack boxes evenly with no overhang', correctOrder: 2 },
        { id: 'wrap', label: 'Secure the load with stretch wrap as trained', correctOrder: 3 },
        { id: 'report', label: 'Tell the supervisor the load is ready', correctOrder: 4 },
      ],
      passNote: 'Stable, wrapped loads protect people and product.',
    },
    {
      id: 'dolly-pass',
      title: 'Move a load with a hand truck',
      situation: 'Your supervisor asks you to move heavy boxes safely across a busy aisle.',
      skill: 'Hand truck',
      steps: [
        { id: 'clear', label: 'Clear the path ahead', correctOrder: 1 },
        { id: 'load', label: 'Load the hand truck with a balanced stack', correctOrder: 2 },
        { id: 'tilt', label: 'Tilt back carefully and walk steady', correctOrder: 3 },
        { id: 'set', label: 'Set down gently and park the truck clear of the aisle', correctOrder: 4 },
      ],
      passNote: 'Never rush a load through a busy aisle. Path clear, then move.',
    },
    {
      id: 'receive-osd',
      title: 'Receive against the manifest',
      situation: 'Your supervisor watches you check an inbound shipment.',
      skill: 'Receiving / OS&D',
      steps: [
        { id: 'list', label: 'Open the manifest and identify expected items', correctOrder: 1 },
        { id: 'count', label: 'Count each carton against the list', correctOrder: 2 },
        { id: 'inspect', label: 'Inspect for overage, shortage, or damage (OS&D)', correctOrder: 3 },
        { id: 'escalate', label: 'Report OS&D to the supervisor before put-away', correctOrder: 4 },
      ],
      passNote: 'Competent receiving means count, inspect, and escalate OS&D — never force a mismatch through.',
    },
  ],
  siteDecisions: [
    {
      id: 'spill',
      title: 'Aisle spill',
      scene: 'You arrive on the floor. There is liquid in the main aisle.',
      prompt: 'What should you do first?',
      options: [
        'Report it / make the area safe',
        'Walk through and keep working',
        'Cover it and leave',
        'Film it for social media',
      ],
      answer: 'Report it / make the area safe',
      teachCorrect: 'See something unsafe, speak up and make it safe. People before production.',
      teachWrong: 'Hazards get reported and controlled first, never ignored.',
    },
    {
      id: 'direction',
      title: 'Supervisor direction',
      scene: 'Your supervisor says: “Stage the pallet in bay two.”',
      prompt: 'What do you do?',
      options: [
        'Stage the pallet in bay two',
        'Put it wherever is closest',
        'Leave it in the aisle',
        'Ask a friend to guess',
      ],
      answer: 'Stage the pallet in bay two',
      teachCorrect: 'Listen fully, then do exactly what was asked. Confirm the bay if unsure.',
      teachWrong: 'Bay two means bay two. Follow the short English direction.',
    },
    {
      id: 'forklift',
      title: 'Moving equipment',
      scene: 'A forklift is reversing near your pick path.',
      prompt: 'Best action?',
      options: [
        'Stop, make eye contact, wait for a clear path',
        'Squeeze past behind it',
        'Tap the machine to hurry',
        'Jog across the path',
      ],
      answer: 'Stop, make eye contact, wait for a clear path',
      teachCorrect: 'People yield to powered equipment until the path is clear. Stay clear — forklifts need certified operators.',
      teachWrong: 'Never assume the driver sees you. Stop and wait.',
    },
    {
      id: 'mismatch',
      title: 'Label mismatch / OS&D',
      scene: 'The shipping label, the screen destination, and the carton count do not match the manifest.',
      prompt: 'What should you do?',
      options: [
        'Stop and ask a supervisor before staging (report OS&D)',
        'Ship it anyway to save time',
        'Change the label yourself',
        'Hide the package behind the rack',
      ],
      answer: 'Stop and ask a supervisor before staging (report OS&D)',
      teachCorrect: 'Overage, shortage, or damage (OS&D) gets escalated — never forced through.',
      teachWrong: 'Do not stage a mismatch. Report OS&D and wait for direction.',
    },
    {
      id: 'missing-vest',
      title: 'Missing vest',
      scene: 'You left your safety vest in the break room. The floor is ready.',
      prompt: 'Best next step?',
      options: [
        'Get your safety vest before entering',
        'Enter quickly without it',
        'Borrow a torn vest that does not fit',
        'Wait until someone notices',
      ],
      answer: 'Get your safety vest before entering',
      teachCorrect: 'No vest → no entry. Fix gear first.',
      teachWrong: 'Never enter the warehouse floor without required high-visibility gear.',
    },
    {
      id: 'log',
      title: 'End-of-day note',
      scene: 'You finished receiving two pallets and staging three orders. Your supervisor was Jordan.',
      prompt: 'What belongs in today’s floor log?',
      options: [
        'Date, tasks you did, and supervisor name',
        'Only your lunch order',
        'Someone else’s private phone number',
        'Nothing. Logs are optional forever',
      ],
      answer: 'Date, tasks you did, and supervisor name',
      teachCorrect: 'Clear daily notes help instructors and employers trust your hours.',
      teachWrong: 'A good log has the date, real tasks, and who supervised you.',
    },
    {
      id: 'visitor',
      title: 'Visitor without vest',
      scene: 'A delivery driver walks toward the floor without a safety vest.',
      prompt: 'What should you do?',
      options: [
        'Stop them at the line and get them a vest or an escort',
        'Wave them through quickly',
        'Lend them a torn vest',
        'Ignore it. Visitors are not your job',
      ],
      answer: 'Stop them at the line and get them a vest or an escort',
      teachCorrect: 'Everyone crossing the line needs the right gear or a proper escort.',
      teachWrong: 'No vest, no entry. Help them get safe before they enter.',
    },
  ],
  finalQuiz: [
    {
      id: 'lf1',
      prompt: 'Safety: Look at this gear. When do you put on your safety vest?',
      emoji: 'SV',
      imageKey: 'log-vest',
      options: ['Before you enter the floor', 'After the first pick', 'Only if the boss is watching', 'Never indoors'],
      answer: 'Before you enter the floor',
      teachCorrect: 'Safety vest before entry, every time.',
      teachWrong: 'Vest and required PPE are on before you cross onto the floor.',
    },
    {
      id: 'lf2',
      prompt: 'Language: “Scan before you stage” means…',
      emoji: 'SC',
      imageKey: 'log-scanner',
      options: [
        'Scan the label before you place the item',
        'Stage first, scan later',
        'Skip scanning',
        'Ask a friend to guess the bay',
      ],
      answer: 'Scan the label before you place the item',
      teachCorrect: 'Scan first. Stage second. Accuracy beats speed.',
      teachWrong: 'Always scan and confirm before you stage.',
    },
    {
      id: 'lf3',
      prompt: 'Systems: Collecting items for an order is called…',
      emoji: 'PK',
      options: ['Picking/order processing', 'Receiving', 'Put-away/storage', 'Break'],
      answer: 'Picking/order processing',
      teachCorrect: 'Picking / order processing collects ordered items accurately.',
      teachWrong: 'Picking is collecting for an order — part of the MSSC flow.',
    },
    {
      id: 'lf4',
      prompt: 'Equipment: Which device reads barcodes?',
      emoji: 'SC',
      imageKey: 'log-scanner',
      options: ['Scanner', 'Pallet', 'Hand truck', 'Storage rack'],
      answer: 'Scanner',
      teachCorrect: 'The scanner reads barcodes and confirms the screen.',
      teachWrong: 'Use a scanner for barcodes — then confirm before you stage.',
    },
    {
      id: 'lf5',
      prompt: 'Safety: If a spill blocks an aisle, you should…',
      emoji: 'SP',
      options: [
        'Stop, report it, and make the area safe',
        'Ignore it',
        'Run through it',
        'Blame a coworker',
      ],
      answer: 'Stop, report it, and make the area safe',
      teachCorrect: 'Control hazards first. That is stop-work competence.',
      teachWrong: 'Report and control spills immediately — do not walk through them.',
    },
    {
      id: 'lf6',
      prompt: 'Judgment: Label and count do not match the manifest. Best action?',
      emoji: 'MF',
      imageKey: 'log-manifest',
      options: [
        'Stop and report OS&D to a supervisor',
        'Ship it to hit the rate',
        'Change the label yourself',
        'Hide the shortage',
      ],
      answer: 'Stop and report OS&D to a supervisor',
      teachCorrect: 'Overage, shortage, or damage (OS&D) is escalated before put-away or ship.',
      teachWrong: 'Never force a mismatch through. Report OS&D.',
    },
    {
      id: 'lf7',
      prompt: 'Equipment: Forklifts are…',
      emoji: 'PE',
      options: [
        'Powered equipment — stay clear unless you are certified',
        'The same as a hand truck',
        'Safe for anyone to drive on day one',
        'Packaging materials',
      ],
      answer: 'Powered equipment — stay clear unless you are certified',
      teachCorrect: 'Forklifts need certified operators. This course teaches awareness and stay-clear habits only.',
      teachWrong: 'Do not claim forklift skill here — stay clear and yield to powered equipment.',
    },
    {
      id: 'lf8',
      prompt: 'Systems: Placing received goods into the correct rack is…',
      emoji: 'PA',
      imageKey: 'log-rack',
      options: ['Put-away/storage', 'Picking/order processing', 'Packaging & shipping', 'Receiving only'],
      answer: 'Put-away/storage',
      teachCorrect: 'Put-away / storage moves checked goods to the right location.',
      teachWrong: 'After receiving, put-away places goods in the assigned rack.',
    },
  ],
  employmentPrep: [
    {
      id: 'log-intro',
      prompt: 'An employer asks: “Why Purpose Academy?” Best answer?',
      options: [
        'I learned logistics foundations, safety, and workplace English with instructors who checked my skills',
        'I watched a few videos once',
        'I do not need safety training',
        'I only want a paycheck with no learning',
      ],
      answer: 'I learned logistics foundations, safety, and workplace English with instructors who checked my skills',
      teachCorrect: 'Connect your training to safety, language, and verified skill.',
      teachWrong: 'Employers want proof of foundations, not shortcuts.',
    },
    {
      id: 'log-safety',
      prompt: 'Interview question: “What do you put on before entering the warehouse floor?”',
      options: [
        'Safety vest and required gear',
        'Headphones only',
        'Nothing special',
        'Open-toe shoes',
      ],
      answer: 'Safety vest and required gear',
      teachCorrect: 'Lead with safety. It shows you are floor-ready.',
      teachWrong: 'Always name safety vest / required gear before entry.',
    },
    {
      id: 'log-team',
      prompt: 'A partner says: “Scan that label.” You should…',
      options: [
        'Scan the label and confirm the screen',
        'Guess the destination',
        'Ignore the request',
        'Throw the scanner',
      ],
      answer: 'Scan the label and confirm the screen',
      teachCorrect: 'Short workplace talk + accurate scanning = good teammate.',
      teachWrong: 'Scan carefully. Confirm before you stage.',
    },
    {
      id: 'log-learn',
      prompt: 'An employer asks how you learn new tasks. Best answer?',
      options: [
        'I listen, practise with an instructor, and ask when I am unsure',
        'I guess and hope nobody notices',
        'I refuse to learn English for the job',
        'I skip safety if it slows me down',
      ],
      answer: 'I listen, practise with an instructor, and ask when I am unsure',
      teachCorrect: 'Employers hire people who learn carefully and ask good questions.',
      teachWrong: 'Show that you practise with guidance and ask when unsure.',
    },
    {
      id: 'log-schedule',
      prompt: 'A partner asks if you can start at 7:00 a.m. You should…',
      options: [
        'Give an honest answer about your availability',
        'Say yes to everything even if you cannot come',
        'Ignore the message',
        'Ask them to text your password',
      ],
      answer: 'Give an honest answer about your availability',
      teachCorrect: 'Clear, honest scheduling builds trust.',
      teachWrong: 'Be honest about when you can start work.',
    },
    {
      id: 'log-ready',
      prompt: 'You arrive for a warehouse walk-through. Best first move?',
      options: [
        'Bring and wear required safety gear',
        'Wear sandals for comfort',
        'Leave PPE in the car',
        'Arrive without confirming the meeting place',
      ],
      answer: 'Bring and wear required safety gear',
      teachCorrect: 'Show up ready: gear on, professional, on time.',
      teachWrong: 'Bring PPE and be ready for the floor walk.',
    },
  ],
  unitCheckpoints: {
    3: [
      {
        id: 'uc3-l1',
        prompt: 'Which device reads barcodes?',
        emoji: 'SC',
        imageKey: 'log-scanner',
        options: ['Scanner', 'Pallet', 'Safety vest', 'Hand truck'],
        answer: 'Scanner',
        teachCorrect: 'Scanner reads barcodes and confirms the screen.',
        teachWrong: 'The scanner reads barcodes — then you confirm before staging.',
      },
      {
        id: 'uc3-l2',
        prompt: 'What must you wear before entering the floor?',
        emoji: 'SV',
        imageKey: 'log-vest',
        options: ['Safety vest / required PPE', 'Sandals', 'Nothing', 'Loose scarf only'],
        answer: 'Safety vest / required PPE',
        teachCorrect: 'Vest and required PPE on before entry.',
        teachWrong: 'Wear a safety vest first — visibility is a duty.',
      },
      {
        id: 'uc3-l3',
        prompt: 'Heavy boxes should move on a…',
        emoji: 'HT',
        imageKey: 'log-dolly',
        options: [
          'Hand truck or pallet jack',
          'Your head',
          'Open hands only while running',
          'The forklift forks while standing on them',
        ],
        answer: 'Hand truck or pallet jack',
        teachCorrect: 'Use a hand truck or pallet jack for heavy loads.',
        teachWrong: 'Manual handling tools for heavy boxes — never climb forks.',
      },
    ],
    4: [
      {
        id: 'uc4-l1',
        prompt: '“Scan before you stage” means…',
        emoji: 'SC',
        imageKey: 'log-scanner',
        options: [
          'Scan the label before you place the item',
          'Place first',
          'Never scan',
          'Ask a friend to guess',
        ],
        answer: 'Scan the label before you place the item',
        teachCorrect: 'Scan first, then stage.',
        teachWrong: 'Scan and confirm before staging.',
      },
      {
        id: 'uc4-l2',
        prompt: 'Keep the aisle clear means…',
        emoji: 'AL',
        imageKey: 'log-rack',
        options: [
          'Do not block the walkway',
          'Stack boxes in the aisle',
          'Park across the path',
          'Leave spills',
        ],
        answer: 'Do not block the walkway',
        teachCorrect: 'Aisles stay clear for people and equipment.',
        teachWrong: 'Do not block walkways or park tools in the path.',
      },
      {
        id: 'uc4-l3',
        prompt: 'Find-the-object practice (Eye Spy) proves you can…',
        emoji: 'PJ',
        imageKey: 'log-jack',
        options: [
          'Spot the real object among others',
          'Skip English forever',
          'Ignore safety gear',
          'Guess without looking',
        ],
        answer: 'Spot the real object among others',
        teachCorrect: 'You identify warehouse objects in a busy scene.',
        teachWrong: 'Eye Spy is about finding the named object.',
      },
      {
        id: 'uc4-l4',
        prompt: 'A workplace instruction is…',
        emoji: 'MF',
        imageKey: 'log-manifest',
        options: [
          'A short English direction you must follow',
          'A song lyric',
          'Optional small talk',
          'Only for supervisors',
        ],
        answer: 'A short English direction you must follow',
        teachCorrect: 'Instructions keep the floor safe and coordinated.',
        teachWrong: 'Follow short English directions on the warehouse floor.',
      },
    ],
    5: [
      {
        id: 'uc5-l1',
        prompt: 'Receiving is when goods…',
        emoji: 'RC',
        imageKey: 'log-manifest',
        options: [
          'Arrive and get checked against the manifest',
          'Leave on a truck only',
          'Are thrown away',
          'Skip inventory',
        ],
        answer: 'Arrive and get checked against the manifest',
        teachCorrect: 'Receiving checks inbound goods and notes OS&D.',
        teachWrong: 'Receiving is inbound check-in against the list.',
      },
      {
        id: 'uc5-l2',
        prompt: 'Forklifts belong to…',
        emoji: 'PE',
        options: [
          'Powered equipment (awareness / stay clear)',
          'Packaging materials',
          'Paperwork',
          'Break rooms',
        ],
        answer: 'Powered equipment (awareness / stay clear)',
        teachCorrect: 'Forklifts are powered equipment. Stay clear unless certified elsewhere.',
        teachWrong: 'Powered equipment needs certified training — this course teaches stay-clear habits.',
      },
      {
        id: 'uc5-l3',
        prompt: 'Stop-work authority means…',
        emoji: '!',
        imageKey: 'log-vest',
        options: [
          'Any worker can stop unsafe work',
          'Only owners can stop work',
          'Never stop for hazards',
          'Stop only after an injury',
        ],
        answer: 'Any worker can stop unsafe work',
        teachCorrect: 'Everyone can stop unsafe work on the floor.',
        teachWrong: 'You can stop work when something looks unsafe.',
      },
    ],
    6: [
      {
        id: 'uc6-l1',
        prompt: 'Competent observation means…',
        emoji: 'O',
        imageKey: 'log-vest',
        options: [
          'You show the skill correctly for an instructor',
          'You watched a video once',
          'You skipped your vest',
          'You guessed the steps',
        ],
        answer: 'You show the skill correctly for an instructor',
        teachCorrect: 'Observation proves real skill under review.',
        teachWrong: 'Show the correct ordered steps for the instructor.',
      },
      {
        id: 'uc6-l2',
        prompt: 'A good floor log includes…',
        emoji: 'L',
        imageKey: 'log-manifest',
        options: [
          'Date, tasks, and supervisor',
          'Only memes',
          'Other people’s passwords',
          'Nothing useful',
        ],
        answer: 'Date, tasks, and supervisor',
        teachCorrect: 'Clear notes build trust.',
        teachWrong: 'Log date, tasks, and who supervised you.',
      },
      {
        id: 'uc6-l3',
        prompt: 'In an interview, lead with…',
        emoji: 'P',
        imageKey: 'log-vest',
        options: [
          'Safety, foundations, and verified skills',
          'Skipping training',
          'Avoiding English',
          'Claiming forklift certification from this course',
        ],
        answer: 'Safety, foundations, and verified skills',
        teachCorrect: 'Employers want safety and proof of skill — not fake certifications.',
        teachWrong: 'Talk about safety and what you can do. Do not claim forklift certification here.',
      },
    ],
  },
}
