import type { PathwayPack } from '../types'
import { gloss, hint } from '../packHelpers'

/**
 * Logistics Foundations content pack.
 * Same progression skeleton as Construction — warehouse / materials-flow imagery and language.
 */
export const logisticsPack: PathwayPack = {
  id: 'logistics',
  skillDomains: {
    vocabulary: 'Vocabulary',
    safety: 'Safety',
    tools: 'Equipment',
    systems: 'Logistics skills',
  },
  unitGoals: {
    3: {
      goal: 'Learn the Level-1 warehouse words you will hear on an Alberta logistics floor.',
      outcomes: ['See each object and hear English', 'Connect the English word to the real action'],
    },
    4: {
      goal: 'Use English with support, then prove you can find and follow warehouse language.',
      outcomes: [
        'Match pictures to English words',
        'Find objects in a busy bay',
        'Follow short workplace instructions',
        'Understand common warehouse phrases',
      ],
    },
    5: {
      goal: 'Build the digital, safety, equipment, and systems foundations every warehouse expects.',
      outcomes: [
        'Practice school computer tasks',
        'Pass required safety checks',
        'Name equipment groups and logistics systems',
      ],
    },
    6: {
      goal: 'Prove readiness under observation, then connect to logistics employment support.',
      outcomes: [
        'Rehearse competent skill order',
        'Make safe floor decisions',
        'Pass the final checks and open employment support',
      ],
    },
  },
  stepTitles: {
    12: {
      title: 'Warehouse Language',
      help: 'Hear a warehouse phrase. Choose what it means.',
      purpose: 'Useful English you will hear in Alberta logistics workplaces.',
    },
    15: {
      title: 'Equipment & Materials',
      help: 'Learn each equipment group. Answer one check.',
      purpose: 'Safe naming before safe use with an instructor.',
    },
    16: {
      title: 'Logistics Systems',
      help: 'Learn each system. Answer one check.',
      purpose: 'Your task keeps goods moving safely and on time.',
    },
    18: {
      title: 'Warehouse Floor Training',
      help: 'Make floor decisions and log the day like a real team member.',
      purpose: 'Daily judgment, notes, and supervisor feedback.',
    },
  },
  vocab: [
    {
      id: 'pallet',
      english: 'Pallet',
      emoji: 'PL',
      imageKey: 'log-pallet',
      definition: 'A flat platform used to stack and move goods.',
      sentence: 'Load the boxes onto the pallet.',
      gloss: gloss('Paleta', 'Tabiq naqil', 'Palette', 'Palette', 'Palette'),
    },
    {
      id: 'scanner',
      english: 'Scanner',
      emoji: 'SC',
      imageKey: 'log-scanner',
      definition: 'A device that reads barcodes on labels.',
      sentence: 'Scan the label with the scanner.',
      gloss: gloss('Escaner', 'Masah', 'Scanner', 'Scanner', 'Scanner'),
    },
    {
      id: 'label',
      english: 'Shipping label',
      emoji: 'LB',
      imageKey: 'log-label',
      definition: 'A sticker that shows where a package must go.',
      sentence: 'Check the shipping label before you move the box.',
      gloss: gloss('Etiqueta de envio', 'Bitagat shahn', 'Shipping label', 'Shipping label', 'Shipping label'),
    },
    {
      id: 'vest',
      english: 'Safety vest',
      emoji: 'SV',
      imageKey: 'log-vest',
      definition: 'A bright vest that helps people see you.',
      sentence: 'Put on your safety vest before you enter the floor.',
      gloss: gloss('Chaleco de seguridad', 'Sitra amn', 'Safety vest', 'Safety vest', 'Safety vest'),
    },
    {
      id: 'dolly',
      english: 'Hand truck',
      emoji: 'HT',
      imageKey: 'log-dolly',
      definition: 'A two-wheel cart for moving heavy boxes.',
      sentence: 'Use the hand truck for the heavy boxes.',
      gloss: gloss('Carretilla', 'Arabat yad', 'Hand truck', 'Hand truck', 'Hand truck'),
    },
    {
      id: 'manifest',
      english: 'Manifest',
      emoji: 'MF',
      imageKey: 'log-manifest',
      definition: 'A list of what is on a shipment or truck.',
      sentence: 'Check the manifest before loading.',
      gloss: gloss('Manifiesto', 'Qaimat shahn', 'Manifest', 'Manifest', 'Manifest'),
    },
    {
      id: 'rack',
      english: 'Storage rack',
      emoji: 'RK',
      imageKey: 'log-rack',
      definition: 'Shelving used to store pallets and goods.',
      sentence: 'Place the pallet on the storage rack.',
      gloss: gloss('Estanteria', 'Raf takhzin', 'Storage rack', 'Storage rack', 'Storage rack'),
    },
  ],
  wordActions: [
    {
      id: 'wa-pallet',
      termId: 'pallet',
      title: 'Pallet in action',
      body: 'Stack boxes evenly on the pallet. Keep weight balanced.',
      actionCue: 'Even stack. Balanced load. Corners clear.',
    },
    {
      id: 'wa-scanner',
      termId: 'scanner',
      title: 'Scanner in action',
      body: 'Aim the scanner at the barcode. Wait for the beep.',
      actionCue: 'Aim. Beep. Confirm the screen.',
    },
    {
      id: 'wa-label',
      termId: 'label',
      title: 'Shipping label in action',
      body: 'Read the destination before you move the package.',
      actionCue: 'Read the label. Match the bay. Then move.',
    },
    {
      id: 'wa-vest',
      termId: 'vest',
      title: 'Safety vest before entry',
      body: 'Put the bright vest on before you cross onto the floor.',
      actionCue: 'Vest on before you enter.',
    },
    {
      id: 'wa-dolly',
      termId: 'dolly',
      title: 'Hand truck in action',
      body: 'Tilt the load back carefully. Walk at a steady pace.',
      actionCue: 'Tilt. Steady walk. Clear path.',
    },
    {
      id: 'wa-manifest',
      termId: 'manifest',
      title: 'Manifest check',
      body: 'Count items against the list before the truck leaves.',
      actionCue: 'Count. Match the list. Sign only when sure.',
    },
    {
      id: 'wa-rack',
      termId: 'rack',
      title: 'Storage rack in action',
      body: 'Place the pallet squarely. Never climb the rack.',
      actionCue: 'Square place. No climbing. Hands clear.',
    },
  ],
  eyeSpyScenes: [
    {
      id: 'bay-a-scanner',
      title: 'Receiving bay A',
      instruction: 'Find the scanner. Tap it in the scene, then confirm the English name.',
      targetId: 'scanner',
      distractors: ['Pallet', 'Safety vest', 'Hand truck'],
      variantGroup: 'bay-scanner',
      hotspots: [
        { id: 'scanner', label: 'Scanner', answer: 'Scanner', imageKey: 'log-scanner', x: 14, y: 40, w: 22, h: 28 },
        { id: 'pallet', label: 'Pallet', answer: 'Pallet', imageKey: 'log-pallet', x: 55, y: 50, w: 28, h: 26 },
        { id: 'vest', label: 'Safety vest', answer: 'Safety vest', imageKey: 'log-vest', x: 40, y: 12, w: 20, h: 24 },
        { id: 'dolly', label: 'Hand truck', answer: 'Hand truck', imageKey: 'log-dolly', x: 72, y: 30, w: 20, h: 30 },
      ],
    },
    {
      id: 'bay-b-scanner',
      title: 'Receiving bay B',
      instruction: 'Find the scanner. Tap it in the scene, then confirm the English name.',
      targetId: 'scanner',
      distractors: ['Shipping label', 'Manifest', 'Storage rack'],
      variantGroup: 'bay-scanner',
      hotspots: [
        { id: 'label', label: 'Shipping label', answer: 'Shipping label', imageKey: 'log-label', x: 10, y: 18, w: 22, h: 22 },
        { id: 'scanner', label: 'Scanner', answer: 'Scanner', imageKey: 'log-scanner', x: 58, y: 42, w: 22, h: 28 },
        { id: 'manifest', label: 'Manifest', answer: 'Manifest', imageKey: 'log-manifest', x: 36, y: 55, w: 22, h: 24 },
        { id: 'rack', label: 'Storage rack', answer: 'Storage rack', imageKey: 'log-rack', x: 74, y: 12, w: 20, h: 30 },
      ],
    },
    {
      id: 'floor-a-vest',
      title: 'Floor walk A',
      instruction: 'Find the safety vest. Tap it in the scene, then confirm the English name.',
      targetId: 'vest',
      distractors: ['Pallet', 'Hand truck', 'Scanner'],
      variantGroup: 'floor-vest',
      hotspots: [
        { id: 'vest', label: 'Safety vest', answer: 'Safety vest', imageKey: 'log-vest', x: 20, y: 20, w: 22, h: 28 },
        { id: 'pallet', label: 'Pallet', answer: 'Pallet', imageKey: 'log-pallet', x: 55, y: 55, w: 28, h: 24 },
        { id: 'dolly', label: 'Hand truck', answer: 'Hand truck', imageKey: 'log-dolly', x: 70, y: 25, w: 20, h: 32 },
        { id: 'scanner', label: 'Scanner', answer: 'Scanner', imageKey: 'log-scanner', x: 40, y: 48, w: 18, h: 24 },
      ],
    },
    {
      id: 'floor-b-vest',
      title: 'Floor walk B',
      instruction: 'Find the safety vest. Tap it in the scene, then confirm the English name.',
      targetId: 'vest',
      distractors: ['Manifest', 'Shipping label', 'Storage rack'],
      variantGroup: 'floor-vest',
      hotspots: [
        { id: 'manifest', label: 'Manifest', answer: 'Manifest', imageKey: 'log-manifest', x: 12, y: 50, w: 22, h: 24 },
        { id: 'vest', label: 'Safety vest', answer: 'Safety vest', imageKey: 'log-vest', x: 48, y: 18, w: 22, h: 28 },
        { id: 'label', label: 'Shipping label', answer: 'Shipping label', imageKey: 'log-label', x: 70, y: 55, w: 20, h: 22 },
        { id: 'rack', label: 'Storage rack', answer: 'Storage rack', imageKey: 'log-rack', x: 30, y: 12, w: 22, h: 30 },
      ],
    },
  ],
  workplaceInstructions: [
    {
      text: 'Scan the shipping label.',
      correct: 'Scan the shipping label',
      imageKey: 'log-label',
      options: ['Scan the shipping label', 'Move the pallet first', 'Remove your vest', 'Climb the rack'],
      supportHint: hint(
        'Scan the shipping label.',
        'Escanea la etiqueta de envio.',
        'Imsah bitagat al-shahn.',
        'Shipping label scan karo.',
        'Shipping label scan adirgu.',
        'Shipping label scan gebiru.',
      ),
    },
    {
      text: 'Put on your safety vest before you enter.',
      correct: 'Put on your safety vest before you enter',
      imageKey: 'log-vest',
      options: [
        'Put on your safety vest before you enter',
        'Leave the vest in the break room',
        'Start loading without gear',
        'Stand in the forklift path',
      ],
      supportHint: hint(
        'Put on your safety vest before you enter.',
        'Ponte el chaleco antes de entrar.',
        'Irtiadi al-sitra qabla al-dukhul.',
        'Andar jane se pehle safety vest pehno.',
        'Ke megebat befit safety vest asdigu.',
        'Qidmi meAtat safety vest asdugu.',
      ),
    },
    {
      text: 'Load the boxes onto the pallet.',
      correct: 'Load the boxes onto the pallet',
      imageKey: 'log-pallet',
      options: ['Load the boxes onto the pallet', 'Throw boxes into the aisle', 'Block the exit', 'Ignore the manifest'],
      supportHint: hint(
        'Load the boxes onto the pallet.',
        'Carga las cajas en la paleta.',
        'Hammal al-sanadiq ala al-tabiq.',
        'Boxes ko palette par load karo.',
        'Sandukochun be palette lay asferu.',
        'Sandukkat ab palette asferu.',
      ),
    },
    {
      text: 'Check the manifest before loading.',
      correct: 'Check the manifest before loading',
      imageKey: 'log-manifest',
      options: [
        'Check the manifest before loading',
        'Load anything nearby',
        'Skip the count',
        'Sign a blank page',
      ],
      supportHint: hint(
        'Check the manifest before loading.',
        'Revisa el manifiesto antes de cargar.',
        'Raji al-qaima qabla al-tahmil.',
        'Load se pehle manifest check karo.',
        'Ke meferat befit manifest yaregagtu.',
        'Qidmi meferat manifest aregagtsu.',
      ),
    },
    {
      text: 'Use the hand truck for heavy boxes.',
      correct: 'Use the hand truck for heavy boxes',
      imageKey: 'log-dolly',
      options: [
        'Use the hand truck for heavy boxes',
        'Carry overloaded stacks alone',
        'Slide boxes with your feet',
        'Climb onto the rack',
      ],
      supportHint: hint(
        'Use the hand truck for heavy boxes.',
        'Usa la carretilla para cajas pesadas.',
        'Istakhdim arabat al-yad lil-sanadiq al-thaqila.',
        'Bhari boxes ke liye hand truck use karo.',
        'Lezinu sandukoch le hand truck techemu.',
        'Nkabd sandukkat hand truck tegberu.',
      ),
    },
  ],
  sitePhrases: [
    {
      en: 'Scan before you stage.',
      why: 'Accuracy before placement.',
      prompt: 'What does this phrase mean?',
      answer: 'Scan the label before you place the item',
      options: [
        'Scan the label before you place the item',
        'Place first, scan later',
        'Skip scanning',
        'Mark it by hand only',
      ],
    },
    {
      en: 'Watch the forklift path.',
      why: 'Equipment always gets space.',
      prompt: 'What should you do?',
      answer: 'Stay clear of moving equipment',
      options: ['Stay clear of moving equipment', 'Stand behind it', 'Run across the path', 'Remove your vest'],
    },
    {
      en: 'Keep the aisle clear.',
      why: 'People and machines need a safe path.',
      prompt: 'What does this phrase mean?',
      answer: 'Do not block the walkway',
      options: ['Do not block the walkway', 'Stack boxes in the aisle', 'Park across the path', 'Leave litter on the floor'],
    },
    {
      en: 'Stage it in bay three.',
      why: 'Short placement direction.',
      prompt: 'What should you do?',
      answer: 'Put it in bay three for now',
      options: ['Put it in bay three for now', 'Throw it away', 'Take it home', 'Ignore the order'],
    },
  ],
  safetyQuiz: [
    {
      id: 'ls1',
      prompt: 'What must you wear before entering the warehouse floor?',
      emoji: 'SV',
      imageKey: 'log-vest',
      options: ['Safety vest', 'Sandals', 'Loose scarf only', 'Nothing'],
      answer: 'Safety vest',
      teachCorrect: 'Bright vest on before you enter the floor.',
      teachWrong: 'Safety vest first — people must see you.',
    },
    {
      id: 'ls2',
      prompt: 'A forklift is moving toward your aisle. What do you do?',
      emoji: 'FK',
      options: ['Step clear and make eye contact', 'Walk behind it closely', 'Wave it to speed up', 'Stand in the path'],
      answer: 'Step clear and make eye contact',
      teachCorrect: 'Give equipment space and confirm the driver sees you.',
      teachWrong: 'Never stand in a forklift path.',
    },
    {
      id: 'ls3',
      prompt: 'Where do heavy boxes belong when moving them?',
      emoji: 'HT',
      imageKey: 'log-dolly',
      options: ['On a hand truck or approved cart', 'Balanced on your head', 'Dragged across the floor', 'Stacked past your eyesight'],
      answer: 'On a hand truck or approved cart',
      teachCorrect: 'Use the right cart. Protect your back.',
      teachWrong: 'Hand truck or approved cart for heavy loads.',
    },
    {
      id: 'ls4',
      prompt: 'You see a spill in the aisle. First action?',
      emoji: 'SP',
      options: ['Report it / make the area safe', 'Walk through it', 'Cover it with cardboard and leave', 'Ignore it'],
      answer: 'Report it / make the area safe',
      teachCorrect: 'Spills cause falls. Control the area first.',
      teachWrong: 'Report and control spills immediately.',
    },
  ],
  toolCategories: [
    {
      title: 'Manual handling tools',
      why: 'Hand trucks and carts you push or pull.',
      mark: 'MH',
      prompt: 'Hand trucks and carts belong to which group?',
      answer: 'Manual handling tools',
      options: ['Manual handling tools', 'Powered equipment', 'Packaging materials', 'Scanning devices'],
    },
    {
      title: 'Powered equipment',
      why: 'Forklifts and powered pallet jacks need training.',
      mark: 'PE',
      prompt: 'Forklifts belong to which group?',
      answer: 'Powered equipment',
      options: ['Packaging materials', 'Powered equipment', 'Manual handling tools', 'Paperwork'],
    },
    {
      title: 'Packaging materials',
      why: 'Pallets, wrap, and cartons protect goods in motion.',
      mark: 'PK',
      prompt: 'Pallets and wrap belong to which group?',
      answer: 'Packaging materials',
      options: ['Scanning devices', 'Powered equipment', 'Packaging materials', 'Floor markings'],
    },
    {
      title: 'Scanning devices',
      why: 'Scanners and printers keep inventory accurate.',
      mark: 'SD',
      prompt: 'Barcode scanners belong to which group?',
      answer: 'Scanning devices',
      options: ['Manual handling tools', 'Packaging materials', 'Scanning devices', 'Powered equipment'],
    },
  ],
  systemTopics: [
    {
      title: 'Receiving',
      why: 'Goods arrive, get checked, and enter inventory.',
      mark: 'RC',
      prompt: 'Checking inbound goods is part of…',
      answer: 'Receiving',
      options: ['Receiving', 'Shipping', 'Returns', 'Inventory counts'],
    },
    {
      title: 'Put-away',
      why: 'Move received goods to the correct storage location.',
      mark: 'PA',
      prompt: 'Placing goods into the right rack is…',
      answer: 'Put-away',
      options: ['Shipping', 'Put-away', 'Returns', 'Cycle count'],
    },
    {
      title: 'Picking',
      why: 'Collect ordered items accurately and on time.',
      mark: 'PK',
      prompt: 'Collecting items for an order is…',
      answer: 'Picking',
      options: ['Receiving', 'Picking', 'Staging', 'Returns'],
    },
    {
      title: 'Shipping',
      why: 'Stage, load, and send outbound orders.',
      mark: 'SH',
      prompt: 'Loading a truck for delivery is part of…',
      answer: 'Shipping',
      options: ['Put-away', 'Receiving', 'Shipping', 'Inventory counts'],
    },
    {
      title: 'Inventory accuracy',
      why: 'Counts and scans keep systems true.',
      mark: 'IA',
      prompt: 'Scan-and-count checks support…',
      answer: 'Inventory accuracy',
      options: ['Inventory accuracy', 'Break schedules', 'Parking rules', 'Uniforms'],
    },
  ],
  observationScenarios: [
    {
      id: 'vest-entry',
      title: 'Safety vest before entry',
      situation: 'Your supervisor asks you to enter the warehouse floor ready for work.',
      skill: 'Safety vest check',
      steps: [
        { id: 'vest', label: 'Safety vest on and visible', correctOrder: 1 },
        { id: 'shoes', label: 'Closed footwear confirmed', correctOrder: 2 },
        { id: 'path', label: 'Check the aisle is clear of equipment', correctOrder: 3 },
        { id: 'enter', label: 'Enter the floor only after gear is ready', correctOrder: 4 },
      ],
      passNote: 'Competent means gear is correct BEFORE you cross the line, every time.',
    },
    {
      id: 'scan-stage',
      title: 'Scan before you stage',
      situation: 'Your supervisor watches you prepare a package for staging.',
      skill: 'Scanner',
      steps: [
        { id: 'read', label: 'Read the shipping label', correctOrder: 1 },
        { id: 'scan', label: 'Scan the barcode and wait for confirmation', correctOrder: 2 },
        { id: 'match', label: 'Match the screen to the destination bay', correctOrder: 3 },
        { id: 'stage', label: 'Stage the package in the correct bay', correctOrder: 4 },
      ],
      passNote: 'Scan first. Stage second. Accuracy beats speed.',
    },
    {
      id: 'pallet-load',
      title: 'Build a stable pallet',
      situation: 'Your supervisor asks you to show a safe pallet stack.',
      skill: 'Pallet',
      steps: [
        { id: 'base', label: 'Start with a sound, flat pallet', correctOrder: 1 },
        { id: 'stack', label: 'Stack boxes evenly with no overhang', correctOrder: 2 },
        { id: 'wrap', label: 'Secure the load as trained', correctOrder: 3 },
        { id: 'report', label: 'Tell the supervisor the load is ready', correctOrder: 4 },
      ],
      passNote: 'Stable loads protect people and product.',
    },
    {
      id: 'dolly-pass',
      title: 'Move a load with a hand truck',
      situation: 'Your supervisor asks you to move heavy boxes safely.',
      skill: 'Hand truck',
      steps: [
        { id: 'clear', label: 'Clear the path ahead', correctOrder: 1 },
        { id: 'load', label: 'Load the hand truck with a balanced stack', correctOrder: 2 },
        { id: 'tilt', label: 'Tilt back carefully and walk steady', correctOrder: 3 },
        { id: 'set', label: 'Set down gently and park the truck clear of the aisle', correctOrder: 4 },
      ],
      passNote: 'Never rush a load through a busy aisle.',
    },
  ],
  siteDecisions: [
    {
      id: 'spill',
      title: 'Aisle spill',
      scene: 'You arrive on the floor. There is liquid in the main aisle.',
      prompt: 'What should you do first?',
      options: [
        'Report it / make the area safe',
        'Walk through and keep working',
        'Cover it and leave',
        'Film it for social media',
      ],
      answer: 'Report it / make the area safe',
      teachCorrect: 'See something unsafe, speak up and make it safe.',
      teachWrong: 'Hazards get reported and controlled first.',
    },
    {
      id: 'direction',
      title: 'Supervisor direction',
      scene: 'Your supervisor says: “Stage the pallet in bay two.”',
      prompt: 'What do you do?',
      options: [
        'Stage the pallet in bay two',
        'Put it wherever is closest',
        'Leave it in the aisle',
        'Ask a friend to guess',
      ],
      answer: 'Stage the pallet in bay two',
      teachCorrect: 'Follow clear directions. Confirm the bay if unsure.',
      teachWrong: 'Bay two means bay two.',
    },
    {
      id: 'forklift',
      title: 'Moving equipment',
      scene: 'A forklift is reversing near your pick path.',
      prompt: 'Best action?',
      options: [
        'Stop, make eye contact, wait for a clear path',
        'Squeeze past behind it',
        'Tap the machine to hurry',
        'Jog across the path',
      ],
      answer: 'Stop, make eye contact, wait for a clear path',
      teachCorrect: 'People yield to equipment until the path is clear.',
      teachWrong: 'Never assume the driver sees you.',
    },
    {
      id: 'mismatch',
      title: 'Label mismatch',
      scene: 'The shipping label and the screen destination do not match.',
      prompt: 'What should you do?',
      options: [
        'Stop and ask a supervisor before staging',
        'Ship it anyway to save time',
        'Change the label yourself',
        'Hide the package',
      ],
      answer: 'Stop and ask a supervisor before staging',
      teachCorrect: 'Accuracy errors get escalated, never forced through.',
      teachWrong: 'Do not stage a mismatch.',
    },
  ],
  finalQuiz: [
    {
      id: 'lf1',
      prompt: 'Which item reads barcodes?',
      emoji: 'SC',
      imageKey: 'log-scanner',
      options: ['Scanner', 'Pallet', 'Hand truck', 'Storage rack'],
      answer: 'Scanner',
      teachCorrect: 'The scanner reads barcodes.',
      teachWrong: 'Use a scanner for barcodes.',
    },
    {
      id: 'lf2',
      prompt: 'What must you wear on the warehouse floor?',
      emoji: 'SV',
      imageKey: 'log-vest',
      options: ['Safety vest', 'Open-toe shoes', 'No vest needed', 'Headphones only'],
      answer: 'Safety vest',
      teachCorrect: 'Safety vest on the floor.',
      teachWrong: 'Wear a safety vest on the floor.',
    },
    {
      id: 'lf3',
      prompt: 'Collecting items for an order is called…',
      emoji: 'PK',
      options: ['Picking', 'Receiving', 'Returns', 'Break'],
      answer: 'Picking',
      teachCorrect: 'Picking collects ordered items.',
      teachWrong: 'Picking is collecting for an order.',
    },
    {
      id: 'lf4',
      prompt: 'If a spill blocks an aisle, you should…',
      emoji: 'SP',
      options: ['Report it / make the area safe', 'Ignore it', 'Run through it', 'Blame a coworker'],
      answer: 'Report it / make the area safe',
      teachCorrect: 'Control hazards first.',
      teachWrong: 'Report and control spills.',
    },
  ],
  employmentPrep: [
    {
      id: 'log-intro',
      prompt: 'An employer asks: “Why Purpose Academy?” Best answer?',
      options: [
        'I learned logistics foundations, safety, and workplace English with instructors who checked my skills',
        'I watched a few videos once',
        'I do not need safety training',
        'I only want a paycheck with no learning',
      ],
      answer: 'I learned logistics foundations, safety, and workplace English with instructors who checked my skills',
      teachCorrect: 'Connect your training to safety, language, and verified skill.',
      teachWrong: 'Employers want proof of foundations, not shortcuts.',
    },
    {
      id: 'log-safety',
      prompt: 'Interview question: “What do you put on before entering the warehouse floor?”',
      options: [
        'Safety vest and required gear',
        'Headphones only',
        'Nothing special',
        'Open-toe shoes',
      ],
      answer: 'Safety vest and required gear',
      teachCorrect: 'Lead with safety. It shows you are floor-ready.',
      teachWrong: 'Always name safety vest / required gear before entry.',
    },
    {
      id: 'log-team',
      prompt: 'A partner says: “Scan that label.” You should…',
      options: [
        'Scan the label and confirm the screen',
        'Guess the destination',
        'Ignore the request',
        'Throw the scanner',
      ],
      answer: 'Scan the label and confirm the screen',
      teachCorrect: 'Short workplace talk + accurate scanning = good teammate.',
      teachWrong: 'Scan carefully. Confirm before you stage.',
    },
    {
      id: 'log-learn',
      prompt: 'An employer asks how you learn new tasks. Best answer?',
      options: [
        'I listen, practise with an instructor, and ask when I am unsure',
        'I guess and hope nobody notices',
        'I refuse to learn English for the job',
        'I skip safety if it slows me down',
      ],
      answer: 'I listen, practise with an instructor, and ask when I am unsure',
      teachCorrect: 'Employers hire people who learn carefully and ask good questions.',
      teachWrong: 'Show that you practise with guidance and ask when unsure.',
    },
    {
      id: 'log-schedule',
      prompt: 'A partner asks if you can start at 7:00 a.m. You should…',
      options: [
        'Give an honest answer about your availability',
        'Say yes to everything even if you cannot come',
        'Ignore the message',
        'Ask them to text your password',
      ],
      answer: 'Give an honest answer about your availability',
      teachCorrect: 'Clear, honest scheduling builds trust.',
      teachWrong: 'Be honest about when you can start work.',
    },
    {
      id: 'log-ready',
      prompt: 'You arrive for a warehouse walk-through. Best first move?',
      options: [
        'Bring and wear required safety gear',
        'Wear sandals for comfort',
        'Leave PPE in the car',
        'Arrive without confirming the meeting place',
      ],
      answer: 'Bring and wear required safety gear',
      teachCorrect: 'Show up ready: gear on, professional, on time.',
      teachWrong: 'Bring PPE and be ready for the floor walk.',
    },
  ],
  unitCheckpoints: {
    3: [
      {
        id: 'uc3-l1',
        prompt: 'Which device reads barcodes?',
        emoji: 'SC',
        imageKey: 'log-scanner',
        options: ['Scanner', 'Pallet', 'Safety vest', 'Hand truck'],
        answer: 'Scanner',
        teachCorrect: 'Scanner reads barcodes.',
        teachWrong: 'The scanner reads barcodes.',
      },
      {
        id: 'uc3-l2',
        prompt: 'What must you wear before entering the floor?',
        emoji: 'SV',
        imageKey: 'log-vest',
        options: ['Safety vest', 'Sandals', 'Nothing', 'Loose scarf only'],
        answer: 'Safety vest',
        teachCorrect: 'Vest on before entry.',
        teachWrong: 'Wear a safety vest first.',
      },
      {
        id: 'uc3-l3',
        prompt: 'Heavy boxes should move on a…',
        emoji: 'HT',
        imageKey: 'log-dolly',
        options: ['Hand truck', 'Your head', 'Open hands only', 'The forklift forks while standing on them'],
        answer: 'Hand truck',
        teachCorrect: 'Use a hand truck for heavy boxes.',
        teachWrong: 'Hand truck for heavy loads.',
      },
    ],
    4: [
      {
        id: 'uc4-l1',
        prompt: '“Scan before you stage” means…',
        emoji: 'SC',
        options: ['Scan the label before you place the item', 'Place first', 'Never scan', 'Ask a friend to guess'],
        answer: 'Scan the label before you place the item',
        teachCorrect: 'Scan first, then stage.',
        teachWrong: 'Scan before staging.',
      },
      {
        id: 'uc4-l2',
        prompt: 'Keep the aisle clear means…',
        emoji: 'AL',
        options: ['Do not block the walkway', 'Stack boxes in the aisle', 'Park across the path', 'Leave spills'],
        answer: 'Do not block the walkway',
        teachCorrect: 'Aisles stay clear for people and equipment.',
        teachWrong: 'Do not block walkways.',
      },
    ],
    5: [
      {
        id: 'uc5-l1',
        prompt: 'Receiving is when goods…',
        emoji: 'RC',
        options: ['Arrive and get checked in', 'Leave on a truck only', 'Are thrown away', 'Skip inventory'],
        answer: 'Arrive and get checked in',
        teachCorrect: 'Receiving checks inbound goods.',
        teachWrong: 'Receiving is inbound check-in.',
      },
      {
        id: 'uc5-l2',
        prompt: 'Forklifts belong to…',
        emoji: 'PE',
        options: ['Powered equipment', 'Packaging materials', 'Paperwork', 'Break rooms'],
        answer: 'Powered equipment',
        teachCorrect: 'Forklifts are powered equipment.',
        teachWrong: 'Powered equipment needs training.',
      },
    ],
  },
}
