#!/usr/bin/env python3
"""Generate constructionVocab660.ts (+ shared first-200 export) from OCR/curated JSON."""
from __future__ import annotations

import json
import re
from pathlib import Path

SRC = Path("/tmp/con-vv-extract/vocab660.json")
CURATED = Path("/cursor/stores/self/construction-vv/gloss-overrides.json")
INDEX = Path("/cursor/stores/self/construction-vv/words-001-660-full-index.json")
OUT = Path("src/pathways/packs/constructionVocab660.ts")


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def term_block(t: dict) -> str:
    g = t["gloss"]
    return (
        "  {\n"
        f"    id: '{esc(t['id'])}',\n"
        f"    english: '{esc(t['english'])}',\n"
        f"    emoji: '{esc(t['emoji'])}',\n"
        f"    imageKey: '{esc(t['imageKey'])}',\n"
        f"    definition: '{esc(t['definition'])}',\n"
        f"    sentence: '{esc(t['sentence'])}',\n"
        f"    gloss: gloss('{esc(g.get('Spanish',''))}', '{esc(g.get('Arabic',''))}', "
        f"'{esc(g.get('Hindi',''))}', '{esc(g.get('Amharic',''))}', '{esc(g.get('Tigrinya',''))}'),\n"
        "  },\n"
    )


def main():
    index = {i["n"]: i for i in json.loads(INDEX.read_text(encoding="utf-8"))["englishIndex"]}
    by_n: dict[int, dict] = {}
    if SRC.exists():
        for t in json.loads(SRC.read_text(encoding="utf-8")):
            by_n[t["n"]] = t
    if CURATED.exists():
        for t in json.loads(CURATED.read_text(encoding="utf-8")):
            n = t["n"]
            if n in by_n:
                # merge gloss overrides (non-empty wins)
                for lang, val in (t.get("gloss") or {}).items():
                    if val:
                        by_n[n].setdefault("gloss", {})[lang] = val
                if t.get("sentence"):
                    by_n[n]["sentence"] = t["sentence"]
                if t.get("english"):
                    by_n[n]["english"] = t["english"]
            else:
                by_n[n] = t

    # Ensure all 660 exist (fill missing from index with empty gloss)
    for n, meta in index.items():
        if n not in by_n:
            slug = re.sub(r"[^a-z0-9]+", "-", meta["english"].lower()).strip("-")[:40]
            by_n[n] = {
                "n": n,
                "id": f"{slug}-{n:03d}",
                "english": meta["english"],
                "emoji": "".join(w[0] for w in re.findall(r"[A-Za-z0-9]+", meta["english"])[:2]).upper()[:2] or "VV",
                "imageKey": f"con-vv-{n:03d}",
                "definition": f"A construction workplace word: {meta['english']}.",
                "sentence": meta["sentence"],
                "gloss": {k: "" for k in ["Amharic", "Tigrinya", "Arabic", "Spanish", "Hindi"]},
            }

    terms = [by_n[n] for n in sorted(by_n)]
    assert len(terms) == 660

    header = (
        "/**\n"
        " * Purpose Academy Construction Visual Vocabulary — words 1–660.\n"
        " * Exact worksheet translations (Amharic, Tigrinya, Arabic, Spanish, Hindi — no French)\n"
        " * and workplace sentences from Construction Visual Vocabulary (pages 1–30).\n"
        " * Images: public/media/construction-vv/con-vv-NNN.jpg\n"
        " * Generated by scripts/generate-construction-vocab-ts.py — do not hand-edit bulk rows.\n"
        " */\n"
        "import type { VocabTerm } from '../../student/journeyCurriculum'\n"
        "import { gloss } from '../packHelpers'\n\n"
        "export const CONSTRUCTION_VOCAB_660: VocabTerm[] = [\n"
    )
    body = "".join(term_block(t) for t in terms)
    OUT.write_text(header + body + "]\n", encoding="utf-8")

    empty = sum(1 for t in terms if not all(t["gloss"].get(k) for k in ["Amharic", "Tigrinya", "Arabic", "Spanish", "Hindi"]))
    print(f"Wrote {OUT} ({len(terms)} terms); incomplete gloss rows: {empty}")


if __name__ == "__main__":
    main()
